// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatdata

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AcademyFavorScheduleExcelTable struct {
	_tab flatbuffers.Table
}

func GetRootAsAcademyFavorScheduleExcelTable(buf []byte, offset flatbuffers.UOffsetT) *AcademyFavorScheduleExcelTable {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AcademyFavorScheduleExcelTable{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsAcademyFavorScheduleExcelTable(buf []byte, offset flatbuffers.UOffsetT) *AcademyFavorScheduleExcelTable {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AcademyFavorScheduleExcelTable{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *AcademyFavorScheduleExcelTable) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AcademyFavorScheduleExcelTable) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AcademyFavorScheduleExcelTable) DataList(obj *AcademyFavorScheduleExcel, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *AcademyFavorScheduleExcelTable) DataListLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func AcademyFavorScheduleExcelTableStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func AcademyFavorScheduleExcelTableAddDataList(builder *flatbuffers.Builder, dataList flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(dataList), 0)
}
func AcademyFavorScheduleExcelTableStartDataListVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func AcademyFavorScheduleExcelTableEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
