// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatdata

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BattleLevelFactorExcelTable struct {
	_tab flatbuffers.Table
}

func GetRootAsBattleLevelFactorExcelTable(buf []byte, offset flatbuffers.UOffsetT) *BattleLevelFactorExcelTable {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BattleLevelFactorExcelTable{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsBattleLevelFactorExcelTable(buf []byte, offset flatbuffers.UOffsetT) *BattleLevelFactorExcelTable {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BattleLevelFactorExcelTable{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *BattleLevelFactorExcelTable) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BattleLevelFactorExcelTable) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BattleLevelFactorExcelTable) DataList(obj *BattleLevelFactorExcel, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *BattleLevelFactorExcelTable) DataListLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func BattleLevelFactorExcelTableStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func BattleLevelFactorExcelTableAddDataList(builder *flatbuffers.Builder, dataList flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(dataList), 0)
}
func BattleLevelFactorExcelTableStartDataListVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func BattleLevelFactorExcelTableEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
