// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatdata

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CharacterStatLimitExcelTable struct {
	_tab flatbuffers.Table
}

func GetRootAsCharacterStatLimitExcelTable(buf []byte, offset flatbuffers.UOffsetT) *CharacterStatLimitExcelTable {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CharacterStatLimitExcelTable{}
	x.Init(buf, n+offset)
	return x
}

func FinishCharacterStatLimitExcelTableBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCharacterStatLimitExcelTable(buf []byte, offset flatbuffers.UOffsetT) *CharacterStatLimitExcelTable {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CharacterStatLimitExcelTable{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCharacterStatLimitExcelTableBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CharacterStatLimitExcelTable) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CharacterStatLimitExcelTable) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CharacterStatLimitExcelTable) DataList(obj *CharacterStatLimitExcel, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *CharacterStatLimitExcelTable) DataListLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func CharacterStatLimitExcelTableStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func CharacterStatLimitExcelTableAddDataList(builder *flatbuffers.Builder, dataList flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(dataList), 0)
}
func CharacterStatLimitExcelTableStartDataListVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func CharacterStatLimitExcelTableEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
