// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatdata

import "strconv"

type ConquestTileType int32

const (
	ConquestTileTypeNone   ConquestTileType = 0
	ConquestTileTypeStart  ConquestTileType = 1
	ConquestTileTypeNormal ConquestTileType = 2
	ConquestTileTypeBattle ConquestTileType = 3
	ConquestTileTypeBase   ConquestTileType = 4
)

var EnumNamesConquestTileType = map[ConquestTileType]string{
	ConquestTileTypeNone:   "None",
	ConquestTileTypeStart:  "Start",
	ConquestTileTypeNormal: "Normal",
	ConquestTileTypeBattle: "Battle",
	ConquestTileTypeBase:   "Base",
}

var EnumValuesConquestTileType = map[string]ConquestTileType{
	"None":   ConquestTileTypeNone,
	"Start":  ConquestTileTypeStart,
	"Normal": ConquestTileTypeNormal,
	"Battle": ConquestTileTypeBattle,
	"Base":   ConquestTileTypeBase,
}

func (v ConquestTileType) String() string {
	if s, ok := EnumNamesConquestTileType[v]; ok {
		return s
	}
	return "ConquestTileType(" + strconv.FormatInt(int64(v), 10) + ")"
}
