// Code generated by fbsgen. DO NOT EDIT.
// Package flatdata contains generated code for a FlatBuffers schema.
package flatdata

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// ConstArenaExcelDto represents a FlatBuffers table.
type ConstArenaExcelDto struct {
	fbsutils.FlatBuffer
	AttackCoolTime                     int64      `json:"attack_cool_time"`
	BattleDuration                     int64      `json:"battle_duration"`
	DefenseCoolTime                    int64      `json:"defense_cool_time"`
	TssStartCoolTime                   int64      `json:"tss_start_cool_time"`
	EndAlarm                           int64      `json:"end_alarm"`
	TimeRewardMaxAmount                int64      `json:"time_reward_max_amount"`
	EnterCostType                      ParcelType `json:"enter_cost_type"`
	EnterCostID                        int64      `json:"enter_cost_id"`
	TicketCost                         int64      `json:"ticket_cost"`
	DailyRewardResetTime               string     `json:"daily_reward_reset_time"`
	OpenScenarioID                     string     `json:"open_scenario_id"`
	CharacterSlotHideRank              []int64    `json:"character_slot_hide_rank"`
	MapSlotHideRank                    int64      `json:"map_slot_hide_rank"`
	RelativeOpponentRankStart          []int64    `json:"relative_opponent_rank_start"`
	RelativeOpponentRankEnd            []int64    `json:"relative_opponent_rank_end"`
	ModifiedStatType                   []StatType `json:"modified_stat_type"`
	StatMulFactor                      []int64    `json:"stat_mul_factor"`
	StatSumFactor                      []int64    `json:"stat_sum_factor"`
	NpcName                            []string   `json:"npc_name"`
	NpcMainCharacterCount              int64      `json:"npc_main_character_count"`
	NpcSupportCharacterCount           int64      `json:"npc_support_character_count"`
	NpcCharacterSkillLevel             int64      `json:"npc_character_skill_level"`
	TimeSpanInDaysForBattleHistory     int64      `json:"time_span_in_days_for_battle_history"`
	HiddenCharacterImagePath           string     `json:"hidden_character_image_path"`
	DefenseVictoryRewardMaxCount       int64      `json:"defense_victory_reward_max_count"`
	TopRankerCountLimit                int64      `json:"top_ranker_count_limit"`
	AutoRefreshIntervalMilliSeconds    int64      `json:"auto_refresh_interval_milli_seconds"`
	EchelonSettingIntervalMilliSeconds int64      `json:"echelon_setting_interval_milli_seconds"`
	SkipAllowedTimeMilliSeconds        int64      `json:"skip_allowed_time_milli_seconds"`
	ShowSeasonChangeInfoStartTime      string     `json:"show_season_change_info_start_time"`
	ShowSeasonChangeInfoEndTime        string     `json:"show_season_change_info_end_time"`
	ShowSeasonID                       int64      `json:"show_season_id"`
	ArenaHistoryQueryLimitDays         int32      `json:"arena_history_query_limit_days"`
}

// MarshalModel marshals the struct into a FlatBuffers offset.
func (t *ConstArenaExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("ConstArena"))
	}
	dailyRewardResetTimeOffset := b.CreateString(fbsutils.Encode(t.DailyRewardResetTime, t.FlatBuffer.TableKey))
	openScenarioIDOffset := b.CreateString(fbsutils.Encode(t.OpenScenarioID, t.FlatBuffer.TableKey))
	ConstArenaExcelStartCharacterSlotHideRankVector(b, len(t.CharacterSlotHideRank))
	for i := len(t.CharacterSlotHideRank) - 1; i >= 0; i-- {
		b.PrependInt64(fbsutils.Encode(t.CharacterSlotHideRank[i], t.FlatBuffer.TableKey))
	}
	characterSlotHideRankOffset := b.EndVector(len(t.CharacterSlotHideRank))
	ConstArenaExcelStartRelativeOpponentRankStartVector(b, len(t.RelativeOpponentRankStart))
	for i := len(t.RelativeOpponentRankStart) - 1; i >= 0; i-- {
		b.PrependInt64(fbsutils.Encode(t.RelativeOpponentRankStart[i], t.FlatBuffer.TableKey))
	}
	relativeOpponentRankStartOffset := b.EndVector(len(t.RelativeOpponentRankStart))
	ConstArenaExcelStartRelativeOpponentRankEndVector(b, len(t.RelativeOpponentRankEnd))
	for i := len(t.RelativeOpponentRankEnd) - 1; i >= 0; i-- {
		b.PrependInt64(fbsutils.Encode(t.RelativeOpponentRankEnd[i], t.FlatBuffer.TableKey))
	}
	relativeOpponentRankEndOffset := b.EndVector(len(t.RelativeOpponentRankEnd))
	ConstArenaExcelStartModifiedStatTypeVector(b, len(t.ModifiedStatType))
	for i := len(t.ModifiedStatType) - 1; i >= 0; i-- {
		b.PrependInt32(fbsutils.Encode(int32(t.ModifiedStatType[i]), t.FlatBuffer.TableKey))
	}
	modifiedStatTypeOffset := b.EndVector(len(t.ModifiedStatType))
	ConstArenaExcelStartStatMulFactorVector(b, len(t.StatMulFactor))
	for i := len(t.StatMulFactor) - 1; i >= 0; i-- {
		b.PrependInt64(fbsutils.Encode(t.StatMulFactor[i], t.FlatBuffer.TableKey))
	}
	statMulFactorOffset := b.EndVector(len(t.StatMulFactor))
	ConstArenaExcelStartStatSumFactorVector(b, len(t.StatSumFactor))
	for i := len(t.StatSumFactor) - 1; i >= 0; i-- {
		b.PrependInt64(fbsutils.Encode(t.StatSumFactor[i], t.FlatBuffer.TableKey))
	}
	statSumFactorOffset := b.EndVector(len(t.StatSumFactor))
	var npcNameOffset flatbuffers.UOffsetT
	npcNameOffsets := make([]flatbuffers.UOffsetT, len(t.NpcName))
	for i := range t.NpcName {
		npcNameOffsets[i] = b.CreateString(fbsutils.Encode(t.NpcName[i], t.FlatBuffer.TableKey))
	}
	ConstArenaExcelStartNpcNameVector(b, len(t.NpcName))
	for i := len(npcNameOffsets) - 1; i >= 0; i-- {
		b.PrependUOffsetT(npcNameOffsets[i])
	}
	npcNameOffset = b.EndVector(len(t.NpcName))
	hiddenCharacterImagePathOffset := b.CreateString(fbsutils.Encode(t.HiddenCharacterImagePath, t.FlatBuffer.TableKey))
	showSeasonChangeInfoStartTimeOffset := b.CreateString(fbsutils.Encode(t.ShowSeasonChangeInfoStartTime, t.FlatBuffer.TableKey))
	showSeasonChangeInfoEndTimeOffset := b.CreateString(fbsutils.Encode(t.ShowSeasonChangeInfoEndTime, t.FlatBuffer.TableKey))
	ConstArenaExcelStart(b)
	ConstArenaExcelAddAttackCoolTime(b, fbsutils.Encode(t.AttackCoolTime, t.FlatBuffer.TableKey))
	ConstArenaExcelAddBattleDuration(b, fbsutils.Encode(t.BattleDuration, t.FlatBuffer.TableKey))
	ConstArenaExcelAddDefenseCoolTime(b, fbsutils.Encode(t.DefenseCoolTime, t.FlatBuffer.TableKey))
	ConstArenaExcelAddTssStartCoolTime(b, fbsutils.Encode(t.TssStartCoolTime, t.FlatBuffer.TableKey))
	ConstArenaExcelAddEndAlarm(b, fbsutils.Encode(t.EndAlarm, t.FlatBuffer.TableKey))
	ConstArenaExcelAddTimeRewardMaxAmount(b, fbsutils.Encode(t.TimeRewardMaxAmount, t.FlatBuffer.TableKey))
	ConstArenaExcelAddEnterCostType(b, ParcelType(fbsutils.Encode(int32(t.EnterCostType), t.FlatBuffer.TableKey)))
	ConstArenaExcelAddEnterCostId(b, fbsutils.Encode(t.EnterCostID, t.FlatBuffer.TableKey))
	ConstArenaExcelAddTicketCost(b, fbsutils.Encode(t.TicketCost, t.FlatBuffer.TableKey))
	ConstArenaExcelAddDailyRewardResetTime(b, dailyRewardResetTimeOffset)
	ConstArenaExcelAddOpenScenarioId(b, openScenarioIDOffset)
	ConstArenaExcelAddCharacterSlotHideRank(b, characterSlotHideRankOffset)
	ConstArenaExcelAddMapSlotHideRank(b, fbsutils.Encode(t.MapSlotHideRank, t.FlatBuffer.TableKey))
	ConstArenaExcelAddRelativeOpponentRankStart(b, relativeOpponentRankStartOffset)
	ConstArenaExcelAddRelativeOpponentRankEnd(b, relativeOpponentRankEndOffset)
	ConstArenaExcelAddModifiedStatType(b, modifiedStatTypeOffset)
	ConstArenaExcelAddStatMulFactor(b, statMulFactorOffset)
	ConstArenaExcelAddStatSumFactor(b, statSumFactorOffset)
	ConstArenaExcelAddNpcName(b, npcNameOffset)
	ConstArenaExcelAddNpcMainCharacterCount(b, fbsutils.Encode(t.NpcMainCharacterCount, t.FlatBuffer.TableKey))
	ConstArenaExcelAddNpcSupportCharacterCount(b, fbsutils.Encode(t.NpcSupportCharacterCount, t.FlatBuffer.TableKey))
	ConstArenaExcelAddNpcCharacterSkillLevel(b, fbsutils.Encode(t.NpcCharacterSkillLevel, t.FlatBuffer.TableKey))
	ConstArenaExcelAddTimeSpanInDaysForBattleHistory(b, fbsutils.Encode(t.TimeSpanInDaysForBattleHistory, t.FlatBuffer.TableKey))
	ConstArenaExcelAddHiddenCharacterImagePath(b, hiddenCharacterImagePathOffset)
	ConstArenaExcelAddDefenseVictoryRewardMaxCount(b, fbsutils.Encode(t.DefenseVictoryRewardMaxCount, t.FlatBuffer.TableKey))
	ConstArenaExcelAddTopRankerCountLimit(b, fbsutils.Encode(t.TopRankerCountLimit, t.FlatBuffer.TableKey))
	ConstArenaExcelAddAutoRefreshIntervalMilliSeconds(b, fbsutils.Encode(t.AutoRefreshIntervalMilliSeconds, t.FlatBuffer.TableKey))
	ConstArenaExcelAddEchelonSettingIntervalMilliSeconds(b, fbsutils.Encode(t.EchelonSettingIntervalMilliSeconds, t.FlatBuffer.TableKey))
	ConstArenaExcelAddSkipAllowedTimeMilliSeconds(b, fbsutils.Encode(t.SkipAllowedTimeMilliSeconds, t.FlatBuffer.TableKey))
	ConstArenaExcelAddShowSeasonChangeInfoStartTime(b, showSeasonChangeInfoStartTimeOffset)
	ConstArenaExcelAddShowSeasonChangeInfoEndTime(b, showSeasonChangeInfoEndTimeOffset)
	ConstArenaExcelAddShowSeasonId(b, fbsutils.Encode(t.ShowSeasonID, t.FlatBuffer.TableKey))
	ConstArenaExcelAddArenaHistoryQueryLimitDays(b, fbsutils.Encode(t.ArenaHistoryQueryLimitDays, t.FlatBuffer.TableKey))
	return ConstArenaExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer.
func (t *ConstArenaExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers table.
func (t *ConstArenaExcelDto) UnmarshalMessage(e *ConstArenaExcel) error {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("ConstArena"))
	}
	t.AttackCoolTime = fbsutils.Decode(e.AttackCoolTime(), t.FlatBuffer.TableKey)
	t.BattleDuration = fbsutils.Decode(e.BattleDuration(), t.FlatBuffer.TableKey)
	t.DefenseCoolTime = fbsutils.Decode(e.DefenseCoolTime(), t.FlatBuffer.TableKey)
	t.TssStartCoolTime = fbsutils.Decode(e.TssStartCoolTime(), t.FlatBuffer.TableKey)
	t.EndAlarm = fbsutils.Decode(e.EndAlarm(), t.FlatBuffer.TableKey)
	t.TimeRewardMaxAmount = fbsutils.Decode(e.TimeRewardMaxAmount(), t.FlatBuffer.TableKey)
	t.EnterCostType = ParcelType(fbsutils.Decode(int32(e.EnterCostType()), t.FlatBuffer.TableKey))
	t.EnterCostID = fbsutils.Decode(e.EnterCostId(), t.FlatBuffer.TableKey)
	t.TicketCost = fbsutils.Decode(e.TicketCost(), t.FlatBuffer.TableKey)
	t.DailyRewardResetTime = fbsutils.Decode(string(e.DailyRewardResetTime()), t.FlatBuffer.TableKey)
	t.OpenScenarioID = fbsutils.Decode(string(e.OpenScenarioId()), t.FlatBuffer.TableKey)
	t.CharacterSlotHideRank = make([]int64, e.CharacterSlotHideRankLength())
	for i := 0; i < e.CharacterSlotHideRankLength(); i++ {
		t.CharacterSlotHideRank[i] = fbsutils.Decode(e.CharacterSlotHideRank(i), t.FlatBuffer.TableKey)
	}
	t.MapSlotHideRank = fbsutils.Decode(e.MapSlotHideRank(), t.FlatBuffer.TableKey)
	t.RelativeOpponentRankStart = make([]int64, e.RelativeOpponentRankStartLength())
	for i := 0; i < e.RelativeOpponentRankStartLength(); i++ {
		t.RelativeOpponentRankStart[i] = fbsutils.Decode(e.RelativeOpponentRankStart(i), t.FlatBuffer.TableKey)
	}
	t.RelativeOpponentRankEnd = make([]int64, e.RelativeOpponentRankEndLength())
	for i := 0; i < e.RelativeOpponentRankEndLength(); i++ {
		t.RelativeOpponentRankEnd[i] = fbsutils.Decode(e.RelativeOpponentRankEnd(i), t.FlatBuffer.TableKey)
	}
	t.ModifiedStatType = make([]StatType, e.ModifiedStatTypeLength())
	for i := 0; i < e.ModifiedStatTypeLength(); i++ {
		t.ModifiedStatType[i] = StatType(fbsutils.Decode(int32(e.ModifiedStatType(i)), t.FlatBuffer.TableKey))
	}
	t.StatMulFactor = make([]int64, e.StatMulFactorLength())
	for i := 0; i < e.StatMulFactorLength(); i++ {
		t.StatMulFactor[i] = fbsutils.Decode(e.StatMulFactor(i), t.FlatBuffer.TableKey)
	}
	t.StatSumFactor = make([]int64, e.StatSumFactorLength())
	for i := 0; i < e.StatSumFactorLength(); i++ {
		t.StatSumFactor[i] = fbsutils.Decode(e.StatSumFactor(i), t.FlatBuffer.TableKey)
	}
	t.NpcName = make([]string, e.NpcNameLength())
	for i := 0; i < e.NpcNameLength(); i++ {
		t.NpcName[i] = fbsutils.Decode(string(e.NpcName(i)), t.FlatBuffer.TableKey)
	}
	t.NpcMainCharacterCount = fbsutils.Decode(e.NpcMainCharacterCount(), t.FlatBuffer.TableKey)
	t.NpcSupportCharacterCount = fbsutils.Decode(e.NpcSupportCharacterCount(), t.FlatBuffer.TableKey)
	t.NpcCharacterSkillLevel = fbsutils.Decode(e.NpcCharacterSkillLevel(), t.FlatBuffer.TableKey)
	t.TimeSpanInDaysForBattleHistory = fbsutils.Decode(e.TimeSpanInDaysForBattleHistory(), t.FlatBuffer.TableKey)
	t.HiddenCharacterImagePath = fbsutils.Decode(string(e.HiddenCharacterImagePath()), t.FlatBuffer.TableKey)
	t.DefenseVictoryRewardMaxCount = fbsutils.Decode(e.DefenseVictoryRewardMaxCount(), t.FlatBuffer.TableKey)
	t.TopRankerCountLimit = fbsutils.Decode(e.TopRankerCountLimit(), t.FlatBuffer.TableKey)
	t.AutoRefreshIntervalMilliSeconds = fbsutils.Decode(e.AutoRefreshIntervalMilliSeconds(), t.FlatBuffer.TableKey)
	t.EchelonSettingIntervalMilliSeconds = fbsutils.Decode(e.EchelonSettingIntervalMilliSeconds(), t.FlatBuffer.TableKey)
	t.SkipAllowedTimeMilliSeconds = fbsutils.Decode(e.SkipAllowedTimeMilliSeconds(), t.FlatBuffer.TableKey)
	t.ShowSeasonChangeInfoStartTime = fbsutils.Decode(string(e.ShowSeasonChangeInfoStartTime()), t.FlatBuffer.TableKey)
	t.ShowSeasonChangeInfoEndTime = fbsutils.Decode(string(e.ShowSeasonChangeInfoEndTime()), t.FlatBuffer.TableKey)
	t.ShowSeasonID = fbsutils.Decode(e.ShowSeasonId(), t.FlatBuffer.TableKey)
	t.ArenaHistoryQueryLimitDays = fbsutils.Decode(e.ArenaHistoryQueryLimitDays(), t.FlatBuffer.TableKey)
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer.
func (t *ConstArenaExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsConstArenaExcel(data, 0)
	return t.UnmarshalMessage(root)
}

// FlatDataName returns the FlatBuffers table name.
func (ConstArenaExcelDto) FlatDataName() string {
	return "ConstArenaExcel"
}
