// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatdata

import "strconv"

type Difficulty int32

const (
	DifficultyNormal   Difficulty = 0
	DifficultyHard     Difficulty = 1
	DifficultyVeryHard Difficulty = 2
	DifficultyHardcore Difficulty = 3
	DifficultyExtreme  Difficulty = 4
	DifficultyInsane   Difficulty = 5
	DifficultyTorment  Difficulty = 6
	DifficultyLunatic  Difficulty = 7
)

var EnumNamesDifficulty = map[Difficulty]string{
	DifficultyNormal:   "Normal",
	DifficultyHard:     "Hard",
	DifficultyVeryHard: "VeryHard",
	DifficultyHardcore: "Hardcore",
	DifficultyExtreme:  "Extreme",
	DifficultyInsane:   "Insane",
	DifficultyTorment:  "Torment",
	DifficultyLunatic:  "Lunatic",
}

var EnumValuesDifficulty = map[string]Difficulty{
	"Normal":   DifficultyNormal,
	"Hard":     DifficultyHard,
	"VeryHard": DifficultyVeryHard,
	"Hardcore": DifficultyHardcore,
	"Extreme":  DifficultyExtreme,
	"Insane":   DifficultyInsane,
	"Torment":  DifficultyTorment,
	"Lunatic":  DifficultyLunatic,
}

func (v Difficulty) String() string {
	if s, ok := EnumNamesDifficulty[v]; ok {
		return s
	}
	return "Difficulty(" + strconv.FormatInt(int64(v), 10) + ")"
}
