// Code generated by fbsgen. DO NOT EDIT.
// Package flatdata contains generated code for FlatBuffers schema
package flatdata

import (
	"errors"
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// EventContentExcelTableDto represents a FlatBuffers table
type EventContentExcelTableDto struct {
	fbsutils.FlatBuffer
	DataList []EventContentExcelDto `json:"data_list"`
}

// MarshalModel marshals the struct into flatbuffers offset
func (t *EventContentExcelTableDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("EventContent"))
	}
	EventContentExcelTableStart(b)
	EventContentExcelTableStartDataListVector(b, len(t.DataList))
	for i := range len(t.DataList) {
		// The array should be reversed.
		b.PrependUOffsetT(t.DataList[len(t.DataList)-i-1].MarshalModel(b))
	}
	EventContentExcelTableAddDataList(b, b.EndVector(len(t.DataList)))
	return EventContentExcelTableEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer
func (t *EventContentExcelTableDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers buffer
func (t *EventContentExcelTableDto) UnmarshalMessage(e *EventContentExcelTable) error {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("EventContent"))
	}
	t.DataList = make([]EventContentExcelDto, e.DataListLength())
	for i := range e.DataListLength() {
		d := new(EventContentExcel)
		if !e.DataList(d, i) {
			return errors.New("failed to unmarshal data")
		}
		t.DataList[i].UnmarshalMessage(d)
	}
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer
func (t *EventContentExcelTableDto) Unmarshal(data []byte) error {
	root := GetRootAsEventContentExcelTable(data, 0)
	err := t.UnmarshalMessage(root)
	if err != nil {
		return err
	}
	return nil
}

// Name returns the name of the flatbuffer table name
func (EventContentExcelTableDto) FlatDataName() string {
	return "EventContentExcelTable"
}
