// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatdata

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type EventContentDiceRaceExcelTable struct {
	_tab flatbuffers.Table
}

func GetRootAsEventContentDiceRaceExcelTable(buf []byte, offset flatbuffers.UOffsetT) *EventContentDiceRaceExcelTable {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &EventContentDiceRaceExcelTable{}
	x.Init(buf, n+offset)
	return x
}

func FinishEventContentDiceRaceExcelTableBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsEventContentDiceRaceExcelTable(buf []byte, offset flatbuffers.UOffsetT) *EventContentDiceRaceExcelTable {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &EventContentDiceRaceExcelTable{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedEventContentDiceRaceExcelTableBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *EventContentDiceRaceExcelTable) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *EventContentDiceRaceExcelTable) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *EventContentDiceRaceExcelTable) DataList(obj *EventContentDiceRaceExcel, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *EventContentDiceRaceExcelTable) DataListLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func EventContentDiceRaceExcelTableStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func EventContentDiceRaceExcelTableAddDataList(builder *flatbuffers.Builder, dataList flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(dataList), 0)
}
func EventContentDiceRaceExcelTableStartDataListVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func EventContentDiceRaceExcelTableEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
