// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatdata

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LimitedStageRewardExcelTable struct {
	_tab flatbuffers.Table
}

func GetRootAsLimitedStageRewardExcelTable(buf []byte, offset flatbuffers.UOffsetT) *LimitedStageRewardExcelTable {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LimitedStageRewardExcelTable{}
	x.Init(buf, n+offset)
	return x
}

func FinishLimitedStageRewardExcelTableBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsLimitedStageRewardExcelTable(buf []byte, offset flatbuffers.UOffsetT) *LimitedStageRewardExcelTable {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LimitedStageRewardExcelTable{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedLimitedStageRewardExcelTableBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *LimitedStageRewardExcelTable) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LimitedStageRewardExcelTable) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LimitedStageRewardExcelTable) DataList(obj *LimitedStageRewardExcel, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *LimitedStageRewardExcelTable) DataListLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func LimitedStageRewardExcelTableStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func LimitedStageRewardExcelTableAddDataList(builder *flatbuffers.Builder, dataList flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(dataList), 0)
}
func LimitedStageRewardExcelTableStartDataListVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func LimitedStageRewardExcelTableEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
