// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatdata

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LimitedStageExcelTable struct {
	_tab flatbuffers.Table
}

func GetRootAsLimitedStageExcelTable(buf []byte, offset flatbuffers.UOffsetT) *LimitedStageExcelTable {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LimitedStageExcelTable{}
	x.Init(buf, n+offset)
	return x
}

func FinishLimitedStageExcelTableBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsLimitedStageExcelTable(buf []byte, offset flatbuffers.UOffsetT) *LimitedStageExcelTable {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LimitedStageExcelTable{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedLimitedStageExcelTableBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *LimitedStageExcelTable) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LimitedStageExcelTable) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LimitedStageExcelTable) DataList(obj *LimitedStageExcel, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *LimitedStageExcelTable) DataListLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func LimitedStageExcelTableStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func LimitedStageExcelTableAddDataList(builder *flatbuffers.Builder, dataList flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(dataList), 0)
}
func LimitedStageExcelTableStartDataListVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func LimitedStageExcelTableEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
