// Code generated by fbsgen. DO NOT EDIT.
// Package flatdata contains generated code for a FlatBuffers schema.
package flatdata

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// LocalizeKeyMappingExcelDto represents a FlatBuffers table.
type LocalizeKeyMappingExcelDto struct {
	fbsutils.FlatBuffer
	Key uint32 `json:"key"`
	Kr  string `json:"kr"`
	Jp  string `json:"jp"`
}

// MarshalModel marshals the struct into a FlatBuffers offset.
func (t *LocalizeKeyMappingExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("LocalizeKeyMapping"))
	}
	krOffset := b.CreateString(fbsutils.Encode(t.Kr, t.FlatBuffer.TableKey))
	jpOffset := b.CreateString(fbsutils.Encode(t.Jp, t.FlatBuffer.TableKey))
	LocalizeKeyMappingExcelStart(b)
	LocalizeKeyMappingExcelAddKey(b, fbsutils.Encode(t.Key, t.FlatBuffer.TableKey))
	LocalizeKeyMappingExcelAddKr(b, krOffset)
	LocalizeKeyMappingExcelAddJp(b, jpOffset)
	return LocalizeKeyMappingExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer.
func (t *LocalizeKeyMappingExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers table.
func (t *LocalizeKeyMappingExcelDto) UnmarshalMessage(e *LocalizeKeyMappingExcel) error {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("LocalizeKeyMapping"))
	}
	t.Key = fbsutils.Decode(e.Key(), t.FlatBuffer.TableKey)
	t.Kr = fbsutils.Decode(string(e.Kr()), t.FlatBuffer.TableKey)
	t.Jp = fbsutils.Decode(string(e.Jp()), t.FlatBuffer.TableKey)
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer.
func (t *LocalizeKeyMappingExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsLocalizeKeyMappingExcel(data, 0)
	return t.UnmarshalMessage(root)
}

// FlatDataName returns the FlatBuffers table name.
func (LocalizeKeyMappingExcelDto) FlatDataName() string {
	return "LocalizeKeyMappingExcel"
}
