// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatdata

import "strconv"

type MemoryLobbyCategory int32

const (
	MemoryLobbyCategoryNone            MemoryLobbyCategory = 0
	MemoryLobbyCategoryUILobbySpecial  MemoryLobbyCategory = 1
	MemoryLobbyCategoryUILobbySpecial2 MemoryLobbyCategory = 2
)

var EnumNamesMemoryLobbyCategory = map[MemoryLobbyCategory]string{
	MemoryLobbyCategoryNone:            "None",
	MemoryLobbyCategoryUILobbySpecial:  "UILobbySpecial",
	MemoryLobbyCategoryUILobbySpecial2: "UILobbySpecial2",
}

var EnumValuesMemoryLobbyCategory = map[string]MemoryLobbyCategory{
	"None":            MemoryLobbyCategoryNone,
	"UILobbySpecial":  MemoryLobbyCategoryUILobbySpecial,
	"UILobbySpecial2": MemoryLobbyCategoryUILobbySpecial2,
}

func (v MemoryLobbyCategory) String() string {
	if s, ok := EnumNamesMemoryLobbyCategory[v]; ok {
		return s
	}
	return "MemoryLobbyCategory(" + strconv.FormatInt(int64(v), 10) + ")"
}
