// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatdata

import "strconv"

type NotificationEventReddot int32

const (
	NotificationEventReddotStagePointReward        NotificationEventReddot = 0
	NotificationEventReddotMissionComplete         NotificationEventReddot = 1
	NotificationEventReddotMiniGameMissionComplete NotificationEventReddot = 2
	NotificationEventReddotWorldRaidReward         NotificationEventReddot = 3
	NotificationEventReddotConquestCalculateReward NotificationEventReddot = 4
	NotificationEventReddotDiceRaceLapReward       NotificationEventReddot = 5
)

var EnumNamesNotificationEventReddot = map[NotificationEventReddot]string{
	NotificationEventReddotStagePointReward:        "StagePointReward",
	NotificationEventReddotMissionComplete:         "MissionComplete",
	NotificationEventReddotMiniGameMissionComplete: "MiniGameMissionComplete",
	NotificationEventReddotWorldRaidReward:         "WorldRaidReward",
	NotificationEventReddotConquestCalculateReward: "ConquestCalculateReward",
	NotificationEventReddotDiceRaceLapReward:       "DiceRaceLapReward",
}

var EnumValuesNotificationEventReddot = map[string]NotificationEventReddot{
	"StagePointReward":        NotificationEventReddotStagePointReward,
	"MissionComplete":         NotificationEventReddotMissionComplete,
	"MiniGameMissionComplete": NotificationEventReddotMiniGameMissionComplete,
	"WorldRaidReward":         NotificationEventReddotWorldRaidReward,
	"ConquestCalculateReward": NotificationEventReddotConquestCalculateReward,
	"DiceRaceLapReward":       NotificationEventReddotDiceRaceLapReward,
}

func (v NotificationEventReddot) String() string {
	if s, ok := EnumNamesNotificationEventReddot[v]; ok {
		return s
	}
	return "NotificationEventReddot(" + strconv.FormatInt(int64(v), 10) + ")"
}
