// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatdata

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PropRootMotionFlat struct {
	_tab flatbuffers.Table
}

func GetRootAsPropRootMotionFlat(buf []byte, offset flatbuffers.UOffsetT) *PropRootMotionFlat {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PropRootMotionFlat{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsPropRootMotionFlat(buf []byte, offset flatbuffers.UOffsetT) *PropRootMotionFlat {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PropRootMotionFlat{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *PropRootMotionFlat) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PropRootMotionFlat) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PropRootMotionFlat) RootMotions(obj *PropMotion, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *PropRootMotionFlat) RootMotionsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func PropRootMotionFlatStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PropRootMotionFlatAddRootMotions(builder *flatbuffers.Builder, rootMotions flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(rootMotions), 0)
}
func PropRootMotionFlatStartRootMotionsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func PropRootMotionFlatEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
