// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatdata

import "strconv"

type PurchasePeriodType int32

const (
	PurchasePeriodTypeNone  PurchasePeriodType = 0
	PurchasePeriodTypeDay   PurchasePeriodType = 1
	PurchasePeriodTypeWeek  PurchasePeriodType = 2
	PurchasePeriodTypeMonth PurchasePeriodType = 3
)

var EnumNamesPurchasePeriodType = map[PurchasePeriodType]string{
	PurchasePeriodTypeNone:  "None",
	PurchasePeriodTypeDay:   "Day",
	PurchasePeriodTypeWeek:  "Week",
	PurchasePeriodTypeMonth: "Month",
}

var EnumValuesPurchasePeriodType = map[string]PurchasePeriodType{
	"None":  PurchasePeriodTypeNone,
	"Day":   PurchasePeriodTypeDay,
	"Week":  PurchasePeriodTypeWeek,
	"Month": PurchasePeriodTypeMonth,
}

func (v PurchasePeriodType) String() string {
	if s, ok := EnumNamesPurchasePeriodType[v]; ok {
		return s
	}
	return "PurchasePeriodType(" + strconv.FormatInt(int64(v), 10) + ")"
}
