// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatdata

import "strconv"

type TacticEnvironment int32

const (
	TacticEnvironmentNone   TacticEnvironment = 0
	TacticEnvironmentWarFog TacticEnvironment = 1
)

var EnumNamesTacticEnvironment = map[TacticEnvironment]string{
	TacticEnvironmentNone:   "None",
	TacticEnvironmentWarFog: "WarFog",
}

var EnumValuesTacticEnvironment = map[string]TacticEnvironment{
	"None":   TacticEnvironmentNone,
	"WarFog": TacticEnvironmentWarFog,
}

func (v TacticEnvironment) String() string {
	if s, ok := EnumNamesTacticEnvironment[v]; ok {
		return s
	}
	return "TacticEnvironment(" + strconv.FormatInt(int64(v), 10) + ")"
}
