// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatdata

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TacticEntityEffectFilterExcelTable struct {
	_tab flatbuffers.Table
}

func GetRootAsTacticEntityEffectFilterExcelTable(buf []byte, offset flatbuffers.UOffsetT) *TacticEntityEffectFilterExcelTable {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TacticEntityEffectFilterExcelTable{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsTacticEntityEffectFilterExcelTable(buf []byte, offset flatbuffers.UOffsetT) *TacticEntityEffectFilterExcelTable {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TacticEntityEffectFilterExcelTable{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *TacticEntityEffectFilterExcelTable) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TacticEntityEffectFilterExcelTable) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TacticEntityEffectFilterExcelTable) DataList(obj *TacticEntityEffectFilterExcel, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *TacticEntityEffectFilterExcelTable) DataListLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func TacticEntityEffectFilterExcelTableStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TacticEntityEffectFilterExcelTableAddDataList(builder *flatbuffers.Builder, dataList flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(dataList), 0)
}
func TacticEntityEffectFilterExcelTableStartDataListVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TacticEntityEffectFilterExcelTableEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
