// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatdata

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TacticSimulatorSettingExcelTable struct {
	_tab flatbuffers.Table
}

func GetRootAsTacticSimulatorSettingExcelTable(buf []byte, offset flatbuffers.UOffsetT) *TacticSimulatorSettingExcelTable {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TacticSimulatorSettingExcelTable{}
	x.Init(buf, n+offset)
	return x
}

func FinishTacticSimulatorSettingExcelTableBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTacticSimulatorSettingExcelTable(buf []byte, offset flatbuffers.UOffsetT) *TacticSimulatorSettingExcelTable {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TacticSimulatorSettingExcelTable{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTacticSimulatorSettingExcelTableBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TacticSimulatorSettingExcelTable) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TacticSimulatorSettingExcelTable) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TacticSimulatorSettingExcelTable) DataList(obj *TacticSimulatorSettingExcel, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *TacticSimulatorSettingExcelTable) DataListLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func TacticSimulatorSettingExcelTableStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TacticSimulatorSettingExcelTableAddDataList(builder *flatbuffers.Builder, dataList flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(dataList), 0)
}
func TacticSimulatorSettingExcelTableStartDataListVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TacticSimulatorSettingExcelTableEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
