// Code generated by fbsgen. DO NOT EDIT.
// Package flatdata contains generated code for FlatBuffers schema
package flatdata

import (
	"errors"
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// TranscendenceRecipeExcelTableDto represents a FlatBuffers table
type TranscendenceRecipeExcelTableDto struct {
	fbsutils.FlatBuffer
	DataList []TranscendenceRecipeExcelDto `json:"data_list"`
}

// MarshalModel marshals the struct into flatbuffers offset
func (t *TranscendenceRecipeExcelTableDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("TranscendenceRecipe"))
	}
	TranscendenceRecipeExcelTableStart(b)
	TranscendenceRecipeExcelTableStartDataListVector(b, len(t.DataList))
	for i := range len(t.DataList) {
		// The array should be reversed.
		b.PrependUOffsetT(t.DataList[len(t.DataList)-i-1].MarshalModel(b))
	}
	TranscendenceRecipeExcelTableAddDataList(b, b.EndVector(len(t.DataList)))
	return TranscendenceRecipeExcelTableEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer
func (t *TranscendenceRecipeExcelTableDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers buffer
func (t *TranscendenceRecipeExcelTableDto) UnmarshalMessage(e *TranscendenceRecipeExcelTable) error {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("TranscendenceRecipe"))
	}
	t.DataList = make([]TranscendenceRecipeExcelDto, e.DataListLength())
	for i := range e.DataListLength() {
		d := new(TranscendenceRecipeExcel)
		if !e.DataList(d, i) {
			return errors.New("failed to unmarshal data")
		}
		t.DataList[i].UnmarshalMessage(d)
	}
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer
func (t *TranscendenceRecipeExcelTableDto) Unmarshal(data []byte) error {
	root := GetRootAsTranscendenceRecipeExcelTable(data, 0)
	err := t.UnmarshalMessage(root)
	if err != nil {
		return err
	}
	return nil
}

// Name returns the name of the flatbuffer table name
func (TranscendenceRecipeExcelTableDto) FlatDataName() string {
	return "TranscendenceRecipeExcelTable"
}
