// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatdata

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type WorldRaidFavorBuffExcelTable struct {
	_tab flatbuffers.Table
}

func GetRootAsWorldRaidFavorBuffExcelTable(buf []byte, offset flatbuffers.UOffsetT) *WorldRaidFavorBuffExcelTable {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &WorldRaidFavorBuffExcelTable{}
	x.Init(buf, n+offset)
	return x
}

func FinishWorldRaidFavorBuffExcelTableBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsWorldRaidFavorBuffExcelTable(buf []byte, offset flatbuffers.UOffsetT) *WorldRaidFavorBuffExcelTable {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &WorldRaidFavorBuffExcelTable{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedWorldRaidFavorBuffExcelTableBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *WorldRaidFavorBuffExcelTable) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *WorldRaidFavorBuffExcelTable) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *WorldRaidFavorBuffExcelTable) DataList(obj *WorldRaidFavorBuffExcel, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *WorldRaidFavorBuffExcelTable) DataListLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func WorldRaidFavorBuffExcelTableStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func WorldRaidFavorBuffExcelTableAddDataList(builder *flatbuffers.Builder, dataList flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(dataList), 0)
}
func WorldRaidFavorBuffExcelTableStartDataListVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func WorldRaidFavorBuffExcelTableEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
