# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Excel

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FavorLevelRewardExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FavorLevelRewardExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFavorLevelRewardExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FavorLevelRewardExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FavorLevelRewardExcel
    def CharacterId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # FavorLevelRewardExcel
    def FavorLevel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # FavorLevelRewardExcel
    def StatType(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # FavorLevelRewardExcel
    def StatTypeAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # FavorLevelRewardExcel
    def StatTypeLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FavorLevelRewardExcel
    def StatTypeIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # FavorLevelRewardExcel
    def StatValue(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # FavorLevelRewardExcel
    def StatValueAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int64Flags, o)
        return 0

    # FavorLevelRewardExcel
    def StatValueLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FavorLevelRewardExcel
    def StatValueIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def FavorLevelRewardExcelStart(builder):
    builder.StartObject(4)

def Start(builder):
    FavorLevelRewardExcelStart(builder)

def FavorLevelRewardExcelAddCharacterId(builder, characterId):
    builder.PrependInt64Slot(0, characterId, 0)

def AddCharacterId(builder, characterId):
    FavorLevelRewardExcelAddCharacterId(builder, characterId)

def FavorLevelRewardExcelAddFavorLevel(builder, favorLevel):
    builder.PrependInt64Slot(1, favorLevel, 0)

def AddFavorLevel(builder, favorLevel):
    FavorLevelRewardExcelAddFavorLevel(builder, favorLevel)

def FavorLevelRewardExcelAddStatType(builder, statType):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(statType), 0)

def AddStatType(builder, statType):
    FavorLevelRewardExcelAddStatType(builder, statType)

def FavorLevelRewardExcelStartStatTypeVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartStatTypeVector(builder, numElems):
    return FavorLevelRewardExcelStartStatTypeVector(builder, numElems)

def FavorLevelRewardExcelAddStatValue(builder, statValue):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(statValue), 0)

def AddStatValue(builder, statValue):
    FavorLevelRewardExcelAddStatValue(builder, statValue)

def FavorLevelRewardExcelStartStatValueVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartStatValueVector(builder, numElems):
    return FavorLevelRewardExcelStartStatValueVector(builder, numElems)

def FavorLevelRewardExcelEnd(builder):
    return builder.EndObject()

def End(builder):
    return FavorLevelRewardExcelEnd(builder)

try:
    from typing import List
except:
    pass

class FavorLevelRewardExcelT(object):

    # FavorLevelRewardExcelT
    def __init__(
        self,
        characterId = 0,
        favorLevel = 0,
        statType = None,
        statValue = None,
    ):
        self.characterId = characterId  # type: int
        self.favorLevel = favorLevel  # type: int
        self.statType = statType  # type: Optional[List[int]]
        self.statValue = statValue  # type: Optional[List[int]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        favorLevelRewardExcel = FavorLevelRewardExcel()
        favorLevelRewardExcel.Init(buf, pos)
        return cls.InitFromObj(favorLevelRewardExcel)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, favorLevelRewardExcel):
        x = FavorLevelRewardExcelT()
        x._UnPack(favorLevelRewardExcel)
        return x

    # FavorLevelRewardExcelT
    def _UnPack(self, favorLevelRewardExcel):
        if favorLevelRewardExcel is None:
            return
        self.characterId = favorLevelRewardExcel.CharacterId()
        self.favorLevel = favorLevelRewardExcel.FavorLevel()
        if not favorLevelRewardExcel.StatTypeIsNone():
            if np is None:
                self.statType = []
                for i in range(favorLevelRewardExcel.StatTypeLength()):
                    self.statType.append(favorLevelRewardExcel.StatType(i))
            else:
                self.statType = favorLevelRewardExcel.StatTypeAsNumpy()
        if not favorLevelRewardExcel.StatValueIsNone():
            if np is None:
                self.statValue = []
                for i in range(favorLevelRewardExcel.StatValueLength()):
                    self.statValue.append(favorLevelRewardExcel.StatValue(i))
            else:
                self.statValue = favorLevelRewardExcel.StatValueAsNumpy()

    # FavorLevelRewardExcelT
    def Pack(self, builder):
        if self.statType is not None:
            if np is not None and type(self.statType) is np.ndarray:
                statType = builder.CreateNumpyVector(self.statType)
            else:
                FavorLevelRewardExcelStartStatTypeVector(builder, len(self.statType))
                for i in reversed(range(len(self.statType))):
                    builder.PrependInt32(self.statType[i])
                statType = builder.EndVector()
        if self.statValue is not None:
            if np is not None and type(self.statValue) is np.ndarray:
                statValue = builder.CreateNumpyVector(self.statValue)
            else:
                FavorLevelRewardExcelStartStatValueVector(builder, len(self.statValue))
                for i in reversed(range(len(self.statValue))):
                    builder.PrependInt64(self.statValue[i])
                statValue = builder.EndVector()
        FavorLevelRewardExcelStart(builder)
        FavorLevelRewardExcelAddCharacterId(builder, self.characterId)
        FavorLevelRewardExcelAddFavorLevel(builder, self.favorLevel)
        if self.statType is not None:
            FavorLevelRewardExcelAddStatType(builder, statType)
        if self.statValue is not None:
            FavorLevelRewardExcelAddStatValue(builder, statValue)
        favorLevelRewardExcel = FavorLevelRewardExcelEnd(builder)
        return favorLevelRewardExcel
