# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Excel

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GachaSelectPickupGroupExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GachaSelectPickupGroupExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGachaSelectPickupGroupExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GachaSelectPickupGroupExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GachaSelectPickupGroupExcel
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # GachaSelectPickupGroupExcel
    def GachaGroupId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # GachaSelectPickupGroupExcel
    def CharacterId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def GachaSelectPickupGroupExcelStart(builder):
    builder.StartObject(3)

def Start(builder):
    GachaSelectPickupGroupExcelStart(builder)

def GachaSelectPickupGroupExcelAddId(builder, id):
    builder.PrependInt64Slot(0, id, 0)

def AddId(builder, id):
    GachaSelectPickupGroupExcelAddId(builder, id)

def GachaSelectPickupGroupExcelAddGachaGroupId(builder, gachaGroupId):
    builder.PrependInt64Slot(1, gachaGroupId, 0)

def AddGachaGroupId(builder, gachaGroupId):
    GachaSelectPickupGroupExcelAddGachaGroupId(builder, gachaGroupId)

def GachaSelectPickupGroupExcelAddCharacterId(builder, characterId):
    builder.PrependInt64Slot(2, characterId, 0)

def AddCharacterId(builder, characterId):
    GachaSelectPickupGroupExcelAddCharacterId(builder, characterId)

def GachaSelectPickupGroupExcelEnd(builder):
    return builder.EndObject()

def End(builder):
    return GachaSelectPickupGroupExcelEnd(builder)
