# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Excel

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ProductDailyRecordInfoExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ProductDailyRecordInfoExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsProductDailyRecordInfoExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ProductDailyRecordInfoExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ProductDailyRecordInfoExcel
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ProductDailyRecordInfoExcel
    def DaySize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ProductDailyRecordInfoExcel
    def ExpirationDate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ProductDailyRecordInfoExcelStart(builder):
    builder.StartObject(3)

def Start(builder):
    ProductDailyRecordInfoExcelStart(builder)

def ProductDailyRecordInfoExcelAddId(builder, id):
    builder.PrependInt64Slot(0, id, 0)

def AddId(builder, id):
    ProductDailyRecordInfoExcelAddId(builder, id)

def ProductDailyRecordInfoExcelAddDaySize(builder, daySize):
    builder.PrependInt32Slot(1, daySize, 0)

def AddDaySize(builder, daySize):
    ProductDailyRecordInfoExcelAddDaySize(builder, daySize)

def ProductDailyRecordInfoExcelAddExpirationDate(builder, expirationDate):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(expirationDate), 0)

def AddExpirationDate(builder, expirationDate):
    ProductDailyRecordInfoExcelAddExpirationDate(builder, expirationDate)

def ProductDailyRecordInfoExcelEnd(builder):
    return builder.EndObject()

def End(builder):
    return ProductDailyRecordInfoExcelEnd(builder)


class ProductDailyRecordInfoExcelT(object):

    # ProductDailyRecordInfoExcelT
    def __init__(
        self,
        id = 0,
        daySize = 0,
        expirationDate = None,
    ):
        self.id = id  # type: int
        self.daySize = daySize  # type: int
        self.expirationDate = expirationDate  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        productDailyRecordInfoExcel = ProductDailyRecordInfoExcel()
        productDailyRecordInfoExcel.Init(buf, pos)
        return cls.InitFromObj(productDailyRecordInfoExcel)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, productDailyRecordInfoExcel):
        x = ProductDailyRecordInfoExcelT()
        x._UnPack(productDailyRecordInfoExcel)
        return x

    # ProductDailyRecordInfoExcelT
    def _UnPack(self, productDailyRecordInfoExcel):
        if productDailyRecordInfoExcel is None:
            return
        self.id = productDailyRecordInfoExcel.Id()
        self.daySize = productDailyRecordInfoExcel.DaySize()
        self.expirationDate = productDailyRecordInfoExcel.ExpirationDate()

    # ProductDailyRecordInfoExcelT
    def Pack(self, builder):
        if self.expirationDate is not None:
            expirationDate = builder.CreateString(self.expirationDate)
        ProductDailyRecordInfoExcelStart(builder)
        ProductDailyRecordInfoExcelAddId(builder, self.id)
        ProductDailyRecordInfoExcelAddDaySize(builder, self.daySize)
        if self.expirationDate is not None:
            ProductDailyRecordInfoExcelAddExpirationDate(builder, expirationDate)
        productDailyRecordInfoExcel = ProductDailyRecordInfoExcelEnd(builder)
        return productDailyRecordInfoExcel
