# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Excel

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ScenarioScriptExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ScenarioScriptExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsScenarioScriptExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ScenarioScriptExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ScenarioScriptExcel
    def VoiceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ScenarioScriptExcel
    def TextJp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ScenarioScriptExcel
    def ScriptKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ScenarioScriptExcel
    def PopupFileName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ScenarioScriptExcel
    def BgEffect(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ScenarioScriptExcel
    def BgName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ScenarioScriptExcel
    def Transition(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ScenarioScriptExcel
    def Sound(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ScenarioScriptExcel
    def BgmId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ScenarioScriptExcel
    def SelectionGroup(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ScenarioScriptExcel
    def GroupId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def ScenarioScriptExcelStart(builder): builder.StartObject(11)
def Start(builder):
    return ScenarioScriptExcelStart(builder)
def ScenarioScriptExcelAddVoiceId(builder, voiceId): builder.PrependUint32Slot(0, voiceId, 0)
def AddVoiceId(builder, voiceId):
    return ScenarioScriptExcelAddVoiceId(builder, voiceId)
def ScenarioScriptExcelAddTextJp(builder, textJp): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(textJp), 0)
def AddTextJp(builder, textJp):
    return ScenarioScriptExcelAddTextJp(builder, textJp)
def ScenarioScriptExcelAddScriptKr(builder, scriptKr): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(scriptKr), 0)
def AddScriptKr(builder, scriptKr):
    return ScenarioScriptExcelAddScriptKr(builder, scriptKr)
def ScenarioScriptExcelAddPopupFileName(builder, popupFileName): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(popupFileName), 0)
def AddPopupFileName(builder, popupFileName):
    return ScenarioScriptExcelAddPopupFileName(builder, popupFileName)
def ScenarioScriptExcelAddBgEffect(builder, bgEffect): builder.PrependUint32Slot(4, bgEffect, 0)
def AddBgEffect(builder, bgEffect):
    return ScenarioScriptExcelAddBgEffect(builder, bgEffect)
def ScenarioScriptExcelAddBgName(builder, bgName): builder.PrependUint32Slot(5, bgName, 0)
def AddBgName(builder, bgName):
    return ScenarioScriptExcelAddBgName(builder, bgName)
def ScenarioScriptExcelAddTransition(builder, transition): builder.PrependUint32Slot(6, transition, 0)
def AddTransition(builder, transition):
    return ScenarioScriptExcelAddTransition(builder, transition)
def ScenarioScriptExcelAddSound(builder, sound): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(sound), 0)
def AddSound(builder, sound):
    return ScenarioScriptExcelAddSound(builder, sound)
def ScenarioScriptExcelAddBgmId(builder, bgmId): builder.PrependInt64Slot(8, bgmId, 0)
def AddBgmId(builder, bgmId):
    return ScenarioScriptExcelAddBgmId(builder, bgmId)
def ScenarioScriptExcelAddSelectionGroup(builder, selectionGroup): builder.PrependInt64Slot(9, selectionGroup, 0)
def AddSelectionGroup(builder, selectionGroup):
    return ScenarioScriptExcelAddSelectionGroup(builder, selectionGroup)
def ScenarioScriptExcelAddGroupId(builder, groupId): builder.PrependInt64Slot(10, groupId, 0)
def AddGroupId(builder, groupId):
    return ScenarioScriptExcelAddGroupId(builder, groupId)
def ScenarioScriptExcelEnd(builder): return builder.EndObject()
def End(builder):
    return ScenarioScriptExcelEnd(builder)