# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Excel

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ShopRecruitMileageExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ShopRecruitMileageExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsShopRecruitMileageExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ShopRecruitMileageExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ShopRecruitMileageExcel
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ShopRecruitMileageExcel
    def MileageGroupId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ShopRecruitMileageExcel
    def MileageRewardGroupId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ShopRecruitMileageExcel
    def IsLoop(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ShopRecruitMileageExcel
    def RequiredRecruitAmount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ShopRecruitMileageExcel
    def RewardParcelType(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # ShopRecruitMileageExcel
    def RewardParcelTypeAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # ShopRecruitMileageExcel
    def RewardParcelTypeLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ShopRecruitMileageExcel
    def RewardParcelTypeIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # ShopRecruitMileageExcel
    def RewardParcelId(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # ShopRecruitMileageExcel
    def RewardParcelIdAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int64Flags, o)
        return 0

    # ShopRecruitMileageExcel
    def RewardParcelIdLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ShopRecruitMileageExcel
    def RewardParcelIdIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # ShopRecruitMileageExcel
    def RewardParcelAmount(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # ShopRecruitMileageExcel
    def RewardParcelAmountAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int64Flags, o)
        return 0

    # ShopRecruitMileageExcel
    def RewardParcelAmountLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ShopRecruitMileageExcel
    def RewardParcelAmountIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

def ShopRecruitMileageExcelStart(builder):
    builder.StartObject(8)

def Start(builder):
    ShopRecruitMileageExcelStart(builder)

def ShopRecruitMileageExcelAddId(builder, id):
    builder.PrependInt64Slot(0, id, 0)

def AddId(builder, id):
    ShopRecruitMileageExcelAddId(builder, id)

def ShopRecruitMileageExcelAddMileageGroupId(builder, mileageGroupId):
    builder.PrependInt64Slot(1, mileageGroupId, 0)

def AddMileageGroupId(builder, mileageGroupId):
    ShopRecruitMileageExcelAddMileageGroupId(builder, mileageGroupId)

def ShopRecruitMileageExcelAddMileageRewardGroupId(builder, mileageRewardGroupId):
    builder.PrependInt64Slot(2, mileageRewardGroupId, 0)

def AddMileageRewardGroupId(builder, mileageRewardGroupId):
    ShopRecruitMileageExcelAddMileageRewardGroupId(builder, mileageRewardGroupId)

def ShopRecruitMileageExcelAddIsLoop(builder, isLoop):
    builder.PrependBoolSlot(3, isLoop, 0)

def AddIsLoop(builder, isLoop):
    ShopRecruitMileageExcelAddIsLoop(builder, isLoop)

def ShopRecruitMileageExcelAddRequiredRecruitAmount(builder, requiredRecruitAmount):
    builder.PrependInt64Slot(4, requiredRecruitAmount, 0)

def AddRequiredRecruitAmount(builder, requiredRecruitAmount):
    ShopRecruitMileageExcelAddRequiredRecruitAmount(builder, requiredRecruitAmount)

def ShopRecruitMileageExcelAddRewardParcelType(builder, rewardParcelType):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(rewardParcelType), 0)

def AddRewardParcelType(builder, rewardParcelType):
    ShopRecruitMileageExcelAddRewardParcelType(builder, rewardParcelType)

def ShopRecruitMileageExcelStartRewardParcelTypeVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartRewardParcelTypeVector(builder, numElems):
    return ShopRecruitMileageExcelStartRewardParcelTypeVector(builder, numElems)

def ShopRecruitMileageExcelAddRewardParcelId(builder, rewardParcelId):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(rewardParcelId), 0)

def AddRewardParcelId(builder, rewardParcelId):
    ShopRecruitMileageExcelAddRewardParcelId(builder, rewardParcelId)

def ShopRecruitMileageExcelStartRewardParcelIdVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartRewardParcelIdVector(builder, numElems):
    return ShopRecruitMileageExcelStartRewardParcelIdVector(builder, numElems)

def ShopRecruitMileageExcelAddRewardParcelAmount(builder, rewardParcelAmount):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(rewardParcelAmount), 0)

def AddRewardParcelAmount(builder, rewardParcelAmount):
    ShopRecruitMileageExcelAddRewardParcelAmount(builder, rewardParcelAmount)

def ShopRecruitMileageExcelStartRewardParcelAmountVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartRewardParcelAmountVector(builder, numElems):
    return ShopRecruitMileageExcelStartRewardParcelAmountVector(builder, numElems)

def ShopRecruitMileageExcelEnd(builder):
    return builder.EndObject()

def End(builder):
    return ShopRecruitMileageExcelEnd(builder)

try:
    from typing import List
except:
    pass

class ShopRecruitMileageExcelT(object):

    # ShopRecruitMileageExcelT
    def __init__(
        self,
        id = 0,
        mileageGroupId = 0,
        mileageRewardGroupId = 0,
        isLoop = False,
        requiredRecruitAmount = 0,
        rewardParcelType = None,
        rewardParcelId = None,
        rewardParcelAmount = None,
    ):
        self.id = id  # type: int
        self.mileageGroupId = mileageGroupId  # type: int
        self.mileageRewardGroupId = mileageRewardGroupId  # type: int
        self.isLoop = isLoop  # type: bool
        self.requiredRecruitAmount = requiredRecruitAmount  # type: int
        self.rewardParcelType = rewardParcelType  # type: Optional[List[int]]
        self.rewardParcelId = rewardParcelId  # type: Optional[List[int]]
        self.rewardParcelAmount = rewardParcelAmount  # type: Optional[List[int]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        shopRecruitMileageExcel = ShopRecruitMileageExcel()
        shopRecruitMileageExcel.Init(buf, pos)
        return cls.InitFromObj(shopRecruitMileageExcel)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, shopRecruitMileageExcel):
        x = ShopRecruitMileageExcelT()
        x._UnPack(shopRecruitMileageExcel)
        return x

    # ShopRecruitMileageExcelT
    def _UnPack(self, shopRecruitMileageExcel):
        if shopRecruitMileageExcel is None:
            return
        self.id = shopRecruitMileageExcel.Id()
        self.mileageGroupId = shopRecruitMileageExcel.MileageGroupId()
        self.mileageRewardGroupId = shopRecruitMileageExcel.MileageRewardGroupId()
        self.isLoop = shopRecruitMileageExcel.IsLoop()
        self.requiredRecruitAmount = shopRecruitMileageExcel.RequiredRecruitAmount()
        if not shopRecruitMileageExcel.RewardParcelTypeIsNone():
            if np is None:
                self.rewardParcelType = []
                for i in range(shopRecruitMileageExcel.RewardParcelTypeLength()):
                    self.rewardParcelType.append(shopRecruitMileageExcel.RewardParcelType(i))
            else:
                self.rewardParcelType = shopRecruitMileageExcel.RewardParcelTypeAsNumpy()
        if not shopRecruitMileageExcel.RewardParcelIdIsNone():
            if np is None:
                self.rewardParcelId = []
                for i in range(shopRecruitMileageExcel.RewardParcelIdLength()):
                    self.rewardParcelId.append(shopRecruitMileageExcel.RewardParcelId(i))
            else:
                self.rewardParcelId = shopRecruitMileageExcel.RewardParcelIdAsNumpy()
        if not shopRecruitMileageExcel.RewardParcelAmountIsNone():
            if np is None:
                self.rewardParcelAmount = []
                for i in range(shopRecruitMileageExcel.RewardParcelAmountLength()):
                    self.rewardParcelAmount.append(shopRecruitMileageExcel.RewardParcelAmount(i))
            else:
                self.rewardParcelAmount = shopRecruitMileageExcel.RewardParcelAmountAsNumpy()

    # ShopRecruitMileageExcelT
    def Pack(self, builder):
        if self.rewardParcelType is not None:
            if np is not None and type(self.rewardParcelType) is np.ndarray:
                rewardParcelType = builder.CreateNumpyVector(self.rewardParcelType)
            else:
                ShopRecruitMileageExcelStartRewardParcelTypeVector(builder, len(self.rewardParcelType))
                for i in reversed(range(len(self.rewardParcelType))):
                    builder.PrependInt32(self.rewardParcelType[i])
                rewardParcelType = builder.EndVector()
        if self.rewardParcelId is not None:
            if np is not None and type(self.rewardParcelId) is np.ndarray:
                rewardParcelId = builder.CreateNumpyVector(self.rewardParcelId)
            else:
                ShopRecruitMileageExcelStartRewardParcelIdVector(builder, len(self.rewardParcelId))
                for i in reversed(range(len(self.rewardParcelId))):
                    builder.PrependInt64(self.rewardParcelId[i])
                rewardParcelId = builder.EndVector()
        if self.rewardParcelAmount is not None:
            if np is not None and type(self.rewardParcelAmount) is np.ndarray:
                rewardParcelAmount = builder.CreateNumpyVector(self.rewardParcelAmount)
            else:
                ShopRecruitMileageExcelStartRewardParcelAmountVector(builder, len(self.rewardParcelAmount))
                for i in reversed(range(len(self.rewardParcelAmount))):
                    builder.PrependInt64(self.rewardParcelAmount[i])
                rewardParcelAmount = builder.EndVector()
        ShopRecruitMileageExcelStart(builder)
        ShopRecruitMileageExcelAddId(builder, self.id)
        ShopRecruitMileageExcelAddMileageGroupId(builder, self.mileageGroupId)
        ShopRecruitMileageExcelAddMileageRewardGroupId(builder, self.mileageRewardGroupId)
        ShopRecruitMileageExcelAddIsLoop(builder, self.isLoop)
        ShopRecruitMileageExcelAddRequiredRecruitAmount(builder, self.requiredRecruitAmount)
        if self.rewardParcelType is not None:
            ShopRecruitMileageExcelAddRewardParcelType(builder, rewardParcelType)
        if self.rewardParcelId is not None:
            ShopRecruitMileageExcelAddRewardParcelId(builder, rewardParcelId)
        if self.rewardParcelAmount is not None:
            ShopRecruitMileageExcelAddRewardParcelAmount(builder, rewardParcelAmount)
        shopRecruitMileageExcel = ShopRecruitMileageExcelEnd(builder)
        return shopRecruitMileageExcel
