# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Excel

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ShopCashExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ShopCashExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsShopCashExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ShopCashExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ShopCashExcel
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ShopCashExcel
    def CashProductId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ShopCashExcel
    def PackageType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ShopCashExcel
    def LocalizeEtcId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ShopCashExcel
    def IconPath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ShopCashExcel
    def DisplayOrder(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ShopCashExcel
    def RenewalDisplayOrder(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ShopCashExcel
    def CategoryType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ShopCashExcel
    def DisplayTag(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ShopCashExcel
    def SalePeriodFrom(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ShopCashExcel
    def SalePeriodTo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ShopCashExcel
    def PeriodTag(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ShopCashExcel
    def AccountLevelLimit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ShopCashExcel
    def AccountLevelHide(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ShopCashExcel
    def ClearMissionLimit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ShopCashExcel
    def ClearMissionHide(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ShopCashExcel
    def PurchaseReportEventName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ShopCashExcelStart(builder):
    builder.StartObject(17)

def Start(builder):
    ShopCashExcelStart(builder)

def ShopCashExcelAddId(builder, id):
    builder.PrependInt64Slot(0, id, 0)

def AddId(builder, id):
    ShopCashExcelAddId(builder, id)

def ShopCashExcelAddCashProductId(builder, cashProductId):
    builder.PrependInt64Slot(1, cashProductId, 0)

def AddCashProductId(builder, cashProductId):
    ShopCashExcelAddCashProductId(builder, cashProductId)

def ShopCashExcelAddPackageType(builder, packageType):
    builder.PrependInt32Slot(2, packageType, 0)

def AddPackageType(builder, packageType):
    ShopCashExcelAddPackageType(builder, packageType)

def ShopCashExcelAddLocalizeEtcId(builder, localizeEtcId):
    builder.PrependUint32Slot(3, localizeEtcId, 0)

def AddLocalizeEtcId(builder, localizeEtcId):
    ShopCashExcelAddLocalizeEtcId(builder, localizeEtcId)

def ShopCashExcelAddIconPath(builder, iconPath):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(iconPath), 0)

def AddIconPath(builder, iconPath):
    ShopCashExcelAddIconPath(builder, iconPath)

def ShopCashExcelAddDisplayOrder(builder, displayOrder):
    builder.PrependInt64Slot(5, displayOrder, 0)

def AddDisplayOrder(builder, displayOrder):
    ShopCashExcelAddDisplayOrder(builder, displayOrder)

def ShopCashExcelAddRenewalDisplayOrder(builder, renewalDisplayOrder):
    builder.PrependInt64Slot(6, renewalDisplayOrder, 0)

def AddRenewalDisplayOrder(builder, renewalDisplayOrder):
    ShopCashExcelAddRenewalDisplayOrder(builder, renewalDisplayOrder)

def ShopCashExcelAddCategoryType(builder, categoryType):
    builder.PrependInt32Slot(7, categoryType, 0)

def AddCategoryType(builder, categoryType):
    ShopCashExcelAddCategoryType(builder, categoryType)

def ShopCashExcelAddDisplayTag(builder, displayTag):
    builder.PrependInt32Slot(8, displayTag, 0)

def AddDisplayTag(builder, displayTag):
    ShopCashExcelAddDisplayTag(builder, displayTag)

def ShopCashExcelAddSalePeriodFrom(builder, salePeriodFrom):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(salePeriodFrom), 0)

def AddSalePeriodFrom(builder, salePeriodFrom):
    ShopCashExcelAddSalePeriodFrom(builder, salePeriodFrom)

def ShopCashExcelAddSalePeriodTo(builder, salePeriodTo):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(salePeriodTo), 0)

def AddSalePeriodTo(builder, salePeriodTo):
    ShopCashExcelAddSalePeriodTo(builder, salePeriodTo)

def ShopCashExcelAddPeriodTag(builder, periodTag):
    builder.PrependBoolSlot(11, periodTag, 0)

def AddPeriodTag(builder, periodTag):
    ShopCashExcelAddPeriodTag(builder, periodTag)

def ShopCashExcelAddAccountLevelLimit(builder, accountLevelLimit):
    builder.PrependInt64Slot(12, accountLevelLimit, 0)

def AddAccountLevelLimit(builder, accountLevelLimit):
    ShopCashExcelAddAccountLevelLimit(builder, accountLevelLimit)

def ShopCashExcelAddAccountLevelHide(builder, accountLevelHide):
    builder.PrependBoolSlot(13, accountLevelHide, 0)

def AddAccountLevelHide(builder, accountLevelHide):
    ShopCashExcelAddAccountLevelHide(builder, accountLevelHide)

def ShopCashExcelAddClearMissionLimit(builder, clearMissionLimit):
    builder.PrependInt64Slot(14, clearMissionLimit, 0)

def AddClearMissionLimit(builder, clearMissionLimit):
    ShopCashExcelAddClearMissionLimit(builder, clearMissionLimit)

def ShopCashExcelAddClearMissionHide(builder, clearMissionHide):
    builder.PrependBoolSlot(15, clearMissionHide, 0)

def AddClearMissionHide(builder, clearMissionHide):
    ShopCashExcelAddClearMissionHide(builder, clearMissionHide)

def ShopCashExcelAddPurchaseReportEventName(builder, purchaseReportEventName):
    builder.PrependUOffsetTRelativeSlot(16, flatbuffers.number_types.UOffsetTFlags.py_type(purchaseReportEventName), 0)

def AddPurchaseReportEventName(builder, purchaseReportEventName):
    ShopCashExcelAddPurchaseReportEventName(builder, purchaseReportEventName)

def ShopCashExcelEnd(builder):
    return builder.EndObject()

def End(builder):
    return ShopCashExcelEnd(builder)
