# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Excel

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SkillSelectExTooltipExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SkillSelectExTooltipExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSkillSelectExTooltipExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SkillSelectExTooltipExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SkillSelectExTooltipExcel
    def GroupId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # SkillSelectExTooltipExcel
    def SelectableExSkillGroupId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SkillSelectExTooltipExcel
    def SkillUseConditionLocalizeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def SkillSelectExTooltipExcelStart(builder):
    builder.StartObject(3)

def Start(builder):
    SkillSelectExTooltipExcelStart(builder)

def SkillSelectExTooltipExcelAddGroupId(builder, groupId):
    builder.PrependInt64Slot(0, groupId, 0)

def AddGroupId(builder, groupId):
    SkillSelectExTooltipExcelAddGroupId(builder, groupId)

def SkillSelectExTooltipExcelAddSelectableExSkillGroupId(builder, selectableExSkillGroupId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(selectableExSkillGroupId), 0)

def AddSelectableExSkillGroupId(builder, selectableExSkillGroupId):
    SkillSelectExTooltipExcelAddSelectableExSkillGroupId(builder, selectableExSkillGroupId)

def SkillSelectExTooltipExcelAddSkillUseConditionLocalizeId(builder, skillUseConditionLocalizeId):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(skillUseConditionLocalizeId), 0)

def AddSkillUseConditionLocalizeId(builder, skillUseConditionLocalizeId):
    SkillSelectExTooltipExcelAddSkillUseConditionLocalizeId(builder, skillUseConditionLocalizeId)

def SkillSelectExTooltipExcelEnd(builder):
    return builder.EndObject()

def End(builder):
    return SkillSelectExTooltipExcelEnd(builder)


class SkillSelectExTooltipExcelT(object):

    # SkillSelectExTooltipExcelT
    def __init__(
        self,
        groupId = 0,
        selectableExSkillGroupId = None,
        skillUseConditionLocalizeId = None,
    ):
        self.groupId = groupId  # type: int
        self.selectableExSkillGroupId = selectableExSkillGroupId  # type: Optional[str]
        self.skillUseConditionLocalizeId = skillUseConditionLocalizeId  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        skillSelectExTooltipExcel = SkillSelectExTooltipExcel()
        skillSelectExTooltipExcel.Init(buf, pos)
        return cls.InitFromObj(skillSelectExTooltipExcel)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, skillSelectExTooltipExcel):
        x = SkillSelectExTooltipExcelT()
        x._UnPack(skillSelectExTooltipExcel)
        return x

    # SkillSelectExTooltipExcelT
    def _UnPack(self, skillSelectExTooltipExcel):
        if skillSelectExTooltipExcel is None:
            return
        self.groupId = skillSelectExTooltipExcel.GroupId()
        self.selectableExSkillGroupId = skillSelectExTooltipExcel.SelectableExSkillGroupId()
        self.skillUseConditionLocalizeId = skillSelectExTooltipExcel.SkillUseConditionLocalizeId()

    # SkillSelectExTooltipExcelT
    def Pack(self, builder):
        if self.selectableExSkillGroupId is not None:
            selectableExSkillGroupId = builder.CreateString(self.selectableExSkillGroupId)
        if self.skillUseConditionLocalizeId is not None:
            skillUseConditionLocalizeId = builder.CreateString(self.skillUseConditionLocalizeId)
        SkillSelectExTooltipExcelStart(builder)
        SkillSelectExTooltipExcelAddGroupId(builder, self.groupId)
        if self.selectableExSkillGroupId is not None:
            SkillSelectExTooltipExcelAddSelectableExSkillGroupId(builder, selectableExSkillGroupId)
        if self.skillUseConditionLocalizeId is not None:
            SkillSelectExTooltipExcelAddSkillUseConditionLocalizeId(builder, skillUseConditionLocalizeId)
        skillSelectExTooltipExcel = SkillSelectExTooltipExcelEnd(builder)
        return skillSelectExTooltipExcel
