// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package excel

import "strconv"

type BulletType int32

const (
	BulletTypeNormal    BulletType = 0
	BulletTypePierce    BulletType = 1
	BulletTypeExplosion BulletType = 2
	BulletTypeSiege     BulletType = 3
	BulletTypeMystic    BulletType = 4
	BulletTypeNone      BulletType = 5
	BulletTypeSonic     BulletType = 6
)

var EnumNamesBulletType = map[BulletType]string{
	BulletTypeNormal:    "Normal",
	BulletTypePierce:    "Pierce",
	BulletTypeExplosion: "Explosion",
	BulletTypeSiege:     "Siege",
	BulletTypeMystic:    "Mystic",
	BulletTypeNone:      "None",
	BulletTypeSonic:     "Sonic",
}

var EnumValuesBulletType = map[string]BulletType{
	"Normal":    BulletTypeNormal,
	"Pierce":    BulletTypePierce,
	"Explosion": BulletTypeExplosion,
	"Siege":     BulletTypeSiege,
	"Mystic":    BulletTypeMystic,
	"None":      BulletTypeNone,
	"Sonic":     BulletTypeSonic,
}

func (v BulletType) String() string {
	if s, ok := EnumNamesBulletType[v]; ok {
		return s
	}
	return "BulletType(" + strconv.FormatInt(int64(v), 10) + ")"
}
