// Code generated by fbsgen. DO NOT EDIT.
// Package excel contains generated code for a FlatBuffers schema.
package excel

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// CafeInfoExcelDto represents a FlatBuffers table.
type CafeInfoExcelDto struct {
	fbsutils.FlatBuffer
	CafeID                  int64                `json:"cafe_id"`
	IsDefault               bool                 `json:"is_default"`
	OpenConditionCafeID     OpenConditionContent `json:"open_condition_cafe_id"`
	OpenConditionCafeInvite OpenConditionContent `json:"open_condition_cafe_invite"`
	SummonParcelType        ParcelType           `json:"summon_parcel_type"`
	SummonParcelID          int64                `json:"summon_parcel_id"`
	SummonParcelAmount      int64                `json:"summon_parcel_amount"`
	CategoryType            ShopCategoryType     `json:"category_type"`
	SummonTicketIconPath    string               `json:"summon_ticket_icon_path"`
}

// MarshalModel marshals the struct into a FlatBuffers offset.
func (t *CafeInfoExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	summonTicketIconPathOffset := b.CreateString(t.SummonTicketIconPath)
	CafeInfoExcelStart(b)
	CafeInfoExcelAddCafeId(b, t.CafeID)
	CafeInfoExcelAddIsDefault(b, t.IsDefault)
	CafeInfoExcelAddOpenConditionCafeId(b, t.OpenConditionCafeID)
	CafeInfoExcelAddOpenConditionCafeInvite(b, t.OpenConditionCafeInvite)
	CafeInfoExcelAddSummonParcelType(b, t.SummonParcelType)
	CafeInfoExcelAddSummonParcelId(b, t.SummonParcelID)
	CafeInfoExcelAddSummonParcelAmount(b, t.SummonParcelAmount)
	CafeInfoExcelAddCategoryType(b, t.CategoryType)
	CafeInfoExcelAddSummonTicketIconPath(b, summonTicketIconPathOffset)
	return CafeInfoExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer.
func (t *CafeInfoExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers table.
func (t *CafeInfoExcelDto) UnmarshalMessage(e *CafeInfoExcel) error {
	t.CafeID = e.CafeId()
	t.IsDefault = e.IsDefault()
	t.OpenConditionCafeID = e.OpenConditionCafeId()
	t.OpenConditionCafeInvite = e.OpenConditionCafeInvite()
	t.SummonParcelType = e.SummonParcelType()
	t.SummonParcelID = e.SummonParcelId()
	t.SummonParcelAmount = e.SummonParcelAmount()
	t.CategoryType = e.CategoryType()
	t.SummonTicketIconPath = string(e.SummonTicketIconPath())
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer.
func (t *CafeInfoExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsCafeInfoExcel(data, 0)
	return t.UnmarshalMessage(root)
}

// FlatDataName returns the FlatBuffers table name.
func (CafeInfoExcelDto) FlatDataName() string {
	return "CafeInfoExcel"
}
