// Code generated by fbsgen. DO NOT EDIT.
// Package excel contains generated code for a FlatBuffers schema.
package excel

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// CafeProductionExcelDto represents a FlatBuffers table.
type CafeProductionExcelDto struct {
	fbsutils.FlatBuffer
	CafeID                          int64      `json:"cafe_id"`
	Rank                            int64      `json:"rank"`
	CafeProductionParcelType        ParcelType `json:"cafe_production_parcel_type"`
	CafeProductionParcelID          int64      `json:"cafe_production_parcel_id"`
	ParcelProductionCoefficient     int64      `json:"parcel_production_coefficient"`
	ParcelProductionCorrectionValue int64      `json:"parcel_production_correction_value"`
	ParcelStorageMax                int64      `json:"parcel_storage_max"`
}

// MarshalModel marshals the struct into a FlatBuffers offset.
func (t *CafeProductionExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	CafeProductionExcelStart(b)
	CafeProductionExcelAddCafeId(b, t.CafeID)
	CafeProductionExcelAddRank(b, t.Rank)
	CafeProductionExcelAddCafeProductionParcelType(b, t.CafeProductionParcelType)
	CafeProductionExcelAddCafeProductionParcelId(b, t.CafeProductionParcelID)
	CafeProductionExcelAddParcelProductionCoefficient(b, t.ParcelProductionCoefficient)
	CafeProductionExcelAddParcelProductionCorrectionValue(b, t.ParcelProductionCorrectionValue)
	CafeProductionExcelAddParcelStorageMax(b, t.ParcelStorageMax)
	return CafeProductionExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer.
func (t *CafeProductionExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers table.
func (t *CafeProductionExcelDto) UnmarshalMessage(e *CafeProductionExcel) error {
	t.CafeID = e.CafeId()
	t.Rank = e.Rank()
	t.CafeProductionParcelType = e.CafeProductionParcelType()
	t.CafeProductionParcelID = e.CafeProductionParcelId()
	t.ParcelProductionCoefficient = e.ParcelProductionCoefficient()
	t.ParcelProductionCorrectionValue = e.ParcelProductionCorrectionValue()
	t.ParcelStorageMax = e.ParcelStorageMax()
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer.
func (t *CafeProductionExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsCafeProductionExcel(data, 0)
	return t.UnmarshalMessage(root)
}

// FlatDataName returns the FlatBuffers table name.
func (CafeProductionExcelDto) FlatDataName() string {
	return "CafeProductionExcel"
}
