// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package excel

import "strconv"

type CCGCharacterType int32

const (
	CCGCharacterTypeNone    CCGCharacterType = 0
	CCGCharacterTypeStriker CCGCharacterType = 1
	CCGCharacterTypeSpecial CCGCharacterType = 2
)

var EnumNamesCCGCharacterType = map[CCGCharacterType]string{
	CCGCharacterTypeNone:    "None",
	CCGCharacterTypeStriker: "Striker",
	CCGCharacterTypeSpecial: "Special",
}

var EnumValuesCCGCharacterType = map[string]CCGCharacterType{
	"None":    CCGCharacterTypeNone,
	"Striker": CCGCharacterTypeStriker,
	"Special": CCGCharacterTypeSpecial,
}

func (v CCGCharacterType) String() string {
	if s, ok := EnumNamesCCGCharacterType[v]; ok {
		return s
	}
	return "CCGCharacterType(" + strconv.FormatInt(int64(v), 10) + ")"
}
