// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package excel

import "strconv"

type CharacterVoiceOverridePriority int32

const (
	CharacterVoiceOverridePriorityNone CharacterVoiceOverridePriority = 0
	CharacterVoiceOverridePriorityHigh CharacterVoiceOverridePriority = 1
	CharacterVoiceOverridePriorityLow  CharacterVoiceOverridePriority = 2
)

var EnumNamesCharacterVoiceOverridePriority = map[CharacterVoiceOverridePriority]string{
	CharacterVoiceOverridePriorityNone: "None",
	CharacterVoiceOverridePriorityHigh: "High",
	CharacterVoiceOverridePriorityLow:  "Low",
}

var EnumValuesCharacterVoiceOverridePriority = map[string]CharacterVoiceOverridePriority{
	"None": CharacterVoiceOverridePriorityNone,
	"High": CharacterVoiceOverridePriorityHigh,
	"Low":  CharacterVoiceOverridePriorityLow,
}

func (v CharacterVoiceOverridePriority) String() string {
	if s, ok := EnumNamesCharacterVoiceOverridePriority[v]; ok {
		return s
	}
	return "CharacterVoiceOverridePriority(" + strconv.FormatInt(int64(v), 10) + ")"
}
