// Code generated by fbsgen. DO NOT EDIT.
// Package excel contains generated code for FlatBuffers schema
package excel

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// ContentSpoilerPopupExcelDto represents a FlatBuffers table
type ContentSpoilerPopupExcelDto struct {
	fbsutils.FlatBuffer
	ContentType             ContentType      `json:"content_type"`
	SpoilerPopupTitle       uint32           `json:"spoiler_popup_title"`
	SpoilerPopupDescription uint32           `json:"spoiler_popup_description"`
	PopupType               SpoilerPopupType `json:"popup_type"`
	ConditionScenarioModeId int64            `json:"condition_scenario_mode_id"`
}

// MarshalModel marshals the struct into flatbuffers offset
func (t *ContentSpoilerPopupExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	ContentSpoilerPopupExcelStart(b)
	ContentSpoilerPopupExcelAddContentType(b, fbsutils.Convert(t.ContentType, t.FlatBuffer.TableKey))
	ContentSpoilerPopupExcelAddSpoilerPopupTitle(b, fbsutils.Convert(t.SpoilerPopupTitle, t.FlatBuffer.TableKey))
	ContentSpoilerPopupExcelAddSpoilerPopupDescription(b, fbsutils.Convert(t.SpoilerPopupDescription, t.FlatBuffer.TableKey))
	ContentSpoilerPopupExcelAddPopupType(b, fbsutils.Convert(t.PopupType, t.FlatBuffer.TableKey))
	ContentSpoilerPopupExcelAddConditionScenarioModeId(b, fbsutils.Convert(t.ConditionScenarioModeId, t.FlatBuffer.TableKey))
	return ContentSpoilerPopupExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer
func (t *ContentSpoilerPopupExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers buffer
func (t *ContentSpoilerPopupExcelDto) UnmarshalMessage(e *ContentSpoilerPopupExcel) error {
	t.ContentType = ContentType(fbsutils.Convert(int32(e.ContentType()), t.FlatBuffer.TableKey))
	t.SpoilerPopupTitle = fbsutils.Convert(e.SpoilerPopupTitle(), t.FlatBuffer.TableKey)
	t.SpoilerPopupDescription = fbsutils.Convert(e.SpoilerPopupDescription(), t.FlatBuffer.TableKey)
	t.PopupType = SpoilerPopupType(fbsutils.Convert(int32(e.PopupType()), t.FlatBuffer.TableKey))
	t.ConditionScenarioModeId = fbsutils.Convert(e.ConditionScenarioModeId(), t.FlatBuffer.TableKey)
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer
func (t *ContentSpoilerPopupExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsContentSpoilerPopupExcel(data, 0)
	err := t.UnmarshalMessage(root)
	if err != nil {
		return err
	}
	return nil
}

// Name returns the name of the flatbuffer table name
func (ContentSpoilerPopupExcelDto) FlatDataName() string {
	return "ContentSpoilerPopupExcel"
}
