// Code generated by fbsgen. DO NOT EDIT.
// Package excel contains generated code for a FlatBuffers schema.
package excel

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// EliminateRaidStageRewardExcelDto represents a FlatBuffers table.
type EliminateRaidStageRewardExcelDto struct {
	fbsutils.FlatBuffer
	GroupID                        int64      `json:"group_id"`
	IsClearStageRewardHideInfo     bool       `json:"is_clear_stage_reward_hide_info"`
	ClearStageRewardProb           int64      `json:"clear_stage_reward_prob"`
	ClearStageRewardParcelType     ParcelType `json:"clear_stage_reward_parcel_type"`
	ClearStageRewardParcelUniqueID int64      `json:"clear_stage_reward_parcel_unique_id"`
	ClearStageRewardAmount         int64      `json:"clear_stage_reward_amount"`
}

// MarshalModel marshals the struct into a FlatBuffers offset.
func (t *EliminateRaidStageRewardExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	EliminateRaidStageRewardExcelStart(b)
	EliminateRaidStageRewardExcelAddGroupId(b, t.GroupID)
	EliminateRaidStageRewardExcelAddIsClearStageRewardHideInfo(b, t.IsClearStageRewardHideInfo)
	EliminateRaidStageRewardExcelAddClearStageRewardProb(b, t.ClearStageRewardProb)
	EliminateRaidStageRewardExcelAddClearStageRewardParcelType(b, t.ClearStageRewardParcelType)
	EliminateRaidStageRewardExcelAddClearStageRewardParcelUniqueId(b, t.ClearStageRewardParcelUniqueID)
	EliminateRaidStageRewardExcelAddClearStageRewardAmount(b, t.ClearStageRewardAmount)
	return EliminateRaidStageRewardExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer.
func (t *EliminateRaidStageRewardExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers table.
func (t *EliminateRaidStageRewardExcelDto) UnmarshalMessage(e *EliminateRaidStageRewardExcel) error {
	t.GroupID = e.GroupId()
	t.IsClearStageRewardHideInfo = e.IsClearStageRewardHideInfo()
	t.ClearStageRewardProb = e.ClearStageRewardProb()
	t.ClearStageRewardParcelType = e.ClearStageRewardParcelType()
	t.ClearStageRewardParcelUniqueID = e.ClearStageRewardParcelUniqueId()
	t.ClearStageRewardAmount = e.ClearStageRewardAmount()
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer.
func (t *EliminateRaidStageRewardExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsEliminateRaidStageRewardExcel(data, 0)
	return t.UnmarshalMessage(root)
}

// FlatDataName returns the FlatBuffers table name.
func (EliminateRaidStageRewardExcelDto) FlatDataName() string {
	return "EliminateRaidStageRewardExcel"
}
