// Code generated by fbsgen. DO NOT EDIT.
// Package excel contains generated code for FlatBuffers schema
package excel

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// EventContentShopExcelDto represents a FlatBuffers table
type EventContentShopExcelDto struct {
	fbsutils.FlatBuffer
	RestrictBuyWhenInventoryFull bool                   `json:"restrict_buy_when_inventory_full"`
	BuyReportEventName           string                 `json:"buy_report_event_name"`
	PurchaseCountResetType       PurchaseCountResetType `json:"purchase_count_reset_type"`
	PurchaseCountLimit           int64                  `json:"purchase_count_limit"`
	PurchaseCooltimeMin          int64                  `json:"purchase_cooltime_min"`
	SalePeriodTo                 string                 `json:"sale_period_to"`
	SalePeriodFrom               string                 `json:"sale_period_from"`
	DisplayOrder                 int64                  `json:"display_order"`
	GoodsId                      []int64                `json:"goods_id"`
	IsLegacy                     bool                   `json:"is_legacy"`
	CategoryType                 ShopCategoryType       `json:"category_type"`
	LocalizeEtcId                uint32                 `json:"localize_etc_id"`
	Id                           int64                  `json:"id"`
	EventContentId               int64                  `json:"event_content_id"`
}

// MarshalModel marshals the struct into flatbuffers offset
func (t *EventContentShopExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	EventContentShopExcelStart(b)
	EventContentShopExcelAddRestrictBuyWhenInventoryFull(b, t.RestrictBuyWhenInventoryFull)
	EventContentShopExcelAddBuyReportEventName(b, b.CreateString(fbsutils.Convert(t.BuyReportEventName, t.FlatBuffer.TableKey)))
	EventContentShopExcelAddPurchaseCountResetType(b, fbsutils.Convert(t.PurchaseCountResetType, t.FlatBuffer.TableKey))
	EventContentShopExcelAddPurchaseCountLimit(b, fbsutils.Convert(t.PurchaseCountLimit, t.FlatBuffer.TableKey))
	EventContentShopExcelAddPurchaseCooltimeMin(b, fbsutils.Convert(t.PurchaseCooltimeMin, t.FlatBuffer.TableKey))
	EventContentShopExcelAddSalePeriodTo(b, b.CreateString(fbsutils.Convert(t.SalePeriodTo, t.FlatBuffer.TableKey)))
	EventContentShopExcelAddSalePeriodFrom(b, b.CreateString(fbsutils.Convert(t.SalePeriodFrom, t.FlatBuffer.TableKey)))
	EventContentShopExcelAddDisplayOrder(b, fbsutils.Convert(t.DisplayOrder, t.FlatBuffer.TableKey))
	EventContentShopExcelStartGoodsIdVector(b, len(t.GoodsId))
	for i := range len(t.GoodsId) {
		b.PrependInt64(fbsutils.Convert(t.GoodsId[len(t.GoodsId)-i-1], t.FlatBuffer.TableKey))
	}
	EventContentShopExcelAddGoodsId(b, b.EndVector(len(t.GoodsId)))
	EventContentShopExcelAddIsLegacy(b, t.IsLegacy)
	EventContentShopExcelAddCategoryType(b, fbsutils.Convert(t.CategoryType, t.FlatBuffer.TableKey))
	EventContentShopExcelAddLocalizeEtcId(b, fbsutils.Convert(t.LocalizeEtcId, t.FlatBuffer.TableKey))
	EventContentShopExcelAddId(b, fbsutils.Convert(t.Id, t.FlatBuffer.TableKey))
	EventContentShopExcelAddEventContentId(b, fbsutils.Convert(t.EventContentId, t.FlatBuffer.TableKey))
	return EventContentShopExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer
func (t *EventContentShopExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers buffer
func (t *EventContentShopExcelDto) UnmarshalMessage(e *EventContentShopExcel) error {
	t.RestrictBuyWhenInventoryFull = e.RestrictBuyWhenInventoryFull()
	t.BuyReportEventName = fbsutils.Convert(string(e.BuyReportEventName()), t.FlatBuffer.TableKey)
	t.PurchaseCountResetType = PurchaseCountResetType(fbsutils.Convert(int32(e.PurchaseCountResetType()), t.FlatBuffer.TableKey))
	t.PurchaseCountLimit = fbsutils.Convert(e.PurchaseCountLimit(), t.FlatBuffer.TableKey)
	t.PurchaseCooltimeMin = fbsutils.Convert(e.PurchaseCooltimeMin(), t.FlatBuffer.TableKey)
	t.SalePeriodTo = fbsutils.Convert(string(e.SalePeriodTo()), t.FlatBuffer.TableKey)
	t.SalePeriodFrom = fbsutils.Convert(string(e.SalePeriodFrom()), t.FlatBuffer.TableKey)
	t.DisplayOrder = fbsutils.Convert(e.DisplayOrder(), t.FlatBuffer.TableKey)
	t.GoodsId = make([]int64, e.GoodsIdLength())
	for i := range e.GoodsIdLength() {
		t.GoodsId[i] = fbsutils.Convert(e.GoodsId(i), t.FlatBuffer.TableKey)
	}
	t.IsLegacy = e.IsLegacy()
	t.CategoryType = ShopCategoryType(fbsutils.Convert(int32(e.CategoryType()), t.FlatBuffer.TableKey))
	t.LocalizeEtcId = fbsutils.Convert(e.LocalizeEtcId(), t.FlatBuffer.TableKey)
	t.Id = fbsutils.Convert(e.Id(), t.FlatBuffer.TableKey)
	t.EventContentId = fbsutils.Convert(e.EventContentId(), t.FlatBuffer.TableKey)
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer
func (t *EventContentShopExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsEventContentShopExcel(data, 0)
	err := t.UnmarshalMessage(root)
	if err != nil {
		return err
	}
	return nil
}

// Name returns the name of the flatbuffer table name
func (EventContentShopExcelDto) FlatDataName() string {
	return "EventContentShopExcel"
}
