// Code generated by fbsgen. DO NOT EDIT.
// Package excel contains generated code for a FlatBuffers schema.
package excel

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// EventContentFortuneGachaShopExcelDto represents a FlatBuffers table.
type EventContentFortuneGachaShopExcelDto struct {
	fbsutils.FlatBuffer
	EventContentID      int64        `json:"event_content_id"`
	ID                  int64        `json:"id"`
	Grade               int32        `json:"grade"`
	CostGoodsID         int64        `json:"cost_goods_id"`
	IsLegacy            bool         `json:"is_legacy"`
	FortuneGachaGroupID int32        `json:"fortune_gacha_group_id"`
	Prob                int32        `json:"prob"`
	ProbModifyValue     int32        `json:"prob_modify_value"`
	ProbModifyLimit     int32        `json:"prob_modify_limit"`
	RewardParcelType    []ParcelType `json:"reward_parcel_type"`
	RewardParcelID      []int64      `json:"reward_parcel_id"`
	RewardParcelAmount  []int64      `json:"reward_parcel_amount"`
}

// MarshalModel marshals the struct into a FlatBuffers offset.
func (t *EventContentFortuneGachaShopExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	EventContentFortuneGachaShopExcelStartRewardParcelTypeVector(b, len(t.RewardParcelType))
	for i := len(t.RewardParcelType) - 1; i >= 0; i-- {
		b.PrependInt32(int32(t.RewardParcelType[i]))
	}
	rewardParcelTypeOffset := b.EndVector(len(t.RewardParcelType))
	EventContentFortuneGachaShopExcelStartRewardParcelIdVector(b, len(t.RewardParcelID))
	for i := len(t.RewardParcelID) - 1; i >= 0; i-- {
		b.PrependInt64(t.RewardParcelID[i])
	}
	rewardParcelIDOffset := b.EndVector(len(t.RewardParcelID))
	EventContentFortuneGachaShopExcelStartRewardParcelAmountVector(b, len(t.RewardParcelAmount))
	for i := len(t.RewardParcelAmount) - 1; i >= 0; i-- {
		b.PrependInt64(t.RewardParcelAmount[i])
	}
	rewardParcelAmountOffset := b.EndVector(len(t.RewardParcelAmount))
	EventContentFortuneGachaShopExcelStart(b)
	EventContentFortuneGachaShopExcelAddEventContentId(b, t.EventContentID)
	EventContentFortuneGachaShopExcelAddId(b, t.ID)
	EventContentFortuneGachaShopExcelAddGrade(b, t.Grade)
	EventContentFortuneGachaShopExcelAddCostGoodsId(b, t.CostGoodsID)
	EventContentFortuneGachaShopExcelAddIsLegacy(b, t.IsLegacy)
	EventContentFortuneGachaShopExcelAddFortuneGachaGroupId(b, t.FortuneGachaGroupID)
	EventContentFortuneGachaShopExcelAddProb(b, t.Prob)
	EventContentFortuneGachaShopExcelAddProbModifyValue(b, t.ProbModifyValue)
	EventContentFortuneGachaShopExcelAddProbModifyLimit(b, t.ProbModifyLimit)
	EventContentFortuneGachaShopExcelAddRewardParcelType(b, rewardParcelTypeOffset)
	EventContentFortuneGachaShopExcelAddRewardParcelId(b, rewardParcelIDOffset)
	EventContentFortuneGachaShopExcelAddRewardParcelAmount(b, rewardParcelAmountOffset)
	return EventContentFortuneGachaShopExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer.
func (t *EventContentFortuneGachaShopExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers table.
func (t *EventContentFortuneGachaShopExcelDto) UnmarshalMessage(e *EventContentFortuneGachaShopExcel) error {
	t.EventContentID = e.EventContentId()
	t.ID = e.Id()
	t.Grade = e.Grade()
	t.CostGoodsID = e.CostGoodsId()
	t.IsLegacy = e.IsLegacy()
	t.FortuneGachaGroupID = e.FortuneGachaGroupId()
	t.Prob = e.Prob()
	t.ProbModifyValue = e.ProbModifyValue()
	t.ProbModifyLimit = e.ProbModifyLimit()
	t.RewardParcelType = make([]ParcelType, e.RewardParcelTypeLength())
	for i := 0; i < e.RewardParcelTypeLength(); i++ {
		t.RewardParcelType[i] = e.RewardParcelType(i)
	}
	t.RewardParcelID = make([]int64, e.RewardParcelIdLength())
	for i := 0; i < e.RewardParcelIdLength(); i++ {
		t.RewardParcelID[i] = e.RewardParcelId(i)
	}
	t.RewardParcelAmount = make([]int64, e.RewardParcelAmountLength())
	for i := 0; i < e.RewardParcelAmountLength(); i++ {
		t.RewardParcelAmount[i] = e.RewardParcelAmount(i)
	}
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer.
func (t *EventContentFortuneGachaShopExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsEventContentFortuneGachaShopExcel(data, 0)
	return t.UnmarshalMessage(root)
}

// FlatDataName returns the FlatBuffers table name.
func (EventContentFortuneGachaShopExcelDto) FlatDataName() string {
	return "EventContentFortuneGachaShopExcel"
}
