// Code generated by fbsgen. DO NOT EDIT.
// Package excel contains generated code for FlatBuffers schema
package excel

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// EventContentTreasureCellRewardExcelDto represents a FlatBuffers table
type EventContentTreasureCellRewardExcelDto struct {
	fbsutils.FlatBuffer
	RewardParcelAmount []int64      `json:"reward_parcel_amount"`
	RewardParcelId     []int64      `json:"reward_parcel_id"`
	RewardParcelType   []ParcelType `json:"reward_parcel_type"`
	LocalizeCodeId     string       `json:"localize_code_id"`
	Id                 int64        `json:"id"`
}

// MarshalModel marshals the struct into flatbuffers offset
func (t *EventContentTreasureCellRewardExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	EventContentTreasureCellRewardExcelStart(b)
	EventContentTreasureCellRewardExcelStartRewardParcelAmountVector(b, len(t.RewardParcelAmount))
	for i := range len(t.RewardParcelAmount) {
		b.PrependInt64(fbsutils.Convert(t.RewardParcelAmount[len(t.RewardParcelAmount)-i-1], t.FlatBuffer.TableKey))
	}
	EventContentTreasureCellRewardExcelAddRewardParcelAmount(b, b.EndVector(len(t.RewardParcelAmount)))
	EventContentTreasureCellRewardExcelStartRewardParcelIdVector(b, len(t.RewardParcelId))
	for i := range len(t.RewardParcelId) {
		b.PrependInt64(fbsutils.Convert(t.RewardParcelId[len(t.RewardParcelId)-i-1], t.FlatBuffer.TableKey))
	}
	EventContentTreasureCellRewardExcelAddRewardParcelId(b, b.EndVector(len(t.RewardParcelId)))
	EventContentTreasureCellRewardExcelStartRewardParcelTypeVector(b, len(t.RewardParcelType))
	for i := range len(t.RewardParcelType) {
		b.PrependInt32(fbsutils.Convert(int32(t.RewardParcelType[len(t.RewardParcelType)-i-1]), t.FlatBuffer.TableKey))
	}
	EventContentTreasureCellRewardExcelAddRewardParcelType(b, b.EndVector(len(t.RewardParcelType)))
	EventContentTreasureCellRewardExcelAddLocalizeCodeId(b, b.CreateString(fbsutils.Convert(t.LocalizeCodeId, t.FlatBuffer.TableKey)))
	EventContentTreasureCellRewardExcelAddId(b, fbsutils.Convert(t.Id, t.FlatBuffer.TableKey))
	return EventContentTreasureCellRewardExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer
func (t *EventContentTreasureCellRewardExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers buffer
func (t *EventContentTreasureCellRewardExcelDto) UnmarshalMessage(e *EventContentTreasureCellRewardExcel) error {
	t.RewardParcelAmount = make([]int64, e.RewardParcelAmountLength())
	for i := range e.RewardParcelAmountLength() {
		t.RewardParcelAmount[i] = fbsutils.Convert(e.RewardParcelAmount(i), t.FlatBuffer.TableKey)
	}
	t.RewardParcelId = make([]int64, e.RewardParcelIdLength())
	for i := range e.RewardParcelIdLength() {
		t.RewardParcelId[i] = fbsutils.Convert(e.RewardParcelId(i), t.FlatBuffer.TableKey)
	}
	t.RewardParcelType = make([]ParcelType, e.RewardParcelTypeLength())
	for i := range e.RewardParcelTypeLength() {
		t.RewardParcelType[i] = ParcelType(fbsutils.Convert(int32(e.RewardParcelType(i)), t.FlatBuffer.TableKey))
	}
	t.LocalizeCodeId = fbsutils.Convert(string(e.LocalizeCodeId()), t.FlatBuffer.TableKey)
	t.Id = fbsutils.Convert(e.Id(), t.FlatBuffer.TableKey)
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer
func (t *EventContentTreasureCellRewardExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsEventContentTreasureCellRewardExcel(data, 0)
	err := t.UnmarshalMessage(root)
	if err != nil {
		return err
	}
	return nil
}

// Name returns the name of the flatbuffer table name
func (EventContentTreasureCellRewardExcelDto) FlatDataName() string {
	return "EventContentTreasureCellRewardExcel"
}
