// Code generated by fbsgen. DO NOT EDIT.
// Package excel contains generated code for FlatBuffers schema
package excel

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// FieldQuestGroupExcelDto represents a FlatBuffers table
type FieldQuestGroupExcelDto struct {
	fbsutils.FlatBuffer
	Id                    int64 `json:"id"`
	SkipFromInteractionId int64 `json:"skip_from_interaction_id"`
	SkipToInteractionId   int64 `json:"skip_to_interaction_id"`
	NextSceneId           int64 `json:"next_scene_id"`
	SkipResultUi          bool  `json:"skip_result_ui"`
}

// MarshalModel marshals the struct into flatbuffers offset
func (t *FieldQuestGroupExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	FieldQuestGroupExcelStart(b)
	FieldQuestGroupExcelAddId(b, fbsutils.Convert(t.Id, t.FlatBuffer.TableKey))
	FieldQuestGroupExcelAddSkipFromInteractionId(b, fbsutils.Convert(t.SkipFromInteractionId, t.FlatBuffer.TableKey))
	FieldQuestGroupExcelAddSkipToInteractionId(b, fbsutils.Convert(t.SkipToInteractionId, t.FlatBuffer.TableKey))
	FieldQuestGroupExcelAddNextSceneId(b, fbsutils.Convert(t.NextSceneId, t.FlatBuffer.TableKey))
	FieldQuestGroupExcelAddSkipResultUi(b, t.SkipResultUi)
	return FieldQuestGroupExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer
func (t *FieldQuestGroupExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers buffer
func (t *FieldQuestGroupExcelDto) UnmarshalMessage(e *FieldQuestGroupExcel) error {
	t.Id = fbsutils.Convert(e.Id(), t.FlatBuffer.TableKey)
	t.SkipFromInteractionId = fbsutils.Convert(e.SkipFromInteractionId(), t.FlatBuffer.TableKey)
	t.SkipToInteractionId = fbsutils.Convert(e.SkipToInteractionId(), t.FlatBuffer.TableKey)
	t.NextSceneId = fbsutils.Convert(e.NextSceneId(), t.FlatBuffer.TableKey)
	t.SkipResultUi = e.SkipResultUi()
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer
func (t *FieldQuestGroupExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsFieldQuestGroupExcel(data, 0)
	err := t.UnmarshalMessage(root)
	if err != nil {
		return err
	}
	return nil
}

// Name returns the name of the flatbuffer table name
func (FieldQuestGroupExcelDto) FlatDataName() string {
	return "FieldQuestGroupExcel"
}
