// Code generated by fbsgen. DO NOT EDIT.
// Package excel contains generated code for a FlatBuffers schema.
package excel

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// InteractiveWorldRaidArcadeMachineExcelDto represents a FlatBuffers table.
type InteractiveWorldRaidArcadeMachineExcelDto struct {
	fbsutils.FlatBuffer
	EventContentID              int64              `json:"event_content_id"`
	MiniGameType                []EventContentType `json:"mini_game_type"`
	MiniGameCostItemID          []int64            `json:"mini_game_cost_item_id"`
	MiniGameCostItemAmount      []int64            `json:"mini_game_cost_item_amount"`
	MiniGameSoftLimitItemID     []string           `json:"mini_game_soft_limit_item_id"`
	MiniGameSoftLimitItemAmount []string           `json:"mini_game_soft_limit_item_amount"`
	MiniGameImage               []string           `json:"mini_game_image"`
	LocalizeTitle               []uint32           `json:"localize_title"`
	LocalizeDesc                []uint32           `json:"localize_desc"`
}

// MarshalModel marshals the struct into a FlatBuffers offset.
func (t *InteractiveWorldRaidArcadeMachineExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	InteractiveWorldRaidArcadeMachineExcelStartMiniGameTypeVector(b, len(t.MiniGameType))
	for i := len(t.MiniGameType) - 1; i >= 0; i-- {
		b.PrependInt32(int32(t.MiniGameType[i]))
	}
	miniGameTypeOffset := b.EndVector(len(t.MiniGameType))
	InteractiveWorldRaidArcadeMachineExcelStartMiniGameCostItemIdVector(b, len(t.MiniGameCostItemID))
	for i := len(t.MiniGameCostItemID) - 1; i >= 0; i-- {
		b.PrependInt64(t.MiniGameCostItemID[i])
	}
	miniGameCostItemIDOffset := b.EndVector(len(t.MiniGameCostItemID))
	InteractiveWorldRaidArcadeMachineExcelStartMiniGameCostItemAmountVector(b, len(t.MiniGameCostItemAmount))
	for i := len(t.MiniGameCostItemAmount) - 1; i >= 0; i-- {
		b.PrependInt64(t.MiniGameCostItemAmount[i])
	}
	miniGameCostItemAmountOffset := b.EndVector(len(t.MiniGameCostItemAmount))
	var miniGameSoftLimitItemIDOffset flatbuffers.UOffsetT
	miniGameSoftLimitItemIDOffsets := make([]flatbuffers.UOffsetT, len(t.MiniGameSoftLimitItemID))
	for i := range t.MiniGameSoftLimitItemID {
		miniGameSoftLimitItemIDOffsets[i] = b.CreateString(t.MiniGameSoftLimitItemID[i])
	}
	InteractiveWorldRaidArcadeMachineExcelStartMiniGameSoftLimitItemIdVector(b, len(t.MiniGameSoftLimitItemID))
	for i := len(miniGameSoftLimitItemIDOffsets) - 1; i >= 0; i-- {
		b.PrependUOffsetT(miniGameSoftLimitItemIDOffsets[i])
	}
	miniGameSoftLimitItemIDOffset = b.EndVector(len(t.MiniGameSoftLimitItemID))
	var miniGameSoftLimitItemAmountOffset flatbuffers.UOffsetT
	miniGameSoftLimitItemAmountOffsets := make([]flatbuffers.UOffsetT, len(t.MiniGameSoftLimitItemAmount))
	for i := range t.MiniGameSoftLimitItemAmount {
		miniGameSoftLimitItemAmountOffsets[i] = b.CreateString(t.MiniGameSoftLimitItemAmount[i])
	}
	InteractiveWorldRaidArcadeMachineExcelStartMiniGameSoftLimitItemAmountVector(b, len(t.MiniGameSoftLimitItemAmount))
	for i := len(miniGameSoftLimitItemAmountOffsets) - 1; i >= 0; i-- {
		b.PrependUOffsetT(miniGameSoftLimitItemAmountOffsets[i])
	}
	miniGameSoftLimitItemAmountOffset = b.EndVector(len(t.MiniGameSoftLimitItemAmount))
	var miniGameImageOffset flatbuffers.UOffsetT
	miniGameImageOffsets := make([]flatbuffers.UOffsetT, len(t.MiniGameImage))
	for i := range t.MiniGameImage {
		miniGameImageOffsets[i] = b.CreateString(t.MiniGameImage[i])
	}
	InteractiveWorldRaidArcadeMachineExcelStartMiniGameImageVector(b, len(t.MiniGameImage))
	for i := len(miniGameImageOffsets) - 1; i >= 0; i-- {
		b.PrependUOffsetT(miniGameImageOffsets[i])
	}
	miniGameImageOffset = b.EndVector(len(t.MiniGameImage))
	InteractiveWorldRaidArcadeMachineExcelStartLocalizeTitleVector(b, len(t.LocalizeTitle))
	for i := len(t.LocalizeTitle) - 1; i >= 0; i-- {
		b.PrependUint32(t.LocalizeTitle[i])
	}
	localizeTitleOffset := b.EndVector(len(t.LocalizeTitle))
	InteractiveWorldRaidArcadeMachineExcelStartLocalizeDescVector(b, len(t.LocalizeDesc))
	for i := len(t.LocalizeDesc) - 1; i >= 0; i-- {
		b.PrependUint32(t.LocalizeDesc[i])
	}
	localizeDescOffset := b.EndVector(len(t.LocalizeDesc))
	InteractiveWorldRaidArcadeMachineExcelStart(b)
	InteractiveWorldRaidArcadeMachineExcelAddEventContentId(b, t.EventContentID)
	InteractiveWorldRaidArcadeMachineExcelAddMiniGameType(b, miniGameTypeOffset)
	InteractiveWorldRaidArcadeMachineExcelAddMiniGameCostItemId(b, miniGameCostItemIDOffset)
	InteractiveWorldRaidArcadeMachineExcelAddMiniGameCostItemAmount(b, miniGameCostItemAmountOffset)
	InteractiveWorldRaidArcadeMachineExcelAddMiniGameSoftLimitItemId(b, miniGameSoftLimitItemIDOffset)
	InteractiveWorldRaidArcadeMachineExcelAddMiniGameSoftLimitItemAmount(b, miniGameSoftLimitItemAmountOffset)
	InteractiveWorldRaidArcadeMachineExcelAddMiniGameImage(b, miniGameImageOffset)
	InteractiveWorldRaidArcadeMachineExcelAddLocalizeTitle(b, localizeTitleOffset)
	InteractiveWorldRaidArcadeMachineExcelAddLocalizeDesc(b, localizeDescOffset)
	return InteractiveWorldRaidArcadeMachineExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer.
func (t *InteractiveWorldRaidArcadeMachineExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers table.
func (t *InteractiveWorldRaidArcadeMachineExcelDto) UnmarshalMessage(e *InteractiveWorldRaidArcadeMachineExcel) error {
	t.EventContentID = e.EventContentId()
	t.MiniGameType = make([]EventContentType, e.MiniGameTypeLength())
	for i := 0; i < e.MiniGameTypeLength(); i++ {
		t.MiniGameType[i] = e.MiniGameType(i)
	}
	t.MiniGameCostItemID = make([]int64, e.MiniGameCostItemIdLength())
	for i := 0; i < e.MiniGameCostItemIdLength(); i++ {
		t.MiniGameCostItemID[i] = e.MiniGameCostItemId(i)
	}
	t.MiniGameCostItemAmount = make([]int64, e.MiniGameCostItemAmountLength())
	for i := 0; i < e.MiniGameCostItemAmountLength(); i++ {
		t.MiniGameCostItemAmount[i] = e.MiniGameCostItemAmount(i)
	}
	t.MiniGameSoftLimitItemID = make([]string, e.MiniGameSoftLimitItemIdLength())
	for i := 0; i < e.MiniGameSoftLimitItemIdLength(); i++ {
		t.MiniGameSoftLimitItemID[i] = string(e.MiniGameSoftLimitItemId(i))
	}
	t.MiniGameSoftLimitItemAmount = make([]string, e.MiniGameSoftLimitItemAmountLength())
	for i := 0; i < e.MiniGameSoftLimitItemAmountLength(); i++ {
		t.MiniGameSoftLimitItemAmount[i] = string(e.MiniGameSoftLimitItemAmount(i))
	}
	t.MiniGameImage = make([]string, e.MiniGameImageLength())
	for i := 0; i < e.MiniGameImageLength(); i++ {
		t.MiniGameImage[i] = string(e.MiniGameImage(i))
	}
	t.LocalizeTitle = make([]uint32, e.LocalizeTitleLength())
	for i := 0; i < e.LocalizeTitleLength(); i++ {
		t.LocalizeTitle[i] = e.LocalizeTitle(i)
	}
	t.LocalizeDesc = make([]uint32, e.LocalizeDescLength())
	for i := 0; i < e.LocalizeDescLength(); i++ {
		t.LocalizeDesc[i] = e.LocalizeDesc(i)
	}
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer.
func (t *InteractiveWorldRaidArcadeMachineExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsInteractiveWorldRaidArcadeMachineExcel(data, 0)
	return t.UnmarshalMessage(root)
}

// FlatDataName returns the FlatBuffers table name.
func (InteractiveWorldRaidArcadeMachineExcelDto) FlatDataName() string {
	return "InteractiveWorldRaidArcadeMachineExcel"
}
