// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package excel

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type InteractiveWorldRaidBossGroupExcel struct {
	_tab flatbuffers.Table
}

func GetRootAsInteractiveWorldRaidBossGroupExcel(buf []byte, offset flatbuffers.UOffsetT) *InteractiveWorldRaidBossGroupExcel {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &InteractiveWorldRaidBossGroupExcel{}
	x.Init(buf, n+offset)
	return x
}

func FinishInteractiveWorldRaidBossGroupExcelBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsInteractiveWorldRaidBossGroupExcel(buf []byte, offset flatbuffers.UOffsetT) *InteractiveWorldRaidBossGroupExcel {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &InteractiveWorldRaidBossGroupExcel{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedInteractiveWorldRaidBossGroupExcelBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *InteractiveWorldRaidBossGroupExcel) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *InteractiveWorldRaidBossGroupExcel) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *InteractiveWorldRaidBossGroupExcel) Id() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *InteractiveWorldRaidBossGroupExcel) MutateId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *InteractiveWorldRaidBossGroupExcel) WorldRaidBossGroupId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *InteractiveWorldRaidBossGroupExcel) MutateWorldRaidBossGroupId(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *InteractiveWorldRaidBossGroupExcel) WorldBossHpLinkGroup() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *InteractiveWorldRaidBossGroupExcel) MutateWorldBossHpLinkGroup(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func (rcv *InteractiveWorldRaidBossGroupExcel) WorldBossName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *InteractiveWorldRaidBossGroupExcel) WorldBossPopupPortrait() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *InteractiveWorldRaidBossGroupExcel) WorldBossPopupNameTexture() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *InteractiveWorldRaidBossGroupExcel) WorldBossPopupBg() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *InteractiveWorldRaidBossGroupExcel) WorldBossParcelPortrait() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *InteractiveWorldRaidBossGroupExcel) WorldBossListParcel() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *InteractiveWorldRaidBossGroupExcel) WorldBossHp() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *InteractiveWorldRaidBossGroupExcel) MutateWorldBossHp(n int64) bool {
	return rcv._tab.MutateInt64Slot(22, n)
}

func (rcv *InteractiveWorldRaidBossGroupExcel) UiHideBeforeSpawn() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *InteractiveWorldRaidBossGroupExcel) MutateUiHideBeforeSpawn(n bool) bool {
	return rcv._tab.MutateBoolSlot(24, n)
}

func (rcv *InteractiveWorldRaidBossGroupExcel) HideAnotherBossKilled() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *InteractiveWorldRaidBossGroupExcel) MutateHideAnotherBossKilled(n bool) bool {
	return rcv._tab.MutateBoolSlot(26, n)
}

func (rcv *InteractiveWorldRaidBossGroupExcel) WorldBossClearRewardGroupId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *InteractiveWorldRaidBossGroupExcel) MutateWorldBossClearRewardGroupId(n int64) bool {
	return rcv._tab.MutateInt64Slot(28, n)
}

func (rcv *InteractiveWorldRaidBossGroupExcel) AnotherBossKilled(j int) int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *InteractiveWorldRaidBossGroupExcel) AnotherBossKilledLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *InteractiveWorldRaidBossGroupExcel) MutateAnotherBossKilled(j int, n int64) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt64(a+flatbuffers.UOffsetT(j*8), n)
	}
	return false
}

func (rcv *InteractiveWorldRaidBossGroupExcel) EchelonConstraintGroupId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *InteractiveWorldRaidBossGroupExcel) MutateEchelonConstraintGroupId(n int64) bool {
	return rcv._tab.MutateInt64Slot(32, n)
}

func (rcv *InteractiveWorldRaidBossGroupExcel) ExclusiveOperatorBossSpawn() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(34))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *InteractiveWorldRaidBossGroupExcel) ExclusiveOperatorBossKill() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(36))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *InteractiveWorldRaidBossGroupExcel) ExclusiveOperatorScenarioBattle() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(38))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *InteractiveWorldRaidBossGroupExcel) ExclusiveOperatorBossDamaged() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(40))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *InteractiveWorldRaidBossGroupExcel) BossGroupOpenCondition() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(42))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *InteractiveWorldRaidBossGroupExcel) MutateBossGroupOpenCondition(n int64) bool {
	return rcv._tab.MutateInt64Slot(42, n)
}

func (rcv *InteractiveWorldRaidBossGroupExcel) RaidScenarioBattleLocalizeKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(44))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func InteractiveWorldRaidBossGroupExcelStart(builder *flatbuffers.Builder) {
	builder.StartObject(21)
}
func InteractiveWorldRaidBossGroupExcelAddId(builder *flatbuffers.Builder, id int64) {
	builder.PrependInt64Slot(0, id, 0)
}
func InteractiveWorldRaidBossGroupExcelAddWorldRaidBossGroupId(builder *flatbuffers.Builder, worldRaidBossGroupId int64) {
	builder.PrependInt64Slot(1, worldRaidBossGroupId, 0)
}
func InteractiveWorldRaidBossGroupExcelAddWorldBossHpLinkGroup(builder *flatbuffers.Builder, worldBossHpLinkGroup int64) {
	builder.PrependInt64Slot(2, worldBossHpLinkGroup, 0)
}
func InteractiveWorldRaidBossGroupExcelAddWorldBossName(builder *flatbuffers.Builder, worldBossName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(worldBossName), 0)
}
func InteractiveWorldRaidBossGroupExcelAddWorldBossPopupPortrait(builder *flatbuffers.Builder, worldBossPopupPortrait flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(worldBossPopupPortrait), 0)
}
func InteractiveWorldRaidBossGroupExcelAddWorldBossPopupNameTexture(builder *flatbuffers.Builder, worldBossPopupNameTexture flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(worldBossPopupNameTexture), 0)
}
func InteractiveWorldRaidBossGroupExcelAddWorldBossPopupBg(builder *flatbuffers.Builder, worldBossPopupBg flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(worldBossPopupBg), 0)
}
func InteractiveWorldRaidBossGroupExcelAddWorldBossParcelPortrait(builder *flatbuffers.Builder, worldBossParcelPortrait flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(worldBossParcelPortrait), 0)
}
func InteractiveWorldRaidBossGroupExcelAddWorldBossListParcel(builder *flatbuffers.Builder, worldBossListParcel flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(worldBossListParcel), 0)
}
func InteractiveWorldRaidBossGroupExcelAddWorldBossHp(builder *flatbuffers.Builder, worldBossHp int64) {
	builder.PrependInt64Slot(9, worldBossHp, 0)
}
func InteractiveWorldRaidBossGroupExcelAddUiHideBeforeSpawn(builder *flatbuffers.Builder, uiHideBeforeSpawn bool) {
	builder.PrependBoolSlot(10, uiHideBeforeSpawn, false)
}
func InteractiveWorldRaidBossGroupExcelAddHideAnotherBossKilled(builder *flatbuffers.Builder, hideAnotherBossKilled bool) {
	builder.PrependBoolSlot(11, hideAnotherBossKilled, false)
}
func InteractiveWorldRaidBossGroupExcelAddWorldBossClearRewardGroupId(builder *flatbuffers.Builder, worldBossClearRewardGroupId int64) {
	builder.PrependInt64Slot(12, worldBossClearRewardGroupId, 0)
}
func InteractiveWorldRaidBossGroupExcelAddAnotherBossKilled(builder *flatbuffers.Builder, anotherBossKilled flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(13, flatbuffers.UOffsetT(anotherBossKilled), 0)
}
func InteractiveWorldRaidBossGroupExcelStartAnotherBossKilledVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func InteractiveWorldRaidBossGroupExcelAddEchelonConstraintGroupId(builder *flatbuffers.Builder, echelonConstraintGroupId int64) {
	builder.PrependInt64Slot(14, echelonConstraintGroupId, 0)
}
func InteractiveWorldRaidBossGroupExcelAddExclusiveOperatorBossSpawn(builder *flatbuffers.Builder, exclusiveOperatorBossSpawn flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(15, flatbuffers.UOffsetT(exclusiveOperatorBossSpawn), 0)
}
func InteractiveWorldRaidBossGroupExcelAddExclusiveOperatorBossKill(builder *flatbuffers.Builder, exclusiveOperatorBossKill flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(16, flatbuffers.UOffsetT(exclusiveOperatorBossKill), 0)
}
func InteractiveWorldRaidBossGroupExcelAddExclusiveOperatorScenarioBattle(builder *flatbuffers.Builder, exclusiveOperatorScenarioBattle flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(17, flatbuffers.UOffsetT(exclusiveOperatorScenarioBattle), 0)
}
func InteractiveWorldRaidBossGroupExcelAddExclusiveOperatorBossDamaged(builder *flatbuffers.Builder, exclusiveOperatorBossDamaged flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(18, flatbuffers.UOffsetT(exclusiveOperatorBossDamaged), 0)
}
func InteractiveWorldRaidBossGroupExcelAddBossGroupOpenCondition(builder *flatbuffers.Builder, bossGroupOpenCondition int64) {
	builder.PrependInt64Slot(19, bossGroupOpenCondition, 0)
}
func InteractiveWorldRaidBossGroupExcelAddRaidScenarioBattleLocalizeKey(builder *flatbuffers.Builder, raidScenarioBattleLocalizeKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(20, flatbuffers.UOffsetT(raidScenarioBattleLocalizeKey), 0)
}
func InteractiveWorldRaidBossGroupExcelEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
