// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package excel

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LocalizeSkillExcel struct {
	_tab flatbuffers.Table
}

func GetRootAsLocalizeSkillExcel(buf []byte, offset flatbuffers.UOffsetT) *LocalizeSkillExcel {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LocalizeSkillExcel{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsLocalizeSkillExcel(buf []byte, offset flatbuffers.UOffsetT) *LocalizeSkillExcel {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LocalizeSkillExcel{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *LocalizeSkillExcel) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LocalizeSkillExcel) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LocalizeSkillExcel) DescriptionJp() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LocalizeSkillExcel) DescriptionKr() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LocalizeSkillExcel) Key() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *LocalizeSkillExcel) MutateKey(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func (rcv *LocalizeSkillExcel) NameJp() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LocalizeSkillExcel) NameKr() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LocalizeSkillExcel) SkillInvokeLocalizeJp() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LocalizeSkillExcel) SkillInvokeLocalizeKr() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func LocalizeSkillExcelStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func LocalizeSkillExcelAddDescriptionJp(builder *flatbuffers.Builder, descriptionJp flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(descriptionJp), 0)
}
func LocalizeSkillExcelAddDescriptionKr(builder *flatbuffers.Builder, descriptionKr flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(descriptionKr), 0)
}
func LocalizeSkillExcelAddKey(builder *flatbuffers.Builder, key uint32) {
	builder.PrependUint32Slot(2, key, 0)
}
func LocalizeSkillExcelAddNameJp(builder *flatbuffers.Builder, nameJp flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(nameJp), 0)
}
func LocalizeSkillExcelAddNameKr(builder *flatbuffers.Builder, nameKr flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(nameKr), 0)
}
func LocalizeSkillExcelAddSkillInvokeLocalizeJp(builder *flatbuffers.Builder, skillInvokeLocalizeJp flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(skillInvokeLocalizeJp), 0)
}
func LocalizeSkillExcelAddSkillInvokeLocalizeKr(builder *flatbuffers.Builder, skillInvokeLocalizeKr flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(skillInvokeLocalizeKr), 0)
}
func LocalizeSkillExcelEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
