// Code generated by fbsgen. DO NOT EDIT.
// Package excel contains generated code for a FlatBuffers schema.
package excel

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// MiniGamePlayGuideExcelDto represents a FlatBuffers table.
type MiniGamePlayGuideExcelDto struct {
	fbsutils.FlatBuffer
	ID             int64            `json:"id"`
	EventContentID int64            `json:"event_content_id"`
	MiniGameType   EventContentType `json:"mini_game_type"`
	IsPcBuild      bool             `json:"is_pc_build"`
	DisplayOrder   int32            `json:"display_order"`
	GuideTitle     string           `json:"guide_title"`
	GuideImagePath string           `json:"guide_image_path"`
	GuideText      string           `json:"guide_text"`
}

// MarshalModel marshals the struct into a FlatBuffers offset.
func (t *MiniGamePlayGuideExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	guideTitleOffset := b.CreateString(t.GuideTitle)
	guideImagePathOffset := b.CreateString(t.GuideImagePath)
	guideTextOffset := b.CreateString(t.GuideText)
	MiniGamePlayGuideExcelStart(b)
	MiniGamePlayGuideExcelAddId(b, t.ID)
	MiniGamePlayGuideExcelAddEventContentId(b, t.EventContentID)
	MiniGamePlayGuideExcelAddMiniGameType(b, t.MiniGameType)
	MiniGamePlayGuideExcelAddIsPcBuild(b, t.IsPcBuild)
	MiniGamePlayGuideExcelAddDisplayOrder(b, t.DisplayOrder)
	MiniGamePlayGuideExcelAddGuideTitle(b, guideTitleOffset)
	MiniGamePlayGuideExcelAddGuideImagePath(b, guideImagePathOffset)
	MiniGamePlayGuideExcelAddGuideText(b, guideTextOffset)
	return MiniGamePlayGuideExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer.
func (t *MiniGamePlayGuideExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers table.
func (t *MiniGamePlayGuideExcelDto) UnmarshalMessage(e *MiniGamePlayGuideExcel) error {
	t.ID = e.Id()
	t.EventContentID = e.EventContentId()
	t.MiniGameType = e.MiniGameType()
	t.IsPcBuild = e.IsPcBuild()
	t.DisplayOrder = e.DisplayOrder()
	t.GuideTitle = string(e.GuideTitle())
	t.GuideImagePath = string(e.GuideImagePath())
	t.GuideText = string(e.GuideText())
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer.
func (t *MiniGamePlayGuideExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsMiniGamePlayGuideExcel(data, 0)
	return t.UnmarshalMessage(root)
}

// FlatDataName returns the FlatBuffers table name.
func (MiniGamePlayGuideExcelDto) FlatDataName() string {
	return "MiniGamePlayGuideExcel"
}
