// Code generated by fbsgen. DO NOT EDIT.
// Package excel contains generated code for a FlatBuffers schema.
package excel

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// MinigameCCGLogicEffectExcelDto represents a FlatBuffers table.
type MinigameCCGLogicEffectExcelDto struct {
	fbsutils.FlatBuffer
	ID           int64  `json:"id"`
	DataLoadPath string `json:"data_load_path"`
	Icon         string `json:"icon"`
}

// MarshalModel marshals the struct into a FlatBuffers offset.
func (t *MinigameCCGLogicEffectExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	dataLoadPathOffset := b.CreateString(t.DataLoadPath)
	iconOffset := b.CreateString(t.Icon)
	MinigameCCGLogicEffectExcelStart(b)
	MinigameCCGLogicEffectExcelAddId(b, t.ID)
	MinigameCCGLogicEffectExcelAddDataLoadPath(b, dataLoadPathOffset)
	MinigameCCGLogicEffectExcelAddIcon(b, iconOffset)
	return MinigameCCGLogicEffectExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer.
func (t *MinigameCCGLogicEffectExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers table.
func (t *MinigameCCGLogicEffectExcelDto) UnmarshalMessage(e *MinigameCCGLogicEffectExcel) error {
	t.ID = e.Id()
	t.DataLoadPath = string(e.DataLoadPath())
	t.Icon = string(e.Icon())
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer.
func (t *MinigameCCGLogicEffectExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsMinigameCCGLogicEffectExcel(data, 0)
	return t.UnmarshalMessage(root)
}

// FlatDataName returns the FlatBuffers table name.
func (MinigameCCGLogicEffectExcelDto) FlatDataName() string {
	return "MinigameCCGLogicEffectExcel"
}
