// Code generated by fbsgen. DO NOT EDIT.
// Package excel contains generated code for a FlatBuffers schema.
package excel

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// MinigameCCGRewardCardRateExcelDto represents a FlatBuffers table.
type MinigameCCGRewardCardRateExcelDto struct {
	fbsutils.FlatBuffer
	RarityGroupID int64 `json:"rarity_group_id"`
	CardRarity    int32 `json:"card_rarity"`
	Rate          int32 `json:"rate"`
}

// MarshalModel marshals the struct into a FlatBuffers offset.
func (t *MinigameCCGRewardCardRateExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	MinigameCCGRewardCardRateExcelStart(b)
	MinigameCCGRewardCardRateExcelAddRarityGroupId(b, t.RarityGroupID)
	MinigameCCGRewardCardRateExcelAddCardRarity(b, t.CardRarity)
	MinigameCCGRewardCardRateExcelAddRate(b, t.Rate)
	return MinigameCCGRewardCardRateExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer.
func (t *MinigameCCGRewardCardRateExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers table.
func (t *MinigameCCGRewardCardRateExcelDto) UnmarshalMessage(e *MinigameCCGRewardCardRateExcel) error {
	t.RarityGroupID = e.RarityGroupId()
	t.CardRarity = e.CardRarity()
	t.Rate = e.Rate()
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer.
func (t *MinigameCCGRewardCardRateExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsMinigameCCGRewardCardRateExcel(data, 0)
	return t.UnmarshalMessage(root)
}

// FlatDataName returns the FlatBuffers table name.
func (MinigameCCGRewardCardRateExcelDto) FlatDataName() string {
	return "MinigameCCGRewardCardRateExcel"
}
