// Code generated by fbsgen. DO NOT EDIT.
// Package excel contains generated code for FlatBuffers schema
package excel

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// MomotalkScheduleSpoilerPopupExcelDto represents a FlatBuffers table
type MomotalkScheduleSpoilerPopupExcelDto struct {
	fbsutils.FlatBuffer
	FavorScheduleId         int64            `json:"favor_schedule_id"`
	SpoilerPopupTitle       uint32           `json:"spoiler_popup_title"`
	SpoilerPopupDescription uint32           `json:"spoiler_popup_description"`
	PopupType               SpoilerPopupType `json:"popup_type"`
	ConditionScenarioModeId int64            `json:"condition_scenario_mode_id"`
}

// MarshalModel marshals the struct into flatbuffers offset
func (t *MomotalkScheduleSpoilerPopupExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	MomotalkScheduleSpoilerPopupExcelStart(b)
	MomotalkScheduleSpoilerPopupExcelAddFavorScheduleId(b, fbsutils.Convert(t.FavorScheduleId, t.FlatBuffer.TableKey))
	MomotalkScheduleSpoilerPopupExcelAddSpoilerPopupTitle(b, fbsutils.Convert(t.SpoilerPopupTitle, t.FlatBuffer.TableKey))
	MomotalkScheduleSpoilerPopupExcelAddSpoilerPopupDescription(b, fbsutils.Convert(t.SpoilerPopupDescription, t.FlatBuffer.TableKey))
	MomotalkScheduleSpoilerPopupExcelAddPopupType(b, fbsutils.Convert(t.PopupType, t.FlatBuffer.TableKey))
	MomotalkScheduleSpoilerPopupExcelAddConditionScenarioModeId(b, fbsutils.Convert(t.ConditionScenarioModeId, t.FlatBuffer.TableKey))
	return MomotalkScheduleSpoilerPopupExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer
func (t *MomotalkScheduleSpoilerPopupExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers buffer
func (t *MomotalkScheduleSpoilerPopupExcelDto) UnmarshalMessage(e *MomotalkScheduleSpoilerPopupExcel) error {
	t.FavorScheduleId = fbsutils.Convert(e.FavorScheduleId(), t.FlatBuffer.TableKey)
	t.SpoilerPopupTitle = fbsutils.Convert(e.SpoilerPopupTitle(), t.FlatBuffer.TableKey)
	t.SpoilerPopupDescription = fbsutils.Convert(e.SpoilerPopupDescription(), t.FlatBuffer.TableKey)
	t.PopupType = SpoilerPopupType(fbsutils.Convert(int32(e.PopupType()), t.FlatBuffer.TableKey))
	t.ConditionScenarioModeId = fbsutils.Convert(e.ConditionScenarioModeId(), t.FlatBuffer.TableKey)
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer
func (t *MomotalkScheduleSpoilerPopupExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsMomotalkScheduleSpoilerPopupExcel(data, 0)
	err := t.UnmarshalMessage(root)
	if err != nil {
		return err
	}
	return nil
}

// Name returns the name of the flatbuffer table name
func (MomotalkScheduleSpoilerPopupExcelDto) FlatDataName() string {
	return "MomotalkScheduleSpoilerPopupExcel"
}
