// Code generated by fbsgen. DO NOT EDIT.
// Package excel contains generated code for a FlatBuffers schema.
package excel

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// ProductSelectExcelDto represents a FlatBuffers table.
type ProductSelectExcelDto struct {
	fbsutils.FlatBuffer
	ID                   int64                `json:"id"`
	ProductSelectSubType ProductSelectSubType `json:"product_select_sub_type"`
	AutoSelectPopupType  AutoSelectPopupType  `json:"auto_select_popup_type"`
	ProductID            string               `json:"product_id"`
	StoreType            StoreType            `json:"store_type"`
	Price                int64                `json:"price"`
	PriceReference       string               `json:"price_reference"`
	PurchasePeriodType   PurchasePeriodType   `json:"purchase_period_type"`
	PurchasePeriodLimit  int64                `json:"purchase_period_limit"`
	ParcelType           []ParcelType         `json:"parcel_type"`
	ParcelID             []int64              `json:"parcel_id"`
	ParcelAmount         []int64              `json:"parcel_amount"`
	ProductSelectionSlot []int64              `json:"product_selection_slot"`
}

// MarshalModel marshals the struct into a FlatBuffers offset.
func (t *ProductSelectExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	productIDOffset := b.CreateString(t.ProductID)
	priceReferenceOffset := b.CreateString(t.PriceReference)
	ProductSelectExcelStartParcelTypeVector(b, len(t.ParcelType))
	for i := len(t.ParcelType) - 1; i >= 0; i-- {
		b.PrependInt32(int32(t.ParcelType[i]))
	}
	parcelTypeOffset := b.EndVector(len(t.ParcelType))
	ProductSelectExcelStartParcelIdVector(b, len(t.ParcelID))
	for i := len(t.ParcelID) - 1; i >= 0; i-- {
		b.PrependInt64(t.ParcelID[i])
	}
	parcelIDOffset := b.EndVector(len(t.ParcelID))
	ProductSelectExcelStartParcelAmountVector(b, len(t.ParcelAmount))
	for i := len(t.ParcelAmount) - 1; i >= 0; i-- {
		b.PrependInt64(t.ParcelAmount[i])
	}
	parcelAmountOffset := b.EndVector(len(t.ParcelAmount))
	ProductSelectExcelStartProductSelectionSlotVector(b, len(t.ProductSelectionSlot))
	for i := len(t.ProductSelectionSlot) - 1; i >= 0; i-- {
		b.PrependInt64(t.ProductSelectionSlot[i])
	}
	productSelectionSlotOffset := b.EndVector(len(t.ProductSelectionSlot))
	ProductSelectExcelStart(b)
	ProductSelectExcelAddId(b, t.ID)
	ProductSelectExcelAddProductSelectSubType(b, t.ProductSelectSubType)
	ProductSelectExcelAddAutoSelectPopupType(b, t.AutoSelectPopupType)
	ProductSelectExcelAddProductId(b, productIDOffset)
	ProductSelectExcelAddStoreType(b, t.StoreType)
	ProductSelectExcelAddPrice(b, t.Price)
	ProductSelectExcelAddPriceReference(b, priceReferenceOffset)
	ProductSelectExcelAddPurchasePeriodType(b, t.PurchasePeriodType)
	ProductSelectExcelAddPurchasePeriodLimit(b, t.PurchasePeriodLimit)
	ProductSelectExcelAddParcelType(b, parcelTypeOffset)
	ProductSelectExcelAddParcelId(b, parcelIDOffset)
	ProductSelectExcelAddParcelAmount(b, parcelAmountOffset)
	ProductSelectExcelAddProductSelectionSlot(b, productSelectionSlotOffset)
	return ProductSelectExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer.
func (t *ProductSelectExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers table.
func (t *ProductSelectExcelDto) UnmarshalMessage(e *ProductSelectExcel) error {
	t.ID = e.Id()
	t.ProductSelectSubType = e.ProductSelectSubType()
	t.AutoSelectPopupType = e.AutoSelectPopupType()
	t.ProductID = string(e.ProductId())
	t.StoreType = e.StoreType()
	t.Price = e.Price()
	t.PriceReference = string(e.PriceReference())
	t.PurchasePeriodType = e.PurchasePeriodType()
	t.PurchasePeriodLimit = e.PurchasePeriodLimit()
	t.ParcelType = make([]ParcelType, e.ParcelTypeLength())
	for i := 0; i < e.ParcelTypeLength(); i++ {
		t.ParcelType[i] = e.ParcelType(i)
	}
	t.ParcelID = make([]int64, e.ParcelIdLength())
	for i := 0; i < e.ParcelIdLength(); i++ {
		t.ParcelID[i] = e.ParcelId(i)
	}
	t.ParcelAmount = make([]int64, e.ParcelAmountLength())
	for i := 0; i < e.ParcelAmountLength(); i++ {
		t.ParcelAmount[i] = e.ParcelAmount(i)
	}
	t.ProductSelectionSlot = make([]int64, e.ProductSelectionSlotLength())
	for i := 0; i < e.ProductSelectionSlotLength(); i++ {
		t.ProductSelectionSlot[i] = e.ProductSelectionSlot(i)
	}
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer.
func (t *ProductSelectExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsProductSelectExcel(data, 0)
	return t.UnmarshalMessage(root)
}

// FlatDataName returns the FlatBuffers table name.
func (ProductSelectExcelDto) FlatDataName() string {
	return "ProductSelectExcel"
}
