// Code generated by fbsgen. DO NOT EDIT.
// Package excel contains generated code for a FlatBuffers schema.
package excel

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// RaidStageSeasonRewardExcelDto represents a FlatBuffers table.
type RaidStageSeasonRewardExcelDto struct {
	fbsutils.FlatBuffer
	SeasonRewardID             int64        `json:"season_reward_id"`
	SeasonRewardParcelType     []ParcelType `json:"season_reward_parcel_type"`
	SeasonRewardParcelUniqueID []int64      `json:"season_reward_parcel_unique_id"`
	SeasonRewardAmount         []int64      `json:"season_reward_amount"`
}

// MarshalModel marshals the struct into a FlatBuffers offset.
func (t *RaidStageSeasonRewardExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	RaidStageSeasonRewardExcelStartSeasonRewardParcelTypeVector(b, len(t.SeasonRewardParcelType))
	for i := len(t.SeasonRewardParcelType) - 1; i >= 0; i-- {
		b.PrependInt32(int32(t.SeasonRewardParcelType[i]))
	}
	seasonRewardParcelTypeOffset := b.EndVector(len(t.SeasonRewardParcelType))
	RaidStageSeasonRewardExcelStartSeasonRewardParcelUniqueIdVector(b, len(t.SeasonRewardParcelUniqueID))
	for i := len(t.SeasonRewardParcelUniqueID) - 1; i >= 0; i-- {
		b.PrependInt64(t.SeasonRewardParcelUniqueID[i])
	}
	seasonRewardParcelUniqueIDOffset := b.EndVector(len(t.SeasonRewardParcelUniqueID))
	RaidStageSeasonRewardExcelStartSeasonRewardAmountVector(b, len(t.SeasonRewardAmount))
	for i := len(t.SeasonRewardAmount) - 1; i >= 0; i-- {
		b.PrependInt64(t.SeasonRewardAmount[i])
	}
	seasonRewardAmountOffset := b.EndVector(len(t.SeasonRewardAmount))
	RaidStageSeasonRewardExcelStart(b)
	RaidStageSeasonRewardExcelAddSeasonRewardId(b, t.SeasonRewardID)
	RaidStageSeasonRewardExcelAddSeasonRewardParcelType(b, seasonRewardParcelTypeOffset)
	RaidStageSeasonRewardExcelAddSeasonRewardParcelUniqueId(b, seasonRewardParcelUniqueIDOffset)
	RaidStageSeasonRewardExcelAddSeasonRewardAmount(b, seasonRewardAmountOffset)
	return RaidStageSeasonRewardExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer.
func (t *RaidStageSeasonRewardExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers table.
func (t *RaidStageSeasonRewardExcelDto) UnmarshalMessage(e *RaidStageSeasonRewardExcel) error {
	t.SeasonRewardID = e.SeasonRewardId()
	t.SeasonRewardParcelType = make([]ParcelType, e.SeasonRewardParcelTypeLength())
	for i := 0; i < e.SeasonRewardParcelTypeLength(); i++ {
		t.SeasonRewardParcelType[i] = e.SeasonRewardParcelType(i)
	}
	t.SeasonRewardParcelUniqueID = make([]int64, e.SeasonRewardParcelUniqueIdLength())
	for i := 0; i < e.SeasonRewardParcelUniqueIdLength(); i++ {
		t.SeasonRewardParcelUniqueID[i] = e.SeasonRewardParcelUniqueId(i)
	}
	t.SeasonRewardAmount = make([]int64, e.SeasonRewardAmountLength())
	for i := 0; i < e.SeasonRewardAmountLength(); i++ {
		t.SeasonRewardAmount[i] = e.SeasonRewardAmount(i)
	}
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer.
func (t *RaidStageSeasonRewardExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsRaidStageSeasonRewardExcel(data, 0)
	return t.UnmarshalMessage(root)
}

// FlatDataName returns the FlatBuffers table name.
func (RaidStageSeasonRewardExcelDto) FlatDataName() string {
	return "RaidStageSeasonRewardExcel"
}
