// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package excel

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ScenarioContentCollectionExcel struct {
	_tab flatbuffers.Table
}

func GetRootAsScenarioContentCollectionExcel(buf []byte, offset flatbuffers.UOffsetT) *ScenarioContentCollectionExcel {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ScenarioContentCollectionExcel{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsScenarioContentCollectionExcel(buf []byte, offset flatbuffers.UOffsetT) *ScenarioContentCollectionExcel {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ScenarioContentCollectionExcel{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ScenarioContentCollectionExcel) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ScenarioContentCollectionExcel) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ScenarioContentCollectionExcel) EmblemResource() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ScenarioContentCollectionExcel) FullResource() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ScenarioContentCollectionExcel) GroupId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ScenarioContentCollectionExcel) MutateGroupId(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func (rcv *ScenarioContentCollectionExcel) Id() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ScenarioContentCollectionExcel) MutateId(n int64) bool {
	return rcv._tab.MutateInt64Slot(10, n)
}

func (rcv *ScenarioContentCollectionExcel) IsHorizon() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ScenarioContentCollectionExcel) MutateIsHorizon(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func (rcv *ScenarioContentCollectionExcel) IsObject() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ScenarioContentCollectionExcel) MutateIsObject(n bool) bool {
	return rcv._tab.MutateBoolSlot(14, n)
}

func (rcv *ScenarioContentCollectionExcel) LocalizeEtcId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ScenarioContentCollectionExcel) MutateLocalizeEtcId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(16, n)
}

func (rcv *ScenarioContentCollectionExcel) MultipleConditionCheckType() MultipleConditionCheckType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return MultipleConditionCheckType(rcv._tab.GetInt32(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ScenarioContentCollectionExcel) MutateMultipleConditionCheckType(n MultipleConditionCheckType) bool {
	return rcv._tab.MutateInt32Slot(18, int32(n))
}

func (rcv *ScenarioContentCollectionExcel) SubNameLocalizeCodeId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ScenarioContentCollectionExcel) ThumbResource() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ScenarioContentCollectionExcel) UnlockConditionCount() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ScenarioContentCollectionExcel) MutateUnlockConditionCount(n int64) bool {
	return rcv._tab.MutateInt64Slot(24, n)
}

func (rcv *ScenarioContentCollectionExcel) UnlockConditionParameter(j int) int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *ScenarioContentCollectionExcel) UnlockConditionParameterLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ScenarioContentCollectionExcel) MutateUnlockConditionParameter(j int, n int64) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt64(a+flatbuffers.UOffsetT(j*8), n)
	}
	return false
}

func (rcv *ScenarioContentCollectionExcel) UnlockConditionType() CollectionUnlockType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return CollectionUnlockType(rcv._tab.GetInt32(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ScenarioContentCollectionExcel) MutateUnlockConditionType(n CollectionUnlockType) bool {
	return rcv._tab.MutateInt32Slot(28, int32(n))
}

func ScenarioContentCollectionExcelStart(builder *flatbuffers.Builder) {
	builder.StartObject(13)
}
func ScenarioContentCollectionExcelAddEmblemResource(builder *flatbuffers.Builder, emblemResource flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(emblemResource), 0)
}
func ScenarioContentCollectionExcelAddFullResource(builder *flatbuffers.Builder, fullResource flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(fullResource), 0)
}
func ScenarioContentCollectionExcelAddGroupId(builder *flatbuffers.Builder, groupId int64) {
	builder.PrependInt64Slot(2, groupId, 0)
}
func ScenarioContentCollectionExcelAddId(builder *flatbuffers.Builder, id int64) {
	builder.PrependInt64Slot(3, id, 0)
}
func ScenarioContentCollectionExcelAddIsHorizon(builder *flatbuffers.Builder, isHorizon bool) {
	builder.PrependBoolSlot(4, isHorizon, false)
}
func ScenarioContentCollectionExcelAddIsObject(builder *flatbuffers.Builder, isObject bool) {
	builder.PrependBoolSlot(5, isObject, false)
}
func ScenarioContentCollectionExcelAddLocalizeEtcId(builder *flatbuffers.Builder, localizeEtcId uint32) {
	builder.PrependUint32Slot(6, localizeEtcId, 0)
}
func ScenarioContentCollectionExcelAddMultipleConditionCheckType(builder *flatbuffers.Builder, multipleConditionCheckType MultipleConditionCheckType) {
	builder.PrependInt32Slot(7, int32(multipleConditionCheckType), 0)
}
func ScenarioContentCollectionExcelAddSubNameLocalizeCodeId(builder *flatbuffers.Builder, subNameLocalizeCodeId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(subNameLocalizeCodeId), 0)
}
func ScenarioContentCollectionExcelAddThumbResource(builder *flatbuffers.Builder, thumbResource flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(thumbResource), 0)
}
func ScenarioContentCollectionExcelAddUnlockConditionCount(builder *flatbuffers.Builder, unlockConditionCount int64) {
	builder.PrependInt64Slot(10, unlockConditionCount, 0)
}
func ScenarioContentCollectionExcelAddUnlockConditionParameter(builder *flatbuffers.Builder, unlockConditionParameter flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(11, flatbuffers.UOffsetT(unlockConditionParameter), 0)
}
func ScenarioContentCollectionExcelStartUnlockConditionParameterVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func ScenarioContentCollectionExcelAddUnlockConditionType(builder *flatbuffers.Builder, unlockConditionType CollectionUnlockType) {
	builder.PrependInt32Slot(12, int32(unlockConditionType), 0)
}
func ScenarioContentCollectionExcelEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
