// Code generated by fbsgen. DO NOT EDIT.
// Package excel contains generated code for FlatBuffers schema
package excel

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// ScenarioCharacterEmotionExcelDto represents a FlatBuffers table
type ScenarioCharacterEmotionExcelDto struct {
	fbsutils.FlatBuffer
	Name         uint32 `json:"name"`
	EmoticonName string `json:"emoticon_name"`
}

// MarshalModel marshals the struct into flatbuffers offset
func (t *ScenarioCharacterEmotionExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	ScenarioCharacterEmotionExcelStart(b)
	ScenarioCharacterEmotionExcelAddName(b, fbsutils.Convert(t.Name, t.FlatBuffer.TableKey))
	ScenarioCharacterEmotionExcelAddEmoticonName(b, b.CreateString(fbsutils.Convert(t.EmoticonName, t.FlatBuffer.TableKey)))
	return ScenarioCharacterEmotionExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer
func (t *ScenarioCharacterEmotionExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers buffer
func (t *ScenarioCharacterEmotionExcelDto) UnmarshalMessage(e *ScenarioCharacterEmotionExcel) error {
	t.Name = fbsutils.Convert(e.Name(), t.FlatBuffer.TableKey)
	t.EmoticonName = fbsutils.Convert(string(e.EmoticonName()), t.FlatBuffer.TableKey)
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer
func (t *ScenarioCharacterEmotionExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsScenarioCharacterEmotionExcel(data, 0)
	err := t.UnmarshalMessage(root)
	if err != nil {
		return err
	}
	return nil
}

// Name returns the name of the flatbuffer table name
func (ScenarioCharacterEmotionExcelDto) FlatDataName() string {
	return "ScenarioCharacterEmotionExcel"
}
