// Code generated by fbsgen. DO NOT EDIT.
// Package excel contains generated code for FlatBuffers schema
package excel

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// ShopFreeRecruitPeriodExcelDto represents a FlatBuffers table
type ShopFreeRecruitPeriodExcelDto struct {
	fbsutils.FlatBuffer
	FreeRecruitCount          int32  `json:"free_recruit_count"`
	IntervalDate              string `json:"interval_date"`
	ShopFreeRecruitId         int64  `json:"shop_free_recruit_id"`
	ShopFreeRecruitIntervalId int64  `json:"shop_free_recruit_interval_id"`
}

// MarshalModel marshals the struct into flatbuffers offset
func (t *ShopFreeRecruitPeriodExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	ShopFreeRecruitPeriodExcelStart(b)
	ShopFreeRecruitPeriodExcelAddFreeRecruitCount(b, fbsutils.Convert(t.FreeRecruitCount, t.FlatBuffer.TableKey))
	ShopFreeRecruitPeriodExcelAddIntervalDate(b, b.CreateString(fbsutils.Convert(t.IntervalDate, t.FlatBuffer.TableKey)))
	ShopFreeRecruitPeriodExcelAddShopFreeRecruitId(b, fbsutils.Convert(t.ShopFreeRecruitId, t.FlatBuffer.TableKey))
	ShopFreeRecruitPeriodExcelAddShopFreeRecruitIntervalId(b, fbsutils.Convert(t.ShopFreeRecruitIntervalId, t.FlatBuffer.TableKey))
	return ShopFreeRecruitPeriodExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer
func (t *ShopFreeRecruitPeriodExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers buffer
func (t *ShopFreeRecruitPeriodExcelDto) UnmarshalMessage(e *ShopFreeRecruitPeriodExcel) error {
	t.FreeRecruitCount = fbsutils.Convert(e.FreeRecruitCount(), t.FlatBuffer.TableKey)
	t.IntervalDate = fbsutils.Convert(string(e.IntervalDate()), t.FlatBuffer.TableKey)
	t.ShopFreeRecruitId = fbsutils.Convert(e.ShopFreeRecruitId(), t.FlatBuffer.TableKey)
	t.ShopFreeRecruitIntervalId = fbsutils.Convert(e.ShopFreeRecruitIntervalId(), t.FlatBuffer.TableKey)
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer
func (t *ShopFreeRecruitPeriodExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsShopFreeRecruitPeriodExcel(data, 0)
	err := t.UnmarshalMessage(root)
	if err != nil {
		return err
	}
	return nil
}

// Name returns the name of the flatbuffer table name
func (ShopFreeRecruitPeriodExcelDto) FlatDataName() string {
	return "ShopFreeRecruitPeriodExcel"
}
