// Code generated by fbsgen. DO NOT EDIT.
// Package excel contains generated code for FlatBuffers schema
package excel

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// ShopRecruitDirectingExcelDto represents a FlatBuffers table
type ShopRecruitDirectingExcelDto struct {
	fbsutils.FlatBuffer
	Path        string             `json:"path"`
	Phase       GachaPhase         `json:"phase"`
	GachaAmount int32              `json:"gacha_amount"`
	IsSsr       bool               `json:"is_ssr"`
	Character   DirectingCharacter `json:"character"`
}

// MarshalModel marshals the struct into flatbuffers offset
func (t *ShopRecruitDirectingExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	__offset_path := b.CreateString(fbsutils.Convert(t.Path, t.FlatBuffer.TableKey))
	ShopRecruitDirectingExcelStart(b)
	ShopRecruitDirectingExcelAddPath(b, __offset_path)
	ShopRecruitDirectingExcelAddPhase(b, fbsutils.Convert(t.Phase, t.FlatBuffer.TableKey))
	ShopRecruitDirectingExcelAddGachaAmount(b, fbsutils.Convert(t.GachaAmount, t.FlatBuffer.TableKey))
	ShopRecruitDirectingExcelAddIsSsr(b, t.IsSsr)
	ShopRecruitDirectingExcelAddCharacter(b, fbsutils.Convert(t.Character, t.FlatBuffer.TableKey))
	return ShopRecruitDirectingExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer
func (t *ShopRecruitDirectingExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers buffer
func (t *ShopRecruitDirectingExcelDto) UnmarshalMessage(e *ShopRecruitDirectingExcel) error {
	t.Path = fbsutils.Convert(string(e.Path()), t.FlatBuffer.TableKey)
	t.Phase = GachaPhase(fbsutils.Convert(int32(e.Phase()), t.FlatBuffer.TableKey))
	t.GachaAmount = fbsutils.Convert(e.GachaAmount(), t.FlatBuffer.TableKey)
	t.IsSsr = e.IsSsr()
	t.Character = DirectingCharacter(fbsutils.Convert(int32(e.Character()), t.FlatBuffer.TableKey))
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer
func (t *ShopRecruitDirectingExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsShopRecruitDirectingExcel(data, 0)
	err := t.UnmarshalMessage(root)
	if err != nil {
		return err
	}
	return nil
}

// Name returns the name of the flatbuffer table name
func (ShopRecruitDirectingExcelDto) FlatDataName() string {
	return "ShopRecruitDirectingExcel"
}
