// Code generated by fbsgen. DO NOT EDIT.
// Package excel contains generated code for a FlatBuffers schema.
package excel

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// ShopInfoExcelDto represents a FlatBuffers table.
type ShopInfoExcelDto struct {
	fbsutils.FlatBuffer
	CategoryType          ShopCategoryType      `json:"category_type"`
	IsRefresh             bool                  `json:"is_refresh"`
	IsSoldOutDimmed       bool                  `json:"is_sold_out_dimmed"`
	CostParcelType        []ParcelType          `json:"cost_parcel_type"`
	CostParcelID          []int64               `json:"cost_parcel_id"`
	AutoRefreshCoolTime   int64                 `json:"auto_refresh_cool_time"`
	ShopRefresherType     ShopRefresherType     `json:"shop_refresher_type"`
	ShopRefreshPeriodType ShopRefreshPeriodType `json:"shop_refresh_period_type"`
	RefreshAbleCount      int64                 `json:"refresh_able_count"`
	GoodsID               []int64               `json:"goods_id"`
	OpenPeriodFrom        string                `json:"open_period_from"`
	OpenPeriodTo          string                `json:"open_period_to"`
	RefreshPeriodBaseTime string                `json:"refresh_period_base_time"`
	ShopProductUpdateTime string                `json:"shop_product_update_time"`
	DisplayParcelType     ParcelType            `json:"display_parcel_type"`
	DisplayParcelID       int64                 `json:"display_parcel_id"`
	IsShopVisible         bool                  `json:"is_shop_visible"`
	DisplayOrder          int32                 `json:"display_order"`
	ShopUpdateDate        int32                 `json:"shop_update_date"`
	ShopUpdateGroupId1    int32                 `json:"shop_update_group_id1"`
	ShopUpdateGroupId2    int32                 `json:"shop_update_group_id2"`
	ShopUpdateGroupId3    int32                 `json:"shop_update_group_id3"`
	ShopUpdateGroupId4    int32                 `json:"shop_update_group_id4"`
	ShopUpdateGroupId5    int32                 `json:"shop_update_group_id5"`
	ShopUpdateGroupId6    int32                 `json:"shop_update_group_id6"`
	ShopUpdateGroupId7    int32                 `json:"shop_update_group_id7"`
	ShopUpdateGroupId8    int32                 `json:"shop_update_group_id8"`
	ShopUpdateGroupId9    int32                 `json:"shop_update_group_id9"`
	ShopUpdateGroupId10   int32                 `json:"shop_update_group_id10"`
	ShopUpdateGroupId11   int32                 `json:"shop_update_group_id11"`
	ShopUpdateGroupId12   int32                 `json:"shop_update_group_id12"`
}

// MarshalModel marshals the struct into a FlatBuffers offset.
func (t *ShopInfoExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	ShopInfoExcelStartCostParcelTypeVector(b, len(t.CostParcelType))
	for i := len(t.CostParcelType) - 1; i >= 0; i-- {
		b.PrependInt32(int32(t.CostParcelType[i]))
	}
	costParcelTypeOffset := b.EndVector(len(t.CostParcelType))
	ShopInfoExcelStartCostParcelIdVector(b, len(t.CostParcelID))
	for i := len(t.CostParcelID) - 1; i >= 0; i-- {
		b.PrependInt64(t.CostParcelID[i])
	}
	costParcelIDOffset := b.EndVector(len(t.CostParcelID))
	ShopInfoExcelStartGoodsIdVector(b, len(t.GoodsID))
	for i := len(t.GoodsID) - 1; i >= 0; i-- {
		b.PrependInt64(t.GoodsID[i])
	}
	goodsIDOffset := b.EndVector(len(t.GoodsID))
	openPeriodFromOffset := b.CreateString(t.OpenPeriodFrom)
	openPeriodToOffset := b.CreateString(t.OpenPeriodTo)
	refreshPeriodBaseTimeOffset := b.CreateString(t.RefreshPeriodBaseTime)
	shopProductUpdateTimeOffset := b.CreateString(t.ShopProductUpdateTime)
	ShopInfoExcelStart(b)
	ShopInfoExcelAddCategoryType(b, t.CategoryType)
	ShopInfoExcelAddIsRefresh(b, t.IsRefresh)
	ShopInfoExcelAddIsSoldOutDimmed(b, t.IsSoldOutDimmed)
	ShopInfoExcelAddCostParcelType(b, costParcelTypeOffset)
	ShopInfoExcelAddCostParcelId(b, costParcelIDOffset)
	ShopInfoExcelAddAutoRefreshCoolTime(b, t.AutoRefreshCoolTime)
	ShopInfoExcelAddShopRefresherType(b, t.ShopRefresherType)
	ShopInfoExcelAddShopRefreshPeriodType(b, t.ShopRefreshPeriodType)
	ShopInfoExcelAddRefreshAbleCount(b, t.RefreshAbleCount)
	ShopInfoExcelAddGoodsId(b, goodsIDOffset)
	ShopInfoExcelAddOpenPeriodFrom(b, openPeriodFromOffset)
	ShopInfoExcelAddOpenPeriodTo(b, openPeriodToOffset)
	ShopInfoExcelAddRefreshPeriodBaseTime(b, refreshPeriodBaseTimeOffset)
	ShopInfoExcelAddShopProductUpdateTime(b, shopProductUpdateTimeOffset)
	ShopInfoExcelAddDisplayParcelType(b, t.DisplayParcelType)
	ShopInfoExcelAddDisplayParcelId(b, t.DisplayParcelID)
	ShopInfoExcelAddIsShopVisible(b, t.IsShopVisible)
	ShopInfoExcelAddDisplayOrder(b, t.DisplayOrder)
	ShopInfoExcelAddShopUpdateDate(b, t.ShopUpdateDate)
	ShopInfoExcelAddShopUpdateGroupId1(b, t.ShopUpdateGroupId1)
	ShopInfoExcelAddShopUpdateGroupId2(b, t.ShopUpdateGroupId2)
	ShopInfoExcelAddShopUpdateGroupId3(b, t.ShopUpdateGroupId3)
	ShopInfoExcelAddShopUpdateGroupId4(b, t.ShopUpdateGroupId4)
	ShopInfoExcelAddShopUpdateGroupId5(b, t.ShopUpdateGroupId5)
	ShopInfoExcelAddShopUpdateGroupId6(b, t.ShopUpdateGroupId6)
	ShopInfoExcelAddShopUpdateGroupId7(b, t.ShopUpdateGroupId7)
	ShopInfoExcelAddShopUpdateGroupId8(b, t.ShopUpdateGroupId8)
	ShopInfoExcelAddShopUpdateGroupId9(b, t.ShopUpdateGroupId9)
	ShopInfoExcelAddShopUpdateGroupId10(b, t.ShopUpdateGroupId10)
	ShopInfoExcelAddShopUpdateGroupId11(b, t.ShopUpdateGroupId11)
	ShopInfoExcelAddShopUpdateGroupId12(b, t.ShopUpdateGroupId12)
	return ShopInfoExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer.
func (t *ShopInfoExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers table.
func (t *ShopInfoExcelDto) UnmarshalMessage(e *ShopInfoExcel) error {
	t.CategoryType = e.CategoryType()
	t.IsRefresh = e.IsRefresh()
	t.IsSoldOutDimmed = e.IsSoldOutDimmed()
	t.CostParcelType = make([]ParcelType, e.CostParcelTypeLength())
	for i := 0; i < e.CostParcelTypeLength(); i++ {
		t.CostParcelType[i] = e.CostParcelType(i)
	}
	t.CostParcelID = make([]int64, e.CostParcelIdLength())
	for i := 0; i < e.CostParcelIdLength(); i++ {
		t.CostParcelID[i] = e.CostParcelId(i)
	}
	t.AutoRefreshCoolTime = e.AutoRefreshCoolTime()
	t.ShopRefresherType = e.ShopRefresherType()
	t.ShopRefreshPeriodType = e.ShopRefreshPeriodType()
	t.RefreshAbleCount = e.RefreshAbleCount()
	t.GoodsID = make([]int64, e.GoodsIdLength())
	for i := 0; i < e.GoodsIdLength(); i++ {
		t.GoodsID[i] = e.GoodsId(i)
	}
	t.OpenPeriodFrom = string(e.OpenPeriodFrom())
	t.OpenPeriodTo = string(e.OpenPeriodTo())
	t.RefreshPeriodBaseTime = string(e.RefreshPeriodBaseTime())
	t.ShopProductUpdateTime = string(e.ShopProductUpdateTime())
	t.DisplayParcelType = e.DisplayParcelType()
	t.DisplayParcelID = e.DisplayParcelId()
	t.IsShopVisible = e.IsShopVisible()
	t.DisplayOrder = e.DisplayOrder()
	t.ShopUpdateDate = e.ShopUpdateDate()
	t.ShopUpdateGroupId1 = e.ShopUpdateGroupId1()
	t.ShopUpdateGroupId2 = e.ShopUpdateGroupId2()
	t.ShopUpdateGroupId3 = e.ShopUpdateGroupId3()
	t.ShopUpdateGroupId4 = e.ShopUpdateGroupId4()
	t.ShopUpdateGroupId5 = e.ShopUpdateGroupId5()
	t.ShopUpdateGroupId6 = e.ShopUpdateGroupId6()
	t.ShopUpdateGroupId7 = e.ShopUpdateGroupId7()
	t.ShopUpdateGroupId8 = e.ShopUpdateGroupId8()
	t.ShopUpdateGroupId9 = e.ShopUpdateGroupId9()
	t.ShopUpdateGroupId10 = e.ShopUpdateGroupId10()
	t.ShopUpdateGroupId11 = e.ShopUpdateGroupId11()
	t.ShopUpdateGroupId12 = e.ShopUpdateGroupId12()
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer.
func (t *ShopInfoExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsShopInfoExcel(data, 0)
	return t.UnmarshalMessage(root)
}

// FlatDataName returns the FlatBuffers table name.
func (ShopInfoExcelDto) FlatDataName() string {
	return "ShopInfoExcel"
}
