// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package excel

import "strconv"

type TacticSpeed int32

const (
	TacticSpeedNone   TacticSpeed = 0
	TacticSpeedSlow   TacticSpeed = 1
	TacticSpeedNormal TacticSpeed = 2
	TacticSpeedFast   TacticSpeed = 3
)

var EnumNamesTacticSpeed = map[TacticSpeed]string{
	TacticSpeedNone:   "None",
	TacticSpeedSlow:   "Slow",
	TacticSpeedNormal: "Normal",
	TacticSpeedFast:   "Fast",
}

var EnumValuesTacticSpeed = map[string]TacticSpeed{
	"None":   TacticSpeedNone,
	"Slow":   TacticSpeedSlow,
	"Normal": TacticSpeedNormal,
	"Fast":   TacticSpeedFast,
}

func (v TacticSpeed) String() string {
	if s, ok := EnumNamesTacticSpeed[v]; ok {
		return s
	}
	return "TacticSpeed(" + strconv.FormatInt(int64(v), 10) + ")"
}
