// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package excel

import "strconv"

type WorldRaidDifficulty int32

const (
	WorldRaidDifficultyNone WorldRaidDifficulty = 0
	WorldRaidDifficultyA    WorldRaidDifficulty = 1
	WorldRaidDifficultyB    WorldRaidDifficulty = 2
	WorldRaidDifficultyC    WorldRaidDifficulty = 3
	WorldRaidDifficultyD    WorldRaidDifficulty = 4
	WorldRaidDifficultyE    WorldRaidDifficulty = 5
	WorldRaidDifficultyF    WorldRaidDifficulty = 6
	WorldRaidDifficultyG    WorldRaidDifficulty = 7
)

var EnumNamesWorldRaidDifficulty = map[WorldRaidDifficulty]string{
	WorldRaidDifficultyNone: "None",
	WorldRaidDifficultyA:    "A",
	WorldRaidDifficultyB:    "B",
	WorldRaidDifficultyC:    "C",
	WorldRaidDifficultyD:    "D",
	WorldRaidDifficultyE:    "E",
	WorldRaidDifficultyF:    "F",
	WorldRaidDifficultyG:    "G",
}

var EnumValuesWorldRaidDifficulty = map[string]WorldRaidDifficulty{
	"None": WorldRaidDifficultyNone,
	"A":    WorldRaidDifficultyA,
	"B":    WorldRaidDifficultyB,
	"C":    WorldRaidDifficultyC,
	"D":    WorldRaidDifficultyD,
	"E":    WorldRaidDifficultyE,
	"F":    WorldRaidDifficultyF,
	"G":    WorldRaidDifficultyG,
}

func (v WorldRaidDifficulty) String() string {
	if s, ok := EnumNamesWorldRaidDifficulty[v]; ok {
		return s
	}
	return "WorldRaidDifficulty(" + strconv.FormatInt(int64(v), 10) + ")"
}
