"""Post-process FlatBuffers Python object APIs for Plana model conversion."""

from __future__ import annotations

import argparse
import ast
from dataclasses import dataclass
import keyword
import os
from pathlib import Path
import re
import sys
import tempfile


_MARKER = "# plana-flatbuffer: object-api conversion"
_RUNTIME_FILE = "_conversion.py"
_HELPER_FILE = "flatdatas_helper.py"
_REQUIRED_MODEL_METHODS = {
    "__init__",
    "InitFromBuf",
    "InitFromPackedBuf",
    "InitFromObj",
    "_UnPack",
    "Pack",
}
_FLAG_CODECS = {
    "Int8Flags": "int8",
    "Uint8Flags": "uint8",
    "Int16Flags": "int16",
    "Uint16Flags": "uint16",
    "Int32Flags": "int32",
    "Uint32Flags": "uint32",
    "Int64Flags": "int64",
    "Uint64Flags": "uint64",
    "Float32Flags": "float32",
    "Float64Flags": "float64",
    "BoolFlags": "bool",
}


class ProcessingError(Exception):
    pass


@dataclass(frozen=True)
class ModelMetadata:
    module: str
    table_name: str
    model_name: str
    fields: tuple[tuple[str, str, bool], ...]


def _normalized_identifier(name: str) -> str:
    return "".join(character for character in name.lower() if character.isalnum())


def _methods(class_node: ast.ClassDef) -> dict[str, ast.FunctionDef]:
    return {
        node.name: node
        for node in class_node.body
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
    }


def _field_names(model_node: ast.ClassDef) -> tuple[str, ...]:
    initializer = _methods(model_node).get("__init__")
    if initializer is None:
        return ()
    fields = []
    for node in ast.walk(initializer):
        if not isinstance(node, ast.Assign):
            continue
        for target in node.targets:
            if (
                isinstance(target, ast.Attribute)
                and isinstance(target.value, ast.Name)
                and target.value.id == "self"
            ):
                fields.append(target.attr)
    return tuple(fields)


def _accessor_codec(method: ast.FunctionDef) -> str | None:
    for node in ast.walk(method):
        if isinstance(node, ast.Attribute) and node.attr in _FLAG_CODECS:
            return _FLAG_CODECS[node.attr]
    for node in ast.walk(method):
        if isinstance(node, ast.Attribute) and node.attr == "String":
            return "string"
    return None


def _sanitize_receiver_collision(source: str) -> str:
    if "# automatically generated by the FlatBuffers compiler" not in source:
        return source

    parameter_pattern = re.compile(
        r"^(?P<indent>[ \t]+)self(?P<default>[ \t]*=[^,\r\n]*,[ \t]*)$",
        re.MULTILINE,
    )
    if parameter_pattern.search(source) is None:
        return source

    sanitized = parameter_pattern.sub(r"\g<indent>self_\g<default>", source)
    sanitized = re.sub(r"\bself\.self\b", "self.self_", sanitized)
    sanitized = re.sub(
        r"^(?P<indent>[ \t]*)self\.self_[ \t]*=[ \t]*self(?P<suffix>[ \t]*(?:#.*)?)$",
        r"\g<indent>self.self_ = self_\g<suffix>",
        sanitized,
        flags=re.MULTILINE,
    )
    return sanitized


def _model_metadata(path: Path, package: str, source: str) -> tuple[ModelMetadata, ...]:
    try:
        compile(source, str(path), "exec")
        tree = ast.parse(source, filename=str(path))
    except SyntaxError as error:
        raise ProcessingError(f"{path}: invalid generated Python: {error}") from error

    classes = {node.name: node for node in tree.body if isinstance(node, ast.ClassDef)}
    metadata = []
    relative_module = path.stem

    for model_name, model_node in classes.items():
        if not model_name.endswith("T"):
            continue
        table_name = model_name[:-1]
        table_node = classes.get(table_name)
        if table_node is None:
            continue

        method_names = set(_methods(model_node))
        if not method_names.intersection(_REQUIRED_MODEL_METHODS):
            continue
        missing = sorted(_REQUIRED_MODEL_METHODS - method_names)
        if missing:
            raise ProcessingError(
                f"{path}: {model_name} is missing generated methods: {', '.join(missing)}"
            )

        table_methods = _methods(table_node)
        accessors = {
            _normalized_identifier(name): (name, method)
            for name, method in table_methods.items()
        }
        fields = []
        for field_name in _field_names(model_node):
            normalized = _normalized_identifier(field_name)
            accessor = accessors.get(normalized)
            if accessor is None:
                raise ProcessingError(
                    f"{path}: cannot match {model_name}.{field_name} to a table accessor"
                )
            accessor_name, accessor_method = accessor
            codec = _accessor_codec(accessor_method)
            if codec is None or codec == "bool":
                continue
            is_vector = _normalized_identifier(accessor_name + "Length") in accessors
            fields.append((field_name, codec, is_vector))

        module = f"{package}.{relative_module}"
        metadata.append(ModelMetadata(module, table_name, model_name, tuple(fields)))

    return tuple(metadata)


def _installation_source(
    source: str, package: str, metadata: tuple[ModelMetadata, ...]
) -> str:
    marker_count = source.count(_MARKER)
    if marker_count > 1:
        raise ProcessingError("generated module contains duplicate conversion markers")
    if marker_count == 1 or not metadata:
        return source

    newline = "\r\n" if "\r\n" in source else "\n"
    additions = [
        _MARKER,
        f"from {package}.{_RUNTIME_FILE[:-3]} import install_object_api as _install_object_api",
    ]
    for model in metadata:
        additions.append(
            f"_install_object_api({model.model_name}, {model.table_name!r}, {model.fields!r})"
        )
    return source.rstrip("\r\n") + newline * 2 + newline.join(additions) + newline


def _helper_source(models: tuple[ModelMetadata, ...]) -> str:
    lines = [
        '"""Lazy registry for generated FlatBuffers object models."""',
        "",
        "import importlib",
        "",
        "",
        "_MODELS = {",
    ]
    for model in sorted(models, key=lambda item: item.table_name.lower()):
        lines.append(
            f"    {model.table_name.lower()!r}: ({model.module!r}, {model.model_name!r}),"
        )
    lines.extend(
        [
            "}",
            "",
            "",
            "def get_flat_data_by_name(name):",
            "    target = _MODELS.get(name)",
            "    if target is None:",
            "        return None",
            "    module_name, model_name = target",
            "    module = importlib.import_module(module_name)",
            "    return getattr(module, model_name)()",
            "",
        ]
    )
    return "\n".join(lines)


def _atomic_write(path: Path, content: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    file_descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", suffix=".tmp", dir=path.parent
    )
    try:
        with os.fdopen(file_descriptor, "wb") as temporary_file:
            temporary_file.write(content)
            temporary_file.flush()
            os.fsync(temporary_file.fileno())
        os.replace(temporary_name, path)
    except BaseException:
        try:
            os.unlink(temporary_name)
        except FileNotFoundError:
            pass
        raise


def _validate_package(package: str) -> None:
    parts = package.split(".")
    if not parts or any(
        not part.isidentifier() or keyword.iskeyword(part) for part in parts
    ):
        raise ProcessingError(f"invalid Python package name: {package!r}")


def process_directory(directory: Path, package: str, without_decryption: bool) -> None:
    if not directory.is_dir():
        raise ProcessingError(f"not a directory: {directory}")
    _validate_package(package)

    source_files = sorted(
        path
        for path in directory.rglob("*.py")
        if path.name not in {_RUNTIME_FILE, _HELPER_FILE}
    )
    changes: dict[Path, bytes] = {}
    all_models = []

    for path in source_files:
        original_source = path.read_text(encoding="utf-8")
        source = _sanitize_receiver_collision(original_source)
        models = _model_metadata(path, package, source)
        all_models.extend(models)
        processed = (
            source
            if without_decryption
            else _installation_source(source, package, models)
        )
        compile(processed, str(path), "exec")
        if processed != original_source:
            changes[path] = processed.encode("utf-8")

    helper_source = _helper_source(tuple(all_models))
    helper_path = directory / _HELPER_FILE
    compile(helper_source, str(helper_path), "exec")
    helper = helper_source.encode("utf-8")
    if not helper_path.exists() or helper_path.read_bytes() != helper:
        changes[helper_path] = helper

    if not without_decryption:
        runtime_path = Path(__file__).with_name("python_conversion.py")
        runtime = runtime_path.read_bytes()
        compile(runtime, str(runtime_path), "exec")
        output_runtime_path = directory / _RUNTIME_FILE
        if (
            not output_runtime_path.exists()
            or output_runtime_path.read_bytes() != runtime
        ):
            changes[output_runtime_path] = runtime

    for path, content in changes.items():
        _atomic_write(path, content)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--directory", type=Path, required=True)
    parser.add_argument("--package", required=True)
    parser.add_argument("--without-decryption", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    try:
        process_directory(args.directory, args.package, args.without_decryption)
    except (OSError, ProcessingError, SyntaxError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
