# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BattleExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BattleExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBattleExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BattleExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BattleExcel
    def None_(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # BattleExcel
    def None_AsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # BattleExcel
    def None_Length(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BattleExcel
    def None_IsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # BattleExcel
    def Single(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleExcel
    def Guided(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleExcel
    def Blue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleExcel
    def CoverEnter(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleExcel
    def Normal(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # BattleExcel
    def NormalAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # BattleExcel
    def NormalLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BattleExcel
    def NormalIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # BattleExcel
    def Crush(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleExcel
    def Able(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleExcel
    def AllySelf(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleExcel
    def LightArmor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleExcel
    def Wood(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleExcel
    def All(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # BattleExcel
    def AllAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # BattleExcel
    def AllLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BattleExcel
    def AllIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        return o == 0

    # BattleExcel
    def Distance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleExcel
    def CloseToObstacle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleExcel
    def Students(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleExcel
    def Sequence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleExcel
    def UseNextExSkill(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleExcel
    def Student(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleExcel
    def SearchAndMove(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleExcel
    def Position(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleExcel
    def Street(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleExcel
    def D(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleExcel
    def Main(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleExcel
    def Remain(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleExcel
    def Low(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleExcel
    def Resist(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleExcel
    def Ally(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleExcel
    def Main166405e7(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleExcel
    def TargetToCaster(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleExcel
    def Duration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(62))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleExcel
    def Preset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(64))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleExcel
    def FinalDamage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(66))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleExcel
    def SpecialTransStat(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(68))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BattleExcel
    def Talk(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(70))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def BattleExcelStart(builder):
    builder.StartObject(34)

def Start(builder):
    BattleExcelStart(builder)

def BattleExcelAddNone_(builder, none):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(none), 0)

def AddNone_(builder, none):
    BattleExcelAddNone_(builder, none)

def BattleExcelStartNone_Vector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartNone_Vector(builder, numElems):
    return BattleExcelStartNone_Vector(builder, numElems)

def BattleExcelAddSingle(builder, single):
    builder.PrependInt32Slot(1, single, 0)

def AddSingle(builder, single):
    BattleExcelAddSingle(builder, single)

def BattleExcelAddGuided(builder, guided):
    builder.PrependInt32Slot(2, guided, 0)

def AddGuided(builder, guided):
    BattleExcelAddGuided(builder, guided)

def BattleExcelAddBlue(builder, blue):
    builder.PrependInt32Slot(3, blue, 0)

def AddBlue(builder, blue):
    BattleExcelAddBlue(builder, blue)

def BattleExcelAddCoverEnter(builder, coverEnter):
    builder.PrependInt32Slot(4, coverEnter, 0)

def AddCoverEnter(builder, coverEnter):
    BattleExcelAddCoverEnter(builder, coverEnter)

def BattleExcelAddNormal(builder, normal):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(normal), 0)

def AddNormal(builder, normal):
    BattleExcelAddNormal(builder, normal)

def BattleExcelStartNormalVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartNormalVector(builder, numElems):
    return BattleExcelStartNormalVector(builder, numElems)

def BattleExcelAddCrush(builder, crush):
    builder.PrependInt32Slot(6, crush, 0)

def AddCrush(builder, crush):
    BattleExcelAddCrush(builder, crush)

def BattleExcelAddAble(builder, able):
    builder.PrependInt32Slot(7, able, 0)

def AddAble(builder, able):
    BattleExcelAddAble(builder, able)

def BattleExcelAddAllySelf(builder, allySelf):
    builder.PrependInt32Slot(8, allySelf, 0)

def AddAllySelf(builder, allySelf):
    BattleExcelAddAllySelf(builder, allySelf)

def BattleExcelAddLightArmor(builder, lightArmor):
    builder.PrependInt32Slot(9, lightArmor, 0)

def AddLightArmor(builder, lightArmor):
    BattleExcelAddLightArmor(builder, lightArmor)

def BattleExcelAddWood(builder, wood):
    builder.PrependInt32Slot(10, wood, 0)

def AddWood(builder, wood):
    BattleExcelAddWood(builder, wood)

def BattleExcelAddAll(builder, all):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(all), 0)

def AddAll(builder, all):
    BattleExcelAddAll(builder, all)

def BattleExcelStartAllVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartAllVector(builder, numElems):
    return BattleExcelStartAllVector(builder, numElems)

def BattleExcelAddDistance(builder, distance):
    builder.PrependInt32Slot(12, distance, 0)

def AddDistance(builder, distance):
    BattleExcelAddDistance(builder, distance)

def BattleExcelAddCloseToObstacle(builder, closeToObstacle):
    builder.PrependInt32Slot(13, closeToObstacle, 0)

def AddCloseToObstacle(builder, closeToObstacle):
    BattleExcelAddCloseToObstacle(builder, closeToObstacle)

def BattleExcelAddStudents(builder, students):
    builder.PrependInt32Slot(14, students, 0)

def AddStudents(builder, students):
    BattleExcelAddStudents(builder, students)

def BattleExcelAddSequence(builder, sequence):
    builder.PrependInt32Slot(15, sequence, 0)

def AddSequence(builder, sequence):
    BattleExcelAddSequence(builder, sequence)

def BattleExcelAddUseNextExSkill(builder, useNextExSkill):
    builder.PrependInt32Slot(16, useNextExSkill, 0)

def AddUseNextExSkill(builder, useNextExSkill):
    BattleExcelAddUseNextExSkill(builder, useNextExSkill)

def BattleExcelAddStudent(builder, student):
    builder.PrependInt32Slot(17, student, 0)

def AddStudent(builder, student):
    BattleExcelAddStudent(builder, student)

def BattleExcelAddSearchAndMove(builder, searchAndMove):
    builder.PrependInt32Slot(18, searchAndMove, 0)

def AddSearchAndMove(builder, searchAndMove):
    BattleExcelAddSearchAndMove(builder, searchAndMove)

def BattleExcelAddPosition(builder, position):
    builder.PrependInt32Slot(19, position, 0)

def AddPosition(builder, position):
    BattleExcelAddPosition(builder, position)

def BattleExcelAddStreet(builder, street):
    builder.PrependInt32Slot(20, street, 0)

def AddStreet(builder, street):
    BattleExcelAddStreet(builder, street)

def BattleExcelAddD(builder, d):
    builder.PrependInt32Slot(21, d, 0)

def AddD(builder, d):
    BattleExcelAddD(builder, d)

def BattleExcelAddMain(builder, main):
    builder.PrependInt32Slot(22, main, 0)

def AddMain(builder, main):
    BattleExcelAddMain(builder, main)

def BattleExcelAddRemain(builder, remain):
    builder.PrependInt32Slot(23, remain, 0)

def AddRemain(builder, remain):
    BattleExcelAddRemain(builder, remain)

def BattleExcelAddLow(builder, low):
    builder.PrependInt32Slot(24, low, 0)

def AddLow(builder, low):
    BattleExcelAddLow(builder, low)

def BattleExcelAddResist(builder, resist):
    builder.PrependInt32Slot(25, resist, 0)

def AddResist(builder, resist):
    BattleExcelAddResist(builder, resist)

def BattleExcelAddAlly(builder, ally):
    builder.PrependInt32Slot(26, ally, 0)

def AddAlly(builder, ally):
    BattleExcelAddAlly(builder, ally)

def BattleExcelAddMain166405e7(builder, main166405e7):
    builder.PrependInt32Slot(27, main166405e7, 0)

def AddMain166405e7(builder, main166405e7):
    BattleExcelAddMain166405e7(builder, main166405e7)

def BattleExcelAddTargetToCaster(builder, targetToCaster):
    builder.PrependInt32Slot(28, targetToCaster, 0)

def AddTargetToCaster(builder, targetToCaster):
    BattleExcelAddTargetToCaster(builder, targetToCaster)

def BattleExcelAddDuration(builder, duration):
    builder.PrependInt32Slot(29, duration, 0)

def AddDuration(builder, duration):
    BattleExcelAddDuration(builder, duration)

def BattleExcelAddPreset(builder, preset):
    builder.PrependInt32Slot(30, preset, 0)

def AddPreset(builder, preset):
    BattleExcelAddPreset(builder, preset)

def BattleExcelAddFinalDamage(builder, finalDamage):
    builder.PrependInt32Slot(31, finalDamage, 0)

def AddFinalDamage(builder, finalDamage):
    BattleExcelAddFinalDamage(builder, finalDamage)

def BattleExcelAddSpecialTransStat(builder, specialTransStat):
    builder.PrependInt32Slot(32, specialTransStat, 0)

def AddSpecialTransStat(builder, specialTransStat):
    BattleExcelAddSpecialTransStat(builder, specialTransStat)

def BattleExcelAddTalk(builder, talk):
    builder.PrependInt32Slot(33, talk, 0)

def AddTalk(builder, talk):
    BattleExcelAddTalk(builder, talk)

def BattleExcelEnd(builder):
    return builder.EndObject()

def End(builder):
    return BattleExcelEnd(builder)

try:
    from typing import List
except:
    pass

class BattleExcelT(object):

    # BattleExcelT
    def __init__(
        self,
        none = None,
        single = 0,
        guided = 0,
        blue = 0,
        coverEnter = 0,
        normal = None,
        crush = 0,
        able = 0,
        allySelf = 0,
        lightArmor = 0,
        wood = 0,
        all = None,
        distance = 0,
        closeToObstacle = 0,
        students = 0,
        sequence = 0,
        useNextExSkill = 0,
        student = 0,
        searchAndMove = 0,
        position = 0,
        street = 0,
        d = 0,
        main = 0,
        remain = 0,
        low = 0,
        resist = 0,
        ally = 0,
        main166405e7 = 0,
        targetToCaster = 0,
        duration = 0,
        preset = 0,
        finalDamage = 0,
        specialTransStat = 0,
        talk = 0,
    ):
        self.none = none  # type: Optional[List[int]]
        self.single = single  # type: int
        self.guided = guided  # type: int
        self.blue = blue  # type: int
        self.coverEnter = coverEnter  # type: int
        self.normal = normal  # type: Optional[List[int]]
        self.crush = crush  # type: int
        self.able = able  # type: int
        self.allySelf = allySelf  # type: int
        self.lightArmor = lightArmor  # type: int
        self.wood = wood  # type: int
        self.all = all  # type: Optional[List[int]]
        self.distance = distance  # type: int
        self.closeToObstacle = closeToObstacle  # type: int
        self.students = students  # type: int
        self.sequence = sequence  # type: int
        self.useNextExSkill = useNextExSkill  # type: int
        self.student = student  # type: int
        self.searchAndMove = searchAndMove  # type: int
        self.position = position  # type: int
        self.street = street  # type: int
        self.d = d  # type: int
        self.main = main  # type: int
        self.remain = remain  # type: int
        self.low = low  # type: int
        self.resist = resist  # type: int
        self.ally = ally  # type: int
        self.main166405e7 = main166405e7  # type: int
        self.targetToCaster = targetToCaster  # type: int
        self.duration = duration  # type: int
        self.preset = preset  # type: int
        self.finalDamage = finalDamage  # type: int
        self.specialTransStat = specialTransStat  # type: int
        self.talk = talk  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        battleExcel = BattleExcel()
        battleExcel.Init(buf, pos)
        return cls.InitFromObj(battleExcel)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, battleExcel):
        x = BattleExcelT()
        x._UnPack(battleExcel)
        return x

    # BattleExcelT
    def _UnPack(self, battleExcel):
        if battleExcel is None:
            return
        if not battleExcel.None_IsNone():
            if np is None:
                self.none = []
                for i in range(battleExcel.None_Length()):
                    self.none.append(battleExcel.None_(i))
            else:
                self.none = battleExcel.None_AsNumpy()
        self.single = battleExcel.Single()
        self.guided = battleExcel.Guided()
        self.blue = battleExcel.Blue()
        self.coverEnter = battleExcel.CoverEnter()
        if not battleExcel.NormalIsNone():
            if np is None:
                self.normal = []
                for i in range(battleExcel.NormalLength()):
                    self.normal.append(battleExcel.Normal(i))
            else:
                self.normal = battleExcel.NormalAsNumpy()
        self.crush = battleExcel.Crush()
        self.able = battleExcel.Able()
        self.allySelf = battleExcel.AllySelf()
        self.lightArmor = battleExcel.LightArmor()
        self.wood = battleExcel.Wood()
        if not battleExcel.AllIsNone():
            if np is None:
                self.all = []
                for i in range(battleExcel.AllLength()):
                    self.all.append(battleExcel.All(i))
            else:
                self.all = battleExcel.AllAsNumpy()
        self.distance = battleExcel.Distance()
        self.closeToObstacle = battleExcel.CloseToObstacle()
        self.students = battleExcel.Students()
        self.sequence = battleExcel.Sequence()
        self.useNextExSkill = battleExcel.UseNextExSkill()
        self.student = battleExcel.Student()
        self.searchAndMove = battleExcel.SearchAndMove()
        self.position = battleExcel.Position()
        self.street = battleExcel.Street()
        self.d = battleExcel.D()
        self.main = battleExcel.Main()
        self.remain = battleExcel.Remain()
        self.low = battleExcel.Low()
        self.resist = battleExcel.Resist()
        self.ally = battleExcel.Ally()
        self.main166405e7 = battleExcel.Main166405e7()
        self.targetToCaster = battleExcel.TargetToCaster()
        self.duration = battleExcel.Duration()
        self.preset = battleExcel.Preset()
        self.finalDamage = battleExcel.FinalDamage()
        self.specialTransStat = battleExcel.SpecialTransStat()
        self.talk = battleExcel.Talk()

    # BattleExcelT
    def Pack(self, builder):
        if self.none is not None:
            if np is not None and type(self.none) is np.ndarray:
                none = builder.CreateNumpyVector(self.none)
            else:
                BattleExcelStartNone_Vector(builder, len(self.none))
                for i in reversed(range(len(self.none))):
                    builder.PrependInt32(self.none[i])
                none = builder.EndVector()
        if self.normal is not None:
            if np is not None and type(self.normal) is np.ndarray:
                normal = builder.CreateNumpyVector(self.normal)
            else:
                BattleExcelStartNormalVector(builder, len(self.normal))
                for i in reversed(range(len(self.normal))):
                    builder.PrependInt32(self.normal[i])
                normal = builder.EndVector()
        if self.all is not None:
            if np is not None and type(self.all) is np.ndarray:
                all = builder.CreateNumpyVector(self.all)
            else:
                BattleExcelStartAllVector(builder, len(self.all))
                for i in reversed(range(len(self.all))):
                    builder.PrependInt32(self.all[i])
                all = builder.EndVector()
        BattleExcelStart(builder)
        if self.none is not None:
            BattleExcelAddNone_(builder, none)
        BattleExcelAddSingle(builder, self.single)
        BattleExcelAddGuided(builder, self.guided)
        BattleExcelAddBlue(builder, self.blue)
        BattleExcelAddCoverEnter(builder, self.coverEnter)
        if self.normal is not None:
            BattleExcelAddNormal(builder, normal)
        BattleExcelAddCrush(builder, self.crush)
        BattleExcelAddAble(builder, self.able)
        BattleExcelAddAllySelf(builder, self.allySelf)
        BattleExcelAddLightArmor(builder, self.lightArmor)
        BattleExcelAddWood(builder, self.wood)
        if self.all is not None:
            BattleExcelAddAll(builder, all)
        BattleExcelAddDistance(builder, self.distance)
        BattleExcelAddCloseToObstacle(builder, self.closeToObstacle)
        BattleExcelAddStudents(builder, self.students)
        BattleExcelAddSequence(builder, self.sequence)
        BattleExcelAddUseNextExSkill(builder, self.useNextExSkill)
        BattleExcelAddStudent(builder, self.student)
        BattleExcelAddSearchAndMove(builder, self.searchAndMove)
        BattleExcelAddPosition(builder, self.position)
        BattleExcelAddStreet(builder, self.street)
        BattleExcelAddD(builder, self.d)
        BattleExcelAddMain(builder, self.main)
        BattleExcelAddRemain(builder, self.remain)
        BattleExcelAddLow(builder, self.low)
        BattleExcelAddResist(builder, self.resist)
        BattleExcelAddAlly(builder, self.ally)
        BattleExcelAddMain166405e7(builder, self.main166405e7)
        BattleExcelAddTargetToCaster(builder, self.targetToCaster)
        BattleExcelAddDuration(builder, self.duration)
        BattleExcelAddPreset(builder, self.preset)
        BattleExcelAddFinalDamage(builder, self.finalDamage)
        BattleExcelAddSpecialTransStat(builder, self.specialTransStat)
        BattleExcelAddTalk(builder, self.talk)
        battleExcel = BattleExcelEnd(builder)
        return battleExcel

# plana-flatbuffer: object-api conversion
from FlatData._conversion import install_object_api as _install_object_api
_install_object_api(BattleExcelT, 'BattleExcel', (('none', 'int32', True), ('single', 'int32', False), ('guided', 'int32', False), ('blue', 'int32', False), ('coverEnter', 'int32', False), ('normal', 'int32', True), ('crush', 'int32', False), ('able', 'int32', False), ('allySelf', 'int32', False), ('lightArmor', 'int32', False), ('wood', 'int32', False), ('all', 'int32', True), ('distance', 'int32', False), ('closeToObstacle', 'int32', False), ('students', 'int32', False), ('sequence', 'int32', False), ('useNextExSkill', 'int32', False), ('student', 'int32', False), ('searchAndMove', 'int32', False), ('position', 'int32', False), ('street', 'int32', False), ('d', 'int32', False), ('main', 'int32', False), ('remain', 'int32', False), ('low', 'int32', False), ('resist', 'int32', False), ('ally', 'int32', False), ('main166405e7', 'int32', False), ('targetToCaster', 'int32', False), ('duration', 'int32', False), ('preset', 'int32', False), ('finalDamage', 'int32', False), ('specialTransStat', 'int32', False), ('talk', 'int32', False)))
