# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ConstConquestExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ConstConquestExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsConstConquestExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ConstConquestExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ConstConquestExcel
    def ManageUnitChange(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ConstConquestExcel
    def AssistCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ConstConquestExcel
    def PlayTimeLimitInSeconds(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ConstConquestExcel
    def AnimationUnitAmountMin(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ConstConquestExcel
    def AnimationUnitAmountMax(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ConstConquestExcel
    def AnimationUnitDelay(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def ConstConquestExcelStart(builder):
    builder.StartObject(6)

def Start(builder):
    ConstConquestExcelStart(builder)

def ConstConquestExcelAddManageUnitChange(builder, manageUnitChange):
    builder.PrependInt32Slot(0, manageUnitChange, 0)

def AddManageUnitChange(builder, manageUnitChange):
    ConstConquestExcelAddManageUnitChange(builder, manageUnitChange)

def ConstConquestExcelAddAssistCount(builder, assistCount):
    builder.PrependInt32Slot(1, assistCount, 0)

def AddAssistCount(builder, assistCount):
    ConstConquestExcelAddAssistCount(builder, assistCount)

def ConstConquestExcelAddPlayTimeLimitInSeconds(builder, playTimeLimitInSeconds):
    builder.PrependInt32Slot(2, playTimeLimitInSeconds, 0)

def AddPlayTimeLimitInSeconds(builder, playTimeLimitInSeconds):
    ConstConquestExcelAddPlayTimeLimitInSeconds(builder, playTimeLimitInSeconds)

def ConstConquestExcelAddAnimationUnitAmountMin(builder, animationUnitAmountMin):
    builder.PrependInt32Slot(3, animationUnitAmountMin, 0)

def AddAnimationUnitAmountMin(builder, animationUnitAmountMin):
    ConstConquestExcelAddAnimationUnitAmountMin(builder, animationUnitAmountMin)

def ConstConquestExcelAddAnimationUnitAmountMax(builder, animationUnitAmountMax):
    builder.PrependInt32Slot(4, animationUnitAmountMax, 0)

def AddAnimationUnitAmountMax(builder, animationUnitAmountMax):
    ConstConquestExcelAddAnimationUnitAmountMax(builder, animationUnitAmountMax)

def ConstConquestExcelAddAnimationUnitDelay(builder, animationUnitDelay):
    builder.PrependFloat32Slot(5, animationUnitDelay, 0.0)

def AddAnimationUnitDelay(builder, animationUnitDelay):
    ConstConquestExcelAddAnimationUnitDelay(builder, animationUnitDelay)

def ConstConquestExcelEnd(builder):
    return builder.EndObject()

def End(builder):
    return ConstConquestExcelEnd(builder)


class ConstConquestExcelT(object):

    # ConstConquestExcelT
    def __init__(
        self,
        manageUnitChange = 0,
        assistCount = 0,
        playTimeLimitInSeconds = 0,
        animationUnitAmountMin = 0,
        animationUnitAmountMax = 0,
        animationUnitDelay = 0.0,
    ):
        self.manageUnitChange = manageUnitChange  # type: int
        self.assistCount = assistCount  # type: int
        self.playTimeLimitInSeconds = playTimeLimitInSeconds  # type: int
        self.animationUnitAmountMin = animationUnitAmountMin  # type: int
        self.animationUnitAmountMax = animationUnitAmountMax  # type: int
        self.animationUnitDelay = animationUnitDelay  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        constConquestExcel = ConstConquestExcel()
        constConquestExcel.Init(buf, pos)
        return cls.InitFromObj(constConquestExcel)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, constConquestExcel):
        x = ConstConquestExcelT()
        x._UnPack(constConquestExcel)
        return x

    # ConstConquestExcelT
    def _UnPack(self, constConquestExcel):
        if constConquestExcel is None:
            return
        self.manageUnitChange = constConquestExcel.ManageUnitChange()
        self.assistCount = constConquestExcel.AssistCount()
        self.playTimeLimitInSeconds = constConquestExcel.PlayTimeLimitInSeconds()
        self.animationUnitAmountMin = constConquestExcel.AnimationUnitAmountMin()
        self.animationUnitAmountMax = constConquestExcel.AnimationUnitAmountMax()
        self.animationUnitDelay = constConquestExcel.AnimationUnitDelay()

    # ConstConquestExcelT
    def Pack(self, builder):
        ConstConquestExcelStart(builder)
        ConstConquestExcelAddManageUnitChange(builder, self.manageUnitChange)
        ConstConquestExcelAddAssistCount(builder, self.assistCount)
        ConstConquestExcelAddPlayTimeLimitInSeconds(builder, self.playTimeLimitInSeconds)
        ConstConquestExcelAddAnimationUnitAmountMin(builder, self.animationUnitAmountMin)
        ConstConquestExcelAddAnimationUnitAmountMax(builder, self.animationUnitAmountMax)
        ConstConquestExcelAddAnimationUnitDelay(builder, self.animationUnitDelay)
        constConquestExcel = ConstConquestExcelEnd(builder)
        return constConquestExcel

# plana-flatbuffer: object-api conversion
from FlatData._conversion import install_object_api as _install_object_api
_install_object_api(ConstConquestExcelT, 'ConstConquestExcel', (('manageUnitChange', 'int32', False), ('assistCount', 'int32', False), ('playTimeLimitInSeconds', 'int32', False), ('animationUnitAmountMin', 'int32', False), ('animationUnitAmountMax', 'int32', False), ('animationUnitDelay', 'float32', False)))
