# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DefaultFurnitureExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DefaultFurnitureExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDefaultFurnitureExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DefaultFurnitureExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DefaultFurnitureExcel
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # DefaultFurnitureExcel
    def Location(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # DefaultFurnitureExcel
    def PositionX(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # DefaultFurnitureExcel
    def PositionY(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # DefaultFurnitureExcel
    def Rotation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def DefaultFurnitureExcelStart(builder):
    builder.StartObject(5)

def Start(builder):
    DefaultFurnitureExcelStart(builder)

def DefaultFurnitureExcelAddId(builder, id):
    builder.PrependInt64Slot(0, id, 0)

def AddId(builder, id):
    DefaultFurnitureExcelAddId(builder, id)

def DefaultFurnitureExcelAddLocation(builder, location):
    builder.PrependInt32Slot(1, location, 0)

def AddLocation(builder, location):
    DefaultFurnitureExcelAddLocation(builder, location)

def DefaultFurnitureExcelAddPositionX(builder, positionX):
    builder.PrependFloat32Slot(2, positionX, 0.0)

def AddPositionX(builder, positionX):
    DefaultFurnitureExcelAddPositionX(builder, positionX)

def DefaultFurnitureExcelAddPositionY(builder, positionY):
    builder.PrependFloat32Slot(3, positionY, 0.0)

def AddPositionY(builder, positionY):
    DefaultFurnitureExcelAddPositionY(builder, positionY)

def DefaultFurnitureExcelAddRotation(builder, rotation):
    builder.PrependFloat32Slot(4, rotation, 0.0)

def AddRotation(builder, rotation):
    DefaultFurnitureExcelAddRotation(builder, rotation)

def DefaultFurnitureExcelEnd(builder):
    return builder.EndObject()

def End(builder):
    return DefaultFurnitureExcelEnd(builder)


class DefaultFurnitureExcelT(object):

    # DefaultFurnitureExcelT
    def __init__(
        self,
        id = 0,
        location = 0,
        positionX = 0.0,
        positionY = 0.0,
        rotation = 0.0,
    ):
        self.id = id  # type: int
        self.location = location  # type: int
        self.positionX = positionX  # type: float
        self.positionY = positionY  # type: float
        self.rotation = rotation  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        defaultFurnitureExcel = DefaultFurnitureExcel()
        defaultFurnitureExcel.Init(buf, pos)
        return cls.InitFromObj(defaultFurnitureExcel)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, defaultFurnitureExcel):
        x = DefaultFurnitureExcelT()
        x._UnPack(defaultFurnitureExcel)
        return x

    # DefaultFurnitureExcelT
    def _UnPack(self, defaultFurnitureExcel):
        if defaultFurnitureExcel is None:
            return
        self.id = defaultFurnitureExcel.Id()
        self.location = defaultFurnitureExcel.Location()
        self.positionX = defaultFurnitureExcel.PositionX()
        self.positionY = defaultFurnitureExcel.PositionY()
        self.rotation = defaultFurnitureExcel.Rotation()

    # DefaultFurnitureExcelT
    def Pack(self, builder):
        DefaultFurnitureExcelStart(builder)
        DefaultFurnitureExcelAddId(builder, self.id)
        DefaultFurnitureExcelAddLocation(builder, self.location)
        DefaultFurnitureExcelAddPositionX(builder, self.positionX)
        DefaultFurnitureExcelAddPositionY(builder, self.positionY)
        DefaultFurnitureExcelAddRotation(builder, self.rotation)
        defaultFurnitureExcel = DefaultFurnitureExcelEnd(builder)
        return defaultFurnitureExcel

# plana-flatbuffer: object-api conversion
from FlatData._conversion import install_object_api as _install_object_api
_install_object_api(DefaultFurnitureExcelT, 'DefaultFurnitureExcel', (('id', 'int64', False), ('location', 'int32', False), ('positionX', 'float32', False), ('positionY', 'float32', False), ('rotation', 'float32', False)))
