# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FieldContentStageRewardExcelTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FieldContentStageRewardExcelTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFieldContentStageRewardExcelTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FieldContentStageRewardExcelTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FieldContentStageRewardExcelTable
    def DataList(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from FlatData.FieldContentStageRewardExcel import FieldContentStageRewardExcel
            obj = FieldContentStageRewardExcel()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FieldContentStageRewardExcelTable
    def DataListLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FieldContentStageRewardExcelTable
    def DataListIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def FieldContentStageRewardExcelTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    FieldContentStageRewardExcelTableStart(builder)

def FieldContentStageRewardExcelTableAddDataList(builder, dataList):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(dataList), 0)

def AddDataList(builder, dataList):
    FieldContentStageRewardExcelTableAddDataList(builder, dataList)

def FieldContentStageRewardExcelTableStartDataListVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDataListVector(builder, numElems):
    return FieldContentStageRewardExcelTableStartDataListVector(builder, numElems)

def FieldContentStageRewardExcelTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return FieldContentStageRewardExcelTableEnd(builder)

import FlatData.FieldContentStageRewardExcel
try:
    from typing import List
except:
    pass

class FieldContentStageRewardExcelTableT(object):

    # FieldContentStageRewardExcelTableT
    def __init__(
        self,
        dataList = None,
    ):
        self.dataList = dataList  # type: Optional[List[FlatData.FieldContentStageRewardExcel.FieldContentStageRewardExcelT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        fieldContentStageRewardExcelTable = FieldContentStageRewardExcelTable()
        fieldContentStageRewardExcelTable.Init(buf, pos)
        return cls.InitFromObj(fieldContentStageRewardExcelTable)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, fieldContentStageRewardExcelTable):
        x = FieldContentStageRewardExcelTableT()
        x._UnPack(fieldContentStageRewardExcelTable)
        return x

    # FieldContentStageRewardExcelTableT
    def _UnPack(self, fieldContentStageRewardExcelTable):
        if fieldContentStageRewardExcelTable is None:
            return
        if not fieldContentStageRewardExcelTable.DataListIsNone():
            self.dataList = []
            for i in range(fieldContentStageRewardExcelTable.DataListLength()):
                if fieldContentStageRewardExcelTable.DataList(i) is None:
                    self.dataList.append(None)
                else:
                    fieldContentStageRewardExcel_ = FlatData.FieldContentStageRewardExcel.FieldContentStageRewardExcelT.InitFromObj(fieldContentStageRewardExcelTable.DataList(i))
                    self.dataList.append(fieldContentStageRewardExcel_)

    # FieldContentStageRewardExcelTableT
    def Pack(self, builder):
        if self.dataList is not None:
            dataListlist = []
            for i in range(len(self.dataList)):
                dataListlist.append(self.dataList[i].Pack(builder))
            FieldContentStageRewardExcelTableStartDataListVector(builder, len(self.dataList))
            for i in reversed(range(len(self.dataList))):
                builder.PrependUOffsetTRelative(dataListlist[i])
            dataList = builder.EndVector()
        FieldContentStageRewardExcelTableStart(builder)
        if self.dataList is not None:
            FieldContentStageRewardExcelTableAddDataList(builder, dataList)
        fieldContentStageRewardExcelTable = FieldContentStageRewardExcelTableEnd(builder)
        return fieldContentStageRewardExcelTable

# plana-flatbuffer: object-api conversion
from FlatData._conversion import install_object_api as _install_object_api
_install_object_api(FieldContentStageRewardExcelTableT, 'FieldContentStageRewardExcelTable', ())
