# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FieldKeywordExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FieldKeywordExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFieldKeywordExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FieldKeywordExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FieldKeywordExcel
    def UniqueId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # FieldKeywordExcel
    def SeasonId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # FieldKeywordExcel
    def NameLocalizeKey(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FieldKeywordExcel
    def DescriptionLocalizeKey(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FieldKeywordExcel
    def ImagePath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def FieldKeywordExcelStart(builder):
    builder.StartObject(5)

def Start(builder):
    FieldKeywordExcelStart(builder)

def FieldKeywordExcelAddUniqueId(builder, uniqueId):
    builder.PrependInt64Slot(0, uniqueId, 0)

def AddUniqueId(builder, uniqueId):
    FieldKeywordExcelAddUniqueId(builder, uniqueId)

def FieldKeywordExcelAddSeasonId(builder, seasonId):
    builder.PrependInt64Slot(1, seasonId, 0)

def AddSeasonId(builder, seasonId):
    FieldKeywordExcelAddSeasonId(builder, seasonId)

def FieldKeywordExcelAddNameLocalizeKey(builder, nameLocalizeKey):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(nameLocalizeKey), 0)

def AddNameLocalizeKey(builder, nameLocalizeKey):
    FieldKeywordExcelAddNameLocalizeKey(builder, nameLocalizeKey)

def FieldKeywordExcelAddDescriptionLocalizeKey(builder, descriptionLocalizeKey):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(descriptionLocalizeKey), 0)

def AddDescriptionLocalizeKey(builder, descriptionLocalizeKey):
    FieldKeywordExcelAddDescriptionLocalizeKey(builder, descriptionLocalizeKey)

def FieldKeywordExcelAddImagePath(builder, imagePath):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(imagePath), 0)

def AddImagePath(builder, imagePath):
    FieldKeywordExcelAddImagePath(builder, imagePath)

def FieldKeywordExcelEnd(builder):
    return builder.EndObject()

def End(builder):
    return FieldKeywordExcelEnd(builder)


class FieldKeywordExcelT(object):

    # FieldKeywordExcelT
    def __init__(
        self,
        uniqueId = 0,
        seasonId = 0,
        nameLocalizeKey = None,
        descriptionLocalizeKey = None,
        imagePath = None,
    ):
        self.uniqueId = uniqueId  # type: int
        self.seasonId = seasonId  # type: int
        self.nameLocalizeKey = nameLocalizeKey  # type: Optional[str]
        self.descriptionLocalizeKey = descriptionLocalizeKey  # type: Optional[str]
        self.imagePath = imagePath  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        fieldKeywordExcel = FieldKeywordExcel()
        fieldKeywordExcel.Init(buf, pos)
        return cls.InitFromObj(fieldKeywordExcel)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, fieldKeywordExcel):
        x = FieldKeywordExcelT()
        x._UnPack(fieldKeywordExcel)
        return x

    # FieldKeywordExcelT
    def _UnPack(self, fieldKeywordExcel):
        if fieldKeywordExcel is None:
            return
        self.uniqueId = fieldKeywordExcel.UniqueId()
        self.seasonId = fieldKeywordExcel.SeasonId()
        self.nameLocalizeKey = fieldKeywordExcel.NameLocalizeKey()
        self.descriptionLocalizeKey = fieldKeywordExcel.DescriptionLocalizeKey()
        self.imagePath = fieldKeywordExcel.ImagePath()

    # FieldKeywordExcelT
    def Pack(self, builder):
        if self.nameLocalizeKey is not None:
            nameLocalizeKey = builder.CreateString(self.nameLocalizeKey)
        if self.descriptionLocalizeKey is not None:
            descriptionLocalizeKey = builder.CreateString(self.descriptionLocalizeKey)
        if self.imagePath is not None:
            imagePath = builder.CreateString(self.imagePath)
        FieldKeywordExcelStart(builder)
        FieldKeywordExcelAddUniqueId(builder, self.uniqueId)
        FieldKeywordExcelAddSeasonId(builder, self.seasonId)
        if self.nameLocalizeKey is not None:
            FieldKeywordExcelAddNameLocalizeKey(builder, nameLocalizeKey)
        if self.descriptionLocalizeKey is not None:
            FieldKeywordExcelAddDescriptionLocalizeKey(builder, descriptionLocalizeKey)
        if self.imagePath is not None:
            FieldKeywordExcelAddImagePath(builder, imagePath)
        fieldKeywordExcel = FieldKeywordExcelEnd(builder)
        return fieldKeywordExcel

# plana-flatbuffer: object-api conversion
from FlatData._conversion import install_object_api as _install_object_api
_install_object_api(FieldKeywordExcelT, 'FieldKeywordExcel', (('uniqueId', 'int64', False), ('seasonId', 'int64', False), ('nameLocalizeKey', 'string', False), ('descriptionLocalizeKey', 'string', False), ('imagePath', 'string', False)))
