# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TagExcelTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TagExcelTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTagExcelTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TagExcelTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TagExcelTable
    def DataList(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from FlatData.TagExcel import TagExcel
            obj = TagExcel()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TagExcelTable
    def DataListLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TagExcelTable
    def DataListIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def TagExcelTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    TagExcelTableStart(builder)

def TagExcelTableAddDataList(builder, dataList):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(dataList), 0)

def AddDataList(builder, dataList):
    TagExcelTableAddDataList(builder, dataList)

def TagExcelTableStartDataListVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDataListVector(builder, numElems):
    return TagExcelTableStartDataListVector(builder, numElems)

def TagExcelTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return TagExcelTableEnd(builder)

import FlatData.TagExcel
try:
    from typing import List
except:
    pass

class TagExcelTableT(object):

    # TagExcelTableT
    def __init__(
        self,
        dataList = None,
    ):
        self.dataList = dataList  # type: Optional[List[FlatData.TagExcel.TagExcelT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        tagExcelTable = TagExcelTable()
        tagExcelTable.Init(buf, pos)
        return cls.InitFromObj(tagExcelTable)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, tagExcelTable):
        x = TagExcelTableT()
        x._UnPack(tagExcelTable)
        return x

    # TagExcelTableT
    def _UnPack(self, tagExcelTable):
        if tagExcelTable is None:
            return
        if not tagExcelTable.DataListIsNone():
            self.dataList = []
            for i in range(tagExcelTable.DataListLength()):
                if tagExcelTable.DataList(i) is None:
                    self.dataList.append(None)
                else:
                    tagExcel_ = FlatData.TagExcel.TagExcelT.InitFromObj(tagExcelTable.DataList(i))
                    self.dataList.append(tagExcel_)

    # TagExcelTableT
    def Pack(self, builder):
        if self.dataList is not None:
            dataListlist = []
            for i in range(len(self.dataList)):
                dataListlist.append(self.dataList[i].Pack(builder))
            TagExcelTableStartDataListVector(builder, len(self.dataList))
            for i in reversed(range(len(self.dataList))):
                builder.PrependUOffsetTRelative(dataListlist[i])
            dataList = builder.EndVector()
        TagExcelTableStart(builder)
        if self.dataList is not None:
            TagExcelTableAddDataList(builder, dataList)
        tagExcelTable = TagExcelTableEnd(builder)
        return tagExcelTable

# plana-flatbuffer: object-api conversion
from FlatData._conversion import install_object_api as _install_object_api
_install_object_api(TagExcelTableT, 'TagExcelTable', ())
